import type {
  Driver,
  PoiInfo,
  RoutingProfile,
  Terminal,
  Vehicle,
} from "./types";

export const mockDrivers: Driver[] = [
  {
    driver_id: 1001,
    driver_first_name: "Jordan",
    driver_last_name: "Reyes",
    driver_phone_number: "602-555-0142",
    driver_email: "jordan.reyes@fleet.example",
    carrier: "Desert Freight Co.",
    work_status: "IN_TRANSIT",
    driver_owner: "Admin",
    terminal: "Phoenix Hub",
    driver_type: "OWNER_OPERATOR_OO",
    last_known_location: "I-10 E, Casa Grande, AZ",
    latest_update: Date.now() - 5 * 60_000,
  },
  {
    driver_id: 1002,
    driver_first_name: "Alex",
    driver_last_name: "Novak",
    driver_phone_number: "480-555-0199",
    driver_email: "alex.novak@fleet.example",
    carrier: "Desert Freight Co.",
    work_status: "AVAILABLE",
    terminal: "Phoenix Hub",
    driver_type: "COMPANY_DRIVER_CM",
    last_known_location: "Tempe, AZ",
    latest_update: Date.now() - 20 * 60_000,
  },
  {
    driver_id: 1003,
    driver_first_name: "Mia",
    driver_last_name: "Okonkwo",
    driver_phone_number: "702-555-0108",
    driver_email: "mia.o@fleet.example",
    carrier: "Desert Freight Co.",
    work_status: "AVAILABLE",
    terminal: "Las Vegas Yard",
    driver_type: "LEASE_OWNER_LO",
    last_known_location: "Las Vegas, NV",
    latest_update: Date.now() - 90 * 60_000,
  },
  {
    driver_id: 1004,
    driver_first_name: "Sam",
    driver_last_name: "Chen",
    driver_phone_number: "520-555-0166",
    driver_email: "sam.chen@fleet.example",
    carrier: "Desert Freight Co.",
    work_status: "INACTIVE",
    terminal: "Tucson Depot",
    driver_type: "COMPANY_DRIVER_C",
    last_known_location: "Tucson, AZ",
    latest_update: Date.now() - 2 * 24 * 60 * 60_000,
  },
  {
    driver_id: 1005,
    driver_first_name: "Priya",
    driver_last_name: "Shah",
    driver_phone_number: "435-555-0121",
    driver_email: "priya.shah@fleet.example",
    carrier: "Desert Freight Co.",
    work_status: "IN_TRANSIT",
    terminal: "Utah Steel",
    driver_type: "OWNER_OPERATOR_OO",
    last_known_location: "Cedar City, UT",
    latest_update: Date.now() - 12 * 60_000,
  },
];

export const mockProfiles: RoutingProfile[] = [
  {
    id: 6831,
    name: "Default Routing Profile",
    truck_ft_length: 53,
    truck_in_length: 0,
    truck_ft_width: 8,
    truck_in_width: 6,
    truck_ft_height: 13,
    truck_in_height: 6,
    weight_limit: 80000,
    weight_per_axle: 20000,
    axles: 5,
    trailers: 1,
    hazmat: false,
  },
  {
    id: 6832,
    name: "Oversize Flatbed",
    truck_ft_length: 60,
    truck_in_length: 0,
    truck_ft_width: 10,
    truck_in_width: 0,
    truck_ft_height: 14,
    truck_in_height: 0,
    weight_limit: 92000,
    weight_per_axle: 20000,
    axles: 6,
    trailers: 1,
    hazmat: false,
  },
];

export const mockVehicles: Vehicle[] = [
  { vehicle_id: 501, vehicle_name: "Kenworth T680 · Unit 12", vehicle_plate: "AZ 4F-8821", status: "ACTIVE", assigned_driver: "Jordan Reyes" },
  { vehicle_id: 502, vehicle_name: "Peterbilt 579 · Unit 14", vehicle_plate: "AZ 5G-1203", status: "ACTIVE", assigned_driver: "Alex Novak" },
  { vehicle_id: 503, vehicle_name: "Freightliner Cascadia · Unit 22", vehicle_plate: "NV 9K-5521", status: "ACTIVE", assigned_driver: "Mia Okonkwo" },
  { vehicle_id: 504, vehicle_name: "Volvo VNL · Unit 31", vehicle_plate: "AZ 7J-3390", status: "INACTIVE" },
];

export const mockTerminals: Terminal[] = [
  { terminal_id: 1, terminal_name: "Phoenix Hub", location: "Phoenix, AZ", member_count: 14 },
  { terminal_id: 2, terminal_name: "Las Vegas Yard", location: "Las Vegas, NV", member_count: 6 },
  { terminal_id: 3, terminal_name: "Tucson Depot", location: "Tucson, AZ", member_count: 4 },
  { terminal_id: 4, terminal_name: "Utah Steel", location: "Cedar City, UT", member_count: 3 },
];

export const mockPois: PoiInfo[] = [
  { poi_id: 1, name: "Pilot · Casa Grande", latitude: 32.8795, longitude: -111.7574, type: "fuel" },
  { poi_id: 2, name: "Flying J · Kingman", latitude: 35.1894, longitude: -114.053, type: "fuel" },
  { poi_id: 3, name: "Love's · Las Vegas", latitude: 36.21, longitude: -115.1098, type: "fuel" },
  { poi_id: 4, name: "TA · St. George", latitude: 37.0965, longitude: -113.5684, type: "rest" },
];
