import type {
  Driver,
  PoiInfo,
  RoutingProfile,
  Terminal,
  Vehicle,
} from "./types";

export const mockDrivers: Driver[] = [
  {
    driver_id: 1001,
    driver_first_name: "Jordan",
    driver_last_name: "Reyes",
    driver_phone_number: "602-555-0142",
    driver_email: "jordan.reyes@fleet.example",
    carrier: "Desert Freight Co.",
    work_status: "IN_TRANSIT",
    driver_owner: "Admin",
    terminal: "Phoenix Hub",
    driver_type: "OWNER_OPERATOR_OO",
    last_known_location: "I-10 E, Casa Grande, AZ",
    latest_update: Date.now() - 5 * 60_000,
  },
  {
    driver_id: 1002,
    driver_first_name: "Alex",
    driver_last_name: "Novak",
    driver_phone_number: "480-555-0199",
    driver_email: "alex.novak@fleet.example",
    carrier: "Desert Freight Co.",
    work_status: "AVAILABLE",
    terminal: "Phoenix Hub",
    driver_type: "COMPANY_DRIVER_CM",
    last_known_location: "Tempe, AZ",
    latest_update: Date.now() - 20 * 60_000,
  },
  {
    driver_id: 1003,
    driver_first_name: "Mia",
    driver_last_name: "Okonkwo",
    driver_phone_number: "702-555-0108",
    driver_email: "mia.o@fleet.example",
    carrier: "Desert Freight Co.",
    work_status: "AVAILABLE",
    terminal: "Las Vegas Yard",
    driver_type: "LEASE_OWNER_LO",
    last_known_location: "Las Vegas, NV",
    latest_update: Date.now() - 90 * 60_000,
  },
  {
    driver_id: 1004,
    driver_first_name: "Sam",
    driver_last_name: "Chen",
    driver_phone_number: "520-555-0166",
    driver_email: "sam.chen@fleet.example",
    carrier: "Desert Freight Co.",
    work_status: "INACTIVE",
    terminal: "Tucson Depot",
    driver_type: "COMPANY_DRIVER_C",
    last_known_location: "Tucson, AZ",
    latest_update: Date.now() - 2 * 24 * 60 * 60_000,
  },
  {
    driver_id: 1005,
    driver_first_name: "Priya",
    driver_last_name: "Shah",
    driver_phone_number: "435-555-0121",
    driver_email: "priya.shah@fleet.example",
    carrier: "Desert Freight Co.",
    work_status: "IN_TRANSIT",
    terminal: "Utah Steel",
    driver_type: "OWNER_OPERATOR_OO",
    last_known_location: "Cedar City, UT",
    latest_update: Date.now() - 12 * 60_000,
  },
];

export const mockProfiles: RoutingProfile[] = [
  {
    id: 6831,
    name: "Default Routing Profile",
    truck_ft_length: 53,
    truck_in_length: 0,
    truck_ft_width: 8,
    truck_in_width: 6,
    truck_ft_height: 13,
    truck_in_height: 6,
    weight_limit: 80000,
    weight_per_axle: 20000,
    axles: 5,
    trailers: 1,
    hazmat: false,
    avoid_areas: [],
    avoid_bridges: [],
    route_policy: {
      enforce_permitted_network: true,
      enforce_hazmat_restrictions: true,
      enforce_clearance_limits: true,
    },
  },
  {
    id: 6832,
    name: "Oversize Flatbed",
    truck_ft_length: 60,
    truck_in_length: 0,
    truck_ft_width: 10,
    truck_in_width: 0,
    truck_ft_height: 14,
    truck_in_height: 0,
    weight_limit: 92000,
    weight_per_axle: 20000,
    axles: 6,
    trailers: 1,
    hazmat: false,
    avoid_areas: [],
    avoid_bridges: [],
    route_policy: {
      enforce_permitted_network: true,
      enforce_hazmat_restrictions: true,
      enforce_clearance_limits: true,
    },
  },
];

export const mockVehicles: Vehicle[] = [
  { vehicle_id: 501, vehicle_name: "Kenworth T680 · Unit 12", vehicle_plate: "AZ 4F-8821", status: "ACTIVE", assigned_driver: "Jordan Reyes" },
  { vehicle_id: 502, vehicle_name: "Peterbilt 579 · Unit 14", vehicle_plate: "AZ 5G-1203", status: "ACTIVE", assigned_driver: "Alex Novak" },
  { vehicle_id: 503, vehicle_name: "Freightliner Cascadia · Unit 22", vehicle_plate: "NV 9K-5521", status: "ACTIVE", assigned_driver: "Mia Okonkwo" },
  { vehicle_id: 504, vehicle_name: "Volvo VNL · Unit 31", vehicle_plate: "AZ 7J-3390", status: "INACTIVE" },
];

export const mockTerminals: Terminal[] = [
  { terminal_id: 1, terminal_name: "Phoenix Hub", location: "Phoenix, AZ", member_count: 14 },
  { terminal_id: 2, terminal_name: "Las Vegas Yard", location: "Las Vegas, NV", member_count: 6 },
  { terminal_id: 3, terminal_name: "Tucson Depot", location: "Tucson, AZ", member_count: 4 },
  { terminal_id: 4, terminal_name: "Utah Steel", location: "Cedar City, UT", member_count: 3 },
];

export const mockPois: PoiInfo[] = [
  { poi_id: 1, name: "Pilot · Casa Grande", latitude: 32.8795, longitude: -111.7574, type: "fuel" },
  { poi_id: 2, name: "Flying J · Kingman", latitude: 35.1894, longitude: -114.053, type: "fuel" },
  { poi_id: 3, name: "Love's · Las Vegas", latitude: 36.21, longitude: -115.1098, type: "fuel" },
  { poi_id: 4, name: "TA · St. George", latitude: 37.0965, longitude: -113.5684, type: "rest" },
];

// ─── Dispatcher CoPilot Mock Data ───────────────────────────────

import type {
  Load,
  DispatchDriver,
  ParkingStop,
  DetentionEvent,
  CopilotAlert,
} from "./types";

// Helper: ISO string offset from now
const isoOffset = (hoursFromNow: number) =>
  new Date(Date.now() + hoursFromNow * 3600_000).toISOString();

export const mockLoads: Load[] = [
  {
    id: "PHX-2847",
    origin: { lat: 33.4484, lng: -112.074, name: "Phoenix, AZ" },
    destination: { lat: 32.7767, lng: -96.797, name: "Dallas, TX" },
    commodity: "Electronics",
    weight: 42000,
    rate: 3850,
    miles: 1065,
    pickupWindow: { start: isoOffset(0.5), end: isoOffset(2) },
    deliveryWindow: { start: isoOffset(18), end: isoOffset(22) },
    shipper: "West Valley Distribution",
    receiver: "DFW Logistics Hub",
    status: "pending",
    notes: "High-value freight — temperature monitoring required",
  },
  {
    id: "TUC-1134",
    origin: { lat: 32.2226, lng: -110.9747, name: "Tucson, AZ" },
    destination: { lat: 35.0844, lng: -106.6504, name: "Albuquerque, NM" },
    commodity: "Building Materials",
    weight: 44000,
    rate: 1420,
    miles: 450,
    pickupWindow: { start: isoOffset(3), end: isoOffset(5) },
    deliveryWindow: { start: isoOffset(12), end: isoOffset(16) },
    shipper: "Southwest Lumber Co.",
    receiver: "ABQ Construction Supply",
    status: "assigned",
    assignedDriverId: 1005,
  },
  {
    id: "LV-0921",
    origin: { lat: 36.1699, lng: -115.1398, name: "Las Vegas, NV" },
    destination: { lat: 34.0522, lng: -118.2437, name: "Los Angeles, CA" },
    commodity: "Consumer Goods",
    weight: 38000,
    rate: 1650,
    miles: 270,
    pickupWindow: { start: isoOffset(1), end: isoOffset(3) },
    deliveryWindow: { start: isoOffset(8), end: isoOffset(12) },
    shipper: "Vegas Wholesale",
    receiver: "LA Distribution Center",
    status: "pending",
  },
  {
    id: "PHX-3310",
    origin: { lat: 33.4484, lng: -112.074, name: "Phoenix, AZ" },
    destination: { lat: 36.7783, lng: -119.4179, name: "Fresno, CA" },
    commodity: "Produce (Refrigerated)",
    weight: 39000,
    rate: 2800,
    miles: 515,
    pickupWindow: { start: isoOffset(4), end: isoOffset(6) },
    deliveryWindow: { start: isoOffset(14), end: isoOffset(18) },
    shipper: "Arizona Fresh Farms",
    receiver: "Central Valley Cold Storage",
    status: "pending",
    notes: "Reefer required — 34°F",
  },
];

// ─── Dispatch Drivers (ELD-sourced) ─────────────────────────────────
// HOS values derived from ELD shift summaries (8h anchor, FMCSA 11/14h rules)
// driverId cross-reference: 1001=DRV001 (Jordan), 1002=DRV003 (Alex),
//   1003=DRV004 (Mia), 1004=DRV005 (Sam), 1005=DRV002 (Priya)
export const mockDispatchDrivers: DispatchDriver[] = [
  {
    // DRV001 — Jordan Reyes — IN_TRANSIT (driving 7.5h in shift)
    driverId: 1001,
    firstName: "Jordan",
    lastName: "Reyes",
    phone: "602-555-0142",
    email: "jordan.reyes@fleet.example",
    terminal: "Phoenix Hub",
    currentLat: 32.89,   // Casa Grande, AZ (position along I-10)
    currentLng: -111.76,
    currentCity: "Casa Grande, AZ",
    hosRemaining: 5.5,   // 14h window - 8.5h elapsed
    hosDriveRemaining: 3.5,  // 11h - 7.5h driving
    status: "IN_TRANSIT",
    readiness: "unavailable",
    truckType: "Dry Van 53ft",
    costPerMile: 1.85,
  },
  {
    // DRV003 — Alex Novak — AVAILABLE (on duty but not driving)
    driverId: 1002,
    firstName: "Alex",
    lastName: "Novak",
    phone: "480-555-0199",
    email: "alex.novak@fleet.example",
    terminal: "Phoenix Hub",
    currentLat: 33.425,  // Tempe, AZ
    currentLng: -111.94,
    currentCity: "Tempe, AZ",
    hosRemaining: 6.0,   // 14h - 8h on duty
    hosDriveRemaining: 11.0, // No driving yet this shift
    status: "AVAILABLE",
    readiness: "immediate",
    truckType: "Dry Van 53ft",
    costPerMile: 1.72,
  },
  {
    // DRV004 — Mia Okonkwo — AVAILABLE (on duty, Las Vegas)
    driverId: 1003,
    firstName: "Mia",
    lastName: "Okonkwo",
    phone: "702-555-0108",
    email: "mia.o@fleet.example",
    terminal: "Las Vegas Yard",
    currentLat: 36.1699, // Las Vegas, NV
    currentLng: -115.1398,
    currentCity: "Las Vegas, NV",
    hosRemaining: 6.0,   // 14h - 8h on duty window
    hosDriveRemaining: 11.0, // No driving yet this shift
    status: "AVAILABLE",
    readiness: "immediate",
    truckType: "Flatbed 48ft",
    costPerMile: 1.95,
  },
  {
    // DRV005 — Sam Chen — INACTIVE (off duty 2d ago, fully rested)
    driverId: 1004,
    firstName: "Sam",
    lastName: "Chen",
    phone: "520-555-0166",
    email: "sam.chen@fleet.example",
    terminal: "Tucson Depot",
    currentLat: 32.2217, // Tucson, AZ
    currentLng: -110.9265,
    currentCity: "Tucson, AZ",
    hosRemaining: 14.0,  // fully rested
    hosDriveRemaining: 11.0,
    status: "AVAILABLE", // available after full rest
    readiness: "1hr",
    truckType: "Dry Van 53ft",
    costPerMile: 1.68,
  },
  {
    // DRV002 — Priya Shah — IN_TRANSIT (driving from Cedar City, UT)
    driverId: 1005,
    firstName: "Priya",
    lastName: "Shah",
    phone: "435-555-0121",
    email: "priya.shah@fleet.example",
    terminal: "Utah Steel",
    currentLat: 37.6775, // Cedar City, UT
    currentLng: -113.0619,
    currentCity: "Cedar City, UT",
    hosRemaining: 6.0,   // 14h - 8h on duty
    hosDriveRemaining: 4.0,  // 11h - 7h driving
    status: "IN_TRANSIT",
    readiness: "unavailable",
    truckType: "Dry Van 53ft",
    costPerMile: 1.90,
  },
];

export const mockParkingStops: ParkingStop[] = [
  {
    id: "pk-1",
    name: "Pilot Travel Center",
    lat: 32.43,
    lng: -109.86,
    city: "Lordsburg, NM",
    type: "truck_stop",
    totalSpaces: 120,
    occupancyPercent: 55,
    reservable: true,
    amenities: ["Fuel", "Showers", "Restaurant", "WiFi"],
    milesFromOrigin: 310,
  },
  {
    id: "pk-2",
    name: "Love's Travel Stop",
    lat: 32.34,
    lng: -107.64,
    city: "Deming, NM",
    type: "truck_stop",
    totalSpaces: 90,
    occupancyPercent: 68,
    reservable: true,
    amenities: ["Fuel", "Showers", "Subway"],
    milesFromOrigin: 375,
  },
  {
    id: "pk-3",
    name: "Flying J Travel Center",
    lat: 34.18,
    lng: -103.33,
    city: "Tucumcari, NM",
    type: "truck_stop",
    totalSpaces: 105,
    occupancyPercent: 72,
    reservable: true,
    amenities: ["Fuel", "Showers", "Denny's", "WiFi"],
    milesFromOrigin: 620,
  },
  {
    id: "pk-4",
    name: "TA Travel Center Amarillo",
    lat: 35.19,
    lng: -101.83,
    city: "Amarillo, TX",
    type: "truck_stop",
    totalSpaces: 150,
    occupancyPercent: 88,
    reservable: true,
    amenities: ["Fuel", "Showers", "TA Restaurant", "WiFi", "Scales"],
    milesFromOrigin: 780,
  },
  {
    id: "pk-5",
    name: "Shamrock Truck Stop",
    lat: 35.22,
    lng: -100.25,
    city: "Shamrock, TX",
    type: "truck_stop",
    totalSpaces: 65,
    occupancyPercent: 45,
    reservable: false,
    amenities: ["Fuel", "Showers"],
    milesFromOrigin: 745,
  },
  {
    id: "pk-6",
    name: "Love's Childress",
    lat: 34.43,
    lng: -100.2,
    city: "Childress, TX",
    type: "truck_stop",
    totalSpaces: 80,
    occupancyPercent: 52,
    reservable: true,
    amenities: ["Fuel", "Showers", "Arby's", "WiFi"],
    milesFromOrigin: 710,
  },
];

export const mockDetentionEvents: DetentionEvent[] = [
  {
    id: "det-1",
    loadId: "PHX-2847",
    location: "pickup",
    facilityName: "West Valley Distribution",
    delayMinutes: 120,
    startedAt: isoOffset(-0.5),
    costPerHour: 75,
  },
  {
    id: "det-2",
    loadId: "TUC-1134",
    location: "pickup",
    facilityName: "Southwest Lumber Co.",
    delayMinutes: 35,
    startedAt: isoOffset(-1),
    costPerHour: 65,
  },
];

export const mockAlerts: CopilotAlert[] = [
  {
    id: "alt-1",
    type: "detention_delay",
    severity: "critical",
    title: "2-Hour Detention at Phoenix Shipper",
    message: "Driver Jordan Reyes held at West Valley Distribution for 2 hours. HOS reduced from 9.5h to 7.5h. Trip plan requires recalculation.",
    loadId: "PHX-2847",
    driverId: 1001,
    timestamp: isoOffset(-0.25),
    actionLabel: "View Impact",
    dismissed: false,
  },
  {
    id: "alt-2",
    type: "parking_risk",
    severity: "warning",
    title: "Parking Risk — Amarillo TA Now High Risk",
    message: "With 2h delay, arrival at Amarillo TA pushed to 9:30 PM. Occupancy projected 92%. Backup stop recommended.",
    loadId: "PHX-2847",
    timestamp: isoOffset(-0.15),
    actionLabel: "View Parking Plan",
    dismissed: false,
  },
  {
    id: "alt-3",
    type: "late_delivery_risk",
    severity: "warning",
    title: "ETA Slipping — Dallas Delivery at Risk",
    message: "Updated ETA is now 2h past original schedule. Delivery window closes in 20h. On-time feasibility: marginal.",
    loadId: "PHX-2847",
    timestamp: isoOffset(-0.1),
    actionLabel: "Notify Customer",
    dismissed: false,
  },
  {
    id: "alt-4",
    type: "hos_violation_risk",
    severity: "critical",
    title: "HOS Violation Risk Within 6 Hours",
    message: "Driver Jordan Reyes has 7.5h drive time remaining. Trip to Dallas requires ~15h drive time. Mandatory rest stop required.",
    loadId: "PHX-2847",
    driverId: 1001,
    timestamp: isoOffset(-0.08),
    dismissed: false,
  },
  {
    id: "alt-5",
    type: "detention_cost",
    severity: "info",
    title: "Detention Cost Update — $150 Accrued",
    message: "2-hour detention at West Valley Distribution at $75/hr. Total added cost: $150. Trip margin reduced to 18%.",
    loadId: "PHX-2847",
    timestamp: isoOffset(-0.05),
    dismissed: false,
  },
  {
    id: "alt-6",
    type: "better_driver",
    severity: "info",
    title: "Closer Driver Available for LV-0921",
    message: "Mia Okonkwo is 12 mi from Las Vegas pickup. Current assignment unset. Deadhead savings: 280 mi vs. next best.",
    loadId: "LV-0921",
    driverId: 1003,
    timestamp: isoOffset(-0.02),
    actionLabel: "Assign Driver",
    dismissed: false,
  },
];
