import type {
  CostTrendPoint,
  CurrentTrip,
  DashboardKpi,
  DetentionCase,
  DocumentBillingCase,
  DriverReadinessBreakdown,
  DispatcherSnapshot,
  DispatcherTask,
  LastMileInsight,
  LoadBoardRecord,
  OperationalAlert,
  OperationsDriver,
  OperationsVehicle,
  RepairShopOption,
  RouteChoice,
  SafetyCase,
} from "./types";

const now = new Date("2026-04-19T10:34:00-07:00");

function iso(hoursFromNow: number) {
  return new Date(now.getTime() + hoursFromNow * 60 * 60 * 1000).toISOString();
}

function minutesFromNow(minutes: number) {
  return new Date(now.getTime() + minutes * 60 * 1000).toISOString();
}

function scoreParts(seed: {
  deadhead: number;
  hos: number;
  trip: number;
  equipment: number;
  maintenance: number;
  tomorrow: number;
  stranded: number;
  fuel: number;
  parking: number;
}): DriverReadinessBreakdown[] {
  return [
    { key: "deadhead", label: "Deadhead", weight: 20, rawScore: seed.deadhead, weightedScore: seed.deadhead * 0.2, explanation: "Pickup reach and empty miles." },
    { key: "hos", label: "HOS feasibility", weight: 20, rawScore: seed.hos, weightedScore: seed.hos * 0.2, explanation: "Available drive and duty window." },
    { key: "trip_time", label: "Trip time", weight: 10, rawScore: seed.trip, weightedScore: seed.trip * 0.1, explanation: "Total trip duration against the day plan." },
    { key: "equipment", label: "Equipment fit", weight: 10, rawScore: seed.equipment, weightedScore: seed.equipment * 0.1, explanation: "Trailer and cargo compatibility." },
    { key: "maintenance", label: "Maintenance / ELD", weight: 10, rawScore: seed.maintenance, weightedScore: seed.maintenance * 0.1, explanation: "Vehicle health and ELD confidence." },
    { key: "tomorrow_impact", label: "Tomorrow impact", weight: 10, rawScore: seed.tomorrow, weightedScore: seed.tomorrow * 0.1, explanation: "Effect on tomorrow's committed freight." },
    { key: "stranded_risk", label: "Stranded risk", weight: 10, rawScore: seed.stranded, weightedScore: seed.stranded * 0.1, explanation: "Avoid leaving a driver unusable after delivery." },
    { key: "fuel_plan", label: "Fuel economics", weight: 5, rawScore: seed.fuel, weightedScore: seed.fuel * 0.05, explanation: "MPG and fuel-network savings." },
    { key: "parking_viability", label: "Parking viability", weight: 5, rawScore: seed.parking, weightedScore: seed.parking * 0.05, explanation: "Likelihood of clean HOS stop execution." },
  ];
}

function routeChoices(base: {
  cheapest: [number, number, number, number, number, number];
  fastest: [number, number, number, number, number, number];
  shortest: [number, number, number, number, number, number];
  recommended: [number, number, number, number, number, number];
  warning?: string;
}): RouteChoice[] {
  return [
    {
      id: "cheapest",
      label: "Cheapest",
      miles: base.cheapest[0],
      etaMinutes: base.cheapest[1],
      fuelCost: base.cheapest[2],
      tolls: base.cheapest[3],
      fuelPartnerSavings: base.cheapest[4],
      leftoverHosHours: base.cheapest[5],
      parkingViability: 72,
      legalityScore: 92,
      weatherRisk: "medium",
      closureRisk: "low",
      detentionSensitivity: "medium",
      lastMileConfidence: 76,
      permitted: true,
      stateWarnings: base.warning ? [base.warning] : [],
      explanation: "Lowest modeled route cost after partner fuel savings and toll tradeoffs.",
    },
    {
      id: "fastest",
      label: "Fastest",
      miles: base.fastest[0],
      etaMinutes: base.fastest[1],
      fuelCost: base.fastest[2],
      tolls: base.fastest[3],
      fuelPartnerSavings: base.fastest[4],
      leftoverHosHours: base.fastest[5],
      parkingViability: 64,
      legalityScore: 91,
      weatherRisk: "medium",
      closureRisk: "medium",
      detentionSensitivity: "high",
      lastMileConfidence: 80,
      permitted: true,
      stateWarnings: base.warning ? [base.warning] : [],
      explanation: "Best ETA, but tighter on HOS cushion and detention slippage.",
    },
    {
      id: "shortest",
      label: "Shortest",
      miles: base.shortest[0],
      etaMinutes: base.shortest[1],
      fuelCost: base.shortest[2],
      tolls: base.shortest[3],
      fuelPartnerSavings: base.shortest[4],
      leftoverHosHours: base.shortest[5],
      parkingViability: 68,
      legalityScore: 89,
      weatherRisk: "low",
      closureRisk: "medium",
      detentionSensitivity: "medium",
      lastMileConfidence: 74,
      permitted: true,
      stateWarnings: base.warning ? [base.warning] : [],
      explanation: "Fewest miles, but not always the best schedule or stop pattern.",
    },
    {
      id: "recommended",
      label: "Recommended",
      miles: base.recommended[0],
      etaMinutes: base.recommended[1],
      fuelCost: base.recommended[2],
      tolls: base.recommended[3],
      fuelPartnerSavings: base.recommended[4],
      leftoverHosHours: base.recommended[5],
      parkingViability: 84,
      legalityScore: 97,
      weatherRisk: "low",
      closureRisk: "low",
      detentionSensitivity: "low",
      lastMileConfidence: 89,
      permitted: true,
      stateWarnings: base.warning ? [base.warning] : [],
      explanation: "Best deterministic balance of legality, ETA cushion, parking confidence, and downstream impact.",
    },
  ];
}

export const demoVehicles: OperationsVehicle[] = [
  { id: "veh-05", unit: "T-05", equipment: "Dry Van 53", status: "active", assignedDriverId: "drv-patel", currentFuelPercent: 82, maintenanceScore: 92, mpgLoaded: 6.8, mpgEmpty: 7.4 },
  { id: "veh-14", unit: "T-14", equipment: "Reefer 53", status: "active", assignedDriverId: "drv-ramirez", currentFuelPercent: 17, maintenanceScore: 73, mpgLoaded: 5.9, mpgEmpty: 6.5 },
  { id: "veh-03", unit: "T-03", equipment: "Dry Van 53", status: "active", assignedDriverId: "drv-nguyen", currentFuelPercent: 61, maintenanceScore: 89, mpgLoaded: 6.4, mpgEmpty: 7.1 },
  { id: "veh-12", unit: "T-12", equipment: "Dry Van 53", status: "active", assignedDriverId: "drv-chen", currentFuelPercent: 55, maintenanceScore: 78, mpgLoaded: 6.3, mpgEmpty: 6.9 },
  { id: "veh-21", unit: "T-21", equipment: "Flatbed", status: "active", assignedDriverId: "drv-williams", currentFuelPercent: 74, maintenanceScore: 88, mpgLoaded: 5.8, mpgEmpty: 6.4 },
  { id: "veh-08", unit: "T-08", equipment: "Dry Van 53", status: "breakdown", assignedDriverId: "drv-martinez", currentFuelPercent: 44, maintenanceScore: 42, mpgLoaded: 5.7, mpgEmpty: 6.2 },
  { id: "veh-09", unit: "T-09", equipment: "Dry Van 53", status: "available", assignedDriverId: "drv-okafor", currentFuelPercent: 79, maintenanceScore: 94, mpgLoaded: 6.9, mpgEmpty: 7.3 },
  { id: "veh-16", unit: "T-16", equipment: "Reefer 53", status: "available", assignedDriverId: "drv-reed", currentFuelPercent: 68, maintenanceScore: 91, mpgLoaded: 6.1, mpgEmpty: 6.6 },
  { id: "veh-18", unit: "T-18", equipment: "Power Only", status: "available", assignedDriverId: "drv-johnson", currentFuelPercent: 63, maintenanceScore: 86, mpgLoaded: 6.0, mpgEmpty: 6.7 },
  { id: "veh-11", unit: "T-11", equipment: "Dry Van 53", status: "active", assignedDriverId: "drv-davis", currentFuelPercent: 81, maintenanceScore: 95, mpgLoaded: 6.7, mpgEmpty: 7.1 },
  { id: "veh-25", unit: "T-25", equipment: "Flatbed", status: "maintenance", assignedDriverId: "drv-brown", currentFuelPercent: 37, maintenanceScore: 58, mpgLoaded: 5.5, mpgEmpty: 6.1 },
  { id: "veh-17", unit: "T-17", equipment: "Dry Van 53", status: "available", assignedDriverId: "drv-jackson", currentFuelPercent: 72, maintenanceScore: 90, mpgLoaded: 6.8, mpgEmpty: 7.2 },
  { id: "veh-33", unit: "T-33", equipment: "Dry Van 53", status: "available", currentFuelPercent: 84, maintenanceScore: 93, mpgLoaded: 6.8, mpgEmpty: 7.5 },
  { id: "veh-34", unit: "T-34", equipment: "Reefer 53", status: "available", currentFuelPercent: 88, maintenanceScore: 93, mpgLoaded: 6.0, mpgEmpty: 6.7 },
  { id: "veh-35", unit: "T-35", equipment: "Flatbed", status: "available", currentFuelPercent: 76, maintenanceScore: 87, mpgLoaded: 5.7, mpgEmpty: 6.2 },
  { id: "veh-36", unit: "T-36", equipment: "Dry Van 53", status: "active", currentFuelPercent: 59, maintenanceScore: 79, mpgLoaded: 6.2, mpgEmpty: 6.8 },
  { id: "veh-37", unit: "T-37", equipment: "Dry Van 53", status: "active", currentFuelPercent: 65, maintenanceScore: 84, mpgLoaded: 6.5, mpgEmpty: 6.9 },
  { id: "veh-38", unit: "T-38", equipment: "Dry Van 53", status: "available", currentFuelPercent: 69, maintenanceScore: 90, mpgLoaded: 6.7, mpgEmpty: 7.2 },
  { id: "veh-39", unit: "T-39", equipment: "Reefer 53", status: "active", currentFuelPercent: 57, maintenanceScore: 81, mpgLoaded: 5.9, mpgEmpty: 6.5 },
  { id: "veh-40", unit: "T-40", equipment: "Flatbed", status: "active", currentFuelPercent: 53, maintenanceScore: 83, mpgLoaded: 5.6, mpgEmpty: 6.3 },
  { id: "veh-41", unit: "T-41", equipment: "Dry Van 53", status: "available", currentFuelPercent: 92, maintenanceScore: 96, mpgLoaded: 6.9, mpgEmpty: 7.5 },
  { id: "veh-42", unit: "T-42", equipment: "Dry Van 53", status: "maintenance", currentFuelPercent: 48, maintenanceScore: 51, mpgLoaded: 6.0, mpgEmpty: 6.4 },
  { id: "veh-43", unit: "T-43", equipment: "Dry Van 53", status: "available", currentFuelPercent: 77, maintenanceScore: 89, mpgLoaded: 6.8, mpgEmpty: 7.2 },
  { id: "veh-44", unit: "T-44", equipment: "Power Only", status: "available", currentFuelPercent: 85, maintenanceScore: 94, mpgLoaded: 6.6, mpgEmpty: 7.1 },
];

export const demoDrivers: OperationsDriver[] = [
  {
    id: "drv-patel",
    firstName: "Sanjay",
    lastName: "Patel",
    unit: "T-05",
    truckType: "Dry Van 53",
    terminal: "Dallas",
    status: "available",
    currentCity: "Dallas, TX",
    currentLat: 32.792,
    currentLng: -96.807,
    currentRoute: "Waiting at Dallas logistics park",
    hosRemainingHours: 11.2,
    deadheadMiles: 14,
    readinessScore: 96,
    maintenanceScore: 92,
    csaScore: 11,
    profitabilityScore: 91,
    currentFuelPercent: 82,
    mpgLoaded: 6.8,
    mpgEmpty: 7.4,
    maintenanceRisk: "low",
    downstreamImpact: "No downstream stranding risk. Clears Houston and resets in time for tomorrow's San Antonio tender.",
    eldProvider: "Motive",
    breakdownStatus: "none",
    readinessBreakdown: scoreParts({ deadhead: 96, hos: 98, trip: 92, equipment: 100, maintenance: 92, tomorrow: 90, stranded: 96, fuel: 88, parking: 84 }),
    profile: {
      bio: "Senior OTR driver with high-service shipper history on Texas triangle lanes.",
      phone: "214-555-0105",
      email: "sanjay.patel@truckerpath.demo",
      historicalTrips: ["Dallas -> Houston retail finals", "Fort Worth -> Austin grocery", "Waco -> El Paso transfer"],
      incidents: [],
      hosTrend: "Stable utilization. Usually lands with 2h+ cushion.",
      fuelEfficiency: "6.8 MPG loaded / 7.4 MPG empty",
      averageTripDuration: "8h 14m",
      averageMargin: "$742 avg margin",
      safetyStats: ["0 preventable incidents in last 12 months", "96% on-time check-ins"],
      inspections: ["Level 1 clean - Jan 14", "DOT annual current"],
      violations: [],
      overview: {
        summary: "Patel is the cleanest urgency match in Dallas for load #4812 and is ready for OTR immediately.",
        recommendations: ["Assign urgent Dallas outbound first", "Keep Houston reload window open after delivery"],
        readyForOtrNow: true,
        readyExplanation: "High HOS, low deadhead, correct trailer, and no downstream conflicts.",
      },
      futureCommitments: ["Tomorrow 09:00 San Antonio replenishment hold"],
    },
  },
  {
    id: "drv-ramirez",
    firstName: "Ana",
    lastName: "Ramirez",
    unit: "T-14",
    truckType: "Reefer 53",
    terminal: "Lubbock",
    status: "active",
    currentCity: "Abilene, TX",
    currentLat: 32.449,
    currentLng: -99.733,
    currentRoute: "Lubbock -> Abilene produce",
    currentLoadId: "LD-4799",
    currentTripId: "TR-014",
    hosRemainingHours: 1.47,
    deadheadMiles: 78,
    readinessScore: 44,
    maintenanceScore: 73,
    csaScore: 22,
    profitabilityScore: 70,
    currentFuelPercent: 17,
    mpgLoaded: 5.9,
    mpgEmpty: 6.5,
    maintenanceRisk: "medium",
    downstreamImpact: "Needs relay or fuel stop; current trip threatens delivery and next pickup.",
    eldProvider: "Samsara",
    idleSince: minutesFromNow(-12),
    breakdownStatus: "none",
    readinessBreakdown: scoreParts({ deadhead: 62, hos: 24, trip: 38, equipment: 92, maintenance: 70, tomorrow: 55, stranded: 42, fuel: 20, parking: 34 }),
    profile: {
      bio: "Strong reefer driver who performs well on West Texas food lanes but is currently pinched by fuel and hours.",
      phone: "806-555-0114",
      email: "ana.ramirez@truckerpath.demo",
      historicalTrips: ["Lubbock -> Dallas reefer", "Midland -> Amarillo dairy", "Clovis -> San Antonio produce"],
      incidents: ["1 late arrival in prior quarter due to weather"],
      hosTrend: "Healthy normally, but this week has multiple tight turns.",
      fuelEfficiency: "5.9 MPG loaded / 6.5 MPG empty",
      averageTripDuration: "10h 06m",
      averageMargin: "$604 avg margin",
      safetyStats: ["1 HOS close-call in last 90 days", "CSA 22"],
      inspections: ["Level 3 inspection - Mar 02"],
      violations: ["None in last 12 months"],
      overview: {
        summary: "Ramirez needs intervention now: fuel plus HOS pressure makes the current plan brittle.",
        recommendations: ["Send partner fuel stop", "Evaluate Okafor relay", "Draft notice if ETA slips again"],
        readyForOtrNow: false,
        readyExplanation: "Insufficient drive time for another assignment until current exception clears.",
      },
      futureCommitments: ["Customer hold for Tuesday Amarillo reefer pool"],
    },
  },
  {
    id: "drv-nguyen",
    firstName: "Thu",
    lastName: "Nguyen",
    unit: "T-03",
    truckType: "Dry Van 53",
    terminal: "Kansas City",
    status: "active",
    currentCity: "Salina, KS",
    currentLat: 38.8403,
    currentLng: -97.6114,
    currentRoute: "Kansas City -> St. Louis retail",
    currentLoadId: "LD-4807",
    currentTripId: "TR-003",
    hosRemainingHours: 7.8,
    deadheadMiles: 0,
    readinessScore: 72,
    maintenanceScore: 89,
    csaScore: 18,
    profitabilityScore: 83,
    currentFuelPercent: 61,
    mpgLoaded: 6.4,
    mpgEmpty: 7.1,
    maintenanceRisk: "low",
    downstreamImpact: "Customer SLA risk on active trip due to incident near Salina.",
    eldProvider: "Motive",
    breakdownStatus: "none",
    readinessBreakdown: scoreParts({ deadhead: 80, hos: 78, trip: 68, equipment: 96, maintenance: 88, tomorrow: 75, stranded: 82, fuel: 72, parking: 70 }),
    profile: {
      bio: "Reliable linehaul driver with strong communication history on Midwest freight.",
      phone: "816-555-0103",
      email: "thu.nguyen@truckerpath.demo",
      historicalTrips: ["KC -> St. Louis retail", "Wichita -> Dallas parcel", "Omaha -> Tulsa appliances"],
      incidents: [],
      hosTrend: "Consistent with rare fatigue compression.",
      fuelEfficiency: "6.4 MPG loaded / 7.1 MPG empty",
      averageTripDuration: "7h 48m",
      averageMargin: "$688 avg margin",
      safetyStats: ["0 violations in last year", "Prompt document turnaround"],
      inspections: ["Roadside clean - Feb 11"],
      violations: [],
      overview: {
        summary: "Nguyen is on a solid trip, but weather and traffic have created a customer notice situation.",
        recommendations: ["Review draft notice", "Hold next pickup promise until ETA stabilizes"],
        readyForOtrNow: false,
        readyExplanation: "Currently moving with enough HOS to finish but not available for reassignment.",
      },
      futureCommitments: ["Springfield backhaul placeholder"],
    },
  },
  {
    id: "drv-chen",
    firstName: "Leo",
    lastName: "Chen",
    unit: "T-12",
    truckType: "Dry Van 53",
    terminal: "Joplin",
    status: "active",
    currentCity: "Joplin, MO",
    currentLat: 37.0842,
    currentLng: -94.5133,
    currentRoute: "Idle on service stop",
    currentLoadId: "LD-4835",
    currentTripId: "TR-012",
    hosRemainingHours: 8.3,
    deadheadMiles: 0,
    readinessScore: 61,
    maintenanceScore: 78,
    csaScore: 20,
    profitabilityScore: 77,
    currentFuelPercent: 55,
    mpgLoaded: 6.3,
    mpgEmpty: 6.9,
    maintenanceRisk: "medium",
    downstreamImpact: "ELD sync gap could cause compliance exposure and dispatch hesitation.",
    eldProvider: "Geotab",
    eldErrorCode: "ELD-SYNC-47",
    idleSince: minutesFromNow(-47),
    breakdownStatus: "investigating",
    repairEtaHours: 1.5,
    readinessBreakdown: scoreParts({ deadhead: 78, hos: 82, trip: 70, equipment: 94, maintenance: 42, tomorrow: 72, stranded: 75, fuel: 66, parking: 68 }),
    profile: {
      bio: "Efficient regional driver with good margins but currently blocked by ELD confidence.",
      phone: "417-555-0112",
      email: "leo.chen@truckerpath.demo",
      historicalTrips: ["Joplin -> Tulsa industrial", "Kansas City -> Little Rock parcel", "Joplin -> Memphis retail"],
      incidents: ["ELD restart needed twice this quarter"],
      hosTrend: "Healthy logs when sync is stable.",
      fuelEfficiency: "6.3 MPG loaded / 6.9 MPG empty",
      averageTripDuration: "6h 52m",
      averageMargin: "$566 avg margin",
      safetyStats: ["CSA 20", "Manual-entry review rate elevated"],
      inspections: ["ELD calibration - Jan 28"],
      violations: ["1 missing annotation warning"],
      overview: {
        summary: "Chen is operationally strong, but dispatch should clear the ELD gap before stacking more exposure.",
        recommendations: ["Call driver", "Confirm manual entries", "Offer nearby certified repair if sync won't recover"],
        readyForOtrNow: false,
        readyExplanation: "Physical truck is usable, but compliance confidence is below dispatch threshold.",
      },
      futureCommitments: ["Little Rock tender reserve"],
    },
  },
  {
    id: "drv-williams",
    firstName: "Darius",
    lastName: "Williams",
    unit: "T-21",
    truckType: "Flatbed",
    terminal: "Wichita",
    status: "active",
    currentCity: "Dallas, TX",
    currentLat: 32.7767,
    currentLng: -96.797,
    currentRoute: "Delivered, awaiting paperwork",
    currentLoadId: "LD-4799",
    currentTripId: "TR-021",
    hosRemainingHours: 6.5,
    deadheadMiles: 0,
    readinessScore: 58,
    maintenanceScore: 88,
    csaScore: 15,
    profitabilityScore: 79,
    currentFuelPercent: 74,
    mpgLoaded: 5.8,
    mpgEmpty: 6.4,
    maintenanceRisk: "low",
    downstreamImpact: "Billing blocked on delivered load until BOL/POD are uploaded.",
    eldProvider: "Motive",
    breakdownStatus: "none",
    readinessBreakdown: scoreParts({ deadhead: 70, hos: 76, trip: 58, equipment: 78, maintenance: 88, tomorrow: 62, stranded: 60, fuel: 72, parking: 74 }),
    profile: {
      bio: "Flatbed specialist with reliable field communication but inconsistent paperwork closeout.",
      phone: "316-555-0121",
      email: "darius.williams@truckerpath.demo",
      historicalTrips: ["Wichita -> Dallas steel", "Tulsa -> Houston flatbed", "Oklahoma City -> El Paso machinery"],
      incidents: ["2 document-lag incidents this quarter"],
      hosTrend: "Generally stable.",
      fuelEfficiency: "5.8 MPG loaded / 6.4 MPG empty",
      averageTripDuration: "9h 18m",
      averageMargin: "$731 avg margin",
      safetyStats: ["CSA 15", "Securement notes consistently clean"],
      inspections: ["Securement inspection clean - Feb 04"],
      violations: [],
      overview: {
        summary: "Williams is physically ready for more work, but billing should be unblocked before the delivered trip is forgotten.",
        recommendations: ["Nudge for BOL/POD", "Hold invoice until receipt lands"],
        readyForOtrNow: true,
        readyExplanation: "Truck and HOS are healthy, but admin follow-up is still open.",
      },
      futureCommitments: ["Thursday steel reload"],
    },
  },
  {
    id: "drv-martinez",
    firstName: "Jose",
    lastName: "Martinez",
    unit: "T-08",
    truckType: "Dry Van 53",
    terminal: "Amarillo",
    status: "breakdown",
    currentCity: "Amarillo, TX",
    currentLat: 35.2219,
    currentLng: -101.8313,
    currentRoute: "Shoulder breakdown on US-287",
    currentLoadId: "LD-4821",
    currentTripId: "TR-008",
    hosRemainingHours: 5.2,
    deadheadMiles: 0,
    readinessScore: 12,
    maintenanceScore: 42,
    csaScore: 27,
    profitabilityScore: 51,
    currentFuelPercent: 44,
    mpgLoaded: 5.7,
    mpgEmpty: 6.2,
    maintenanceRisk: "high",
    downstreamImpact: "Active breakdown threatens tonight's load chain and trailer recovery timing.",
    eldProvider: "Geotab",
    eldErrorCode: "P2459",
    idleSince: minutesFromNow(-92),
    breakdownStatus: "confirmed",
    repairEtaHours: 3.5,
    readinessBreakdown: scoreParts({ deadhead: 10, hos: 28, trip: 18, equipment: 94, maintenance: 8, tomorrow: 30, stranded: 12, fuel: 40, parking: 28 }),
    profile: {
      bio: "Reliable veteran driver caught in a true equipment exception today.",
      phone: "806-555-0108",
      email: "jose.martinez@truckerpath.demo",
      historicalTrips: ["Amarillo -> OKC retail", "Dallas -> Amarillo appliances", "Amarillo -> Kansas City transfer"],
      incidents: ["Current breakdown"],
      hosTrend: "Normal prior to the breakdown event.",
      fuelEfficiency: "5.7 MPG loaded / 6.2 MPG empty",
      averageTripDuration: "8h 41m",
      averageMargin: "$592 avg margin",
      safetyStats: ["CSA 27", "No preventable incidents"],
      inspections: ["PM due in 312 miles before incident"],
      violations: [],
      overview: {
        summary: "Martinez should not be considered for any additional work until repair ETA is confirmed and trailer disposition is decided.",
        recommendations: ["Rank nearest repair shops", "Alert load owner", "Evaluate swap to spare tractor"],
        readyForOtrNow: false,
        readyExplanation: "Truck is down with an active fault and service ETA.",
      },
      futureCommitments: ["Trailer recovery in Amarillo"],
    },
  },
  {
    id: "drv-okafor",
    firstName: "Adaeze",
    lastName: "Okafor",
    unit: "T-09",
    truckType: "Dry Van 53",
    terminal: "Abilene",
    status: "available",
    currentCity: "Sweetwater, TX",
    currentLat: 32.4709,
    currentLng: -100.4059,
    currentRoute: "Waiting near relay corridor",
    hosRemainingHours: 9.7,
    deadheadMiles: 18,
    readinessScore: 88,
    maintenanceScore: 94,
    csaScore: 12,
    profitabilityScore: 86,
    currentFuelPercent: 79,
    mpgLoaded: 6.9,
    mpgEmpty: 7.3,
    maintenanceRisk: "low",
    downstreamImpact: "Can save Ramirez without creating a hole tomorrow.",
    eldProvider: "Motive",
    breakdownStatus: "none",
    readinessBreakdown: scoreParts({ deadhead: 91, hos: 90, trip: 82, equipment: 96, maintenance: 94, tomorrow: 83, stranded: 88, fuel: 81, parking: 80 }),
    profile: {
      bio: "Relay-friendly Texas corridor driver with strong time recovery performance.",
      phone: "325-555-0109",
      email: "adaeze.okafor@truckerpath.demo",
      historicalTrips: ["Abilene relay network", "Midland -> DFW crossdock", "Abilene -> Houston dry van"],
      incidents: [],
      hosTrend: "Clean and well-buffered.",
      fuelEfficiency: "6.9 MPG loaded / 7.3 MPG empty",
      averageTripDuration: "7h 11m",
      averageMargin: "$651 avg margin",
      safetyStats: ["CSA 12", "Fast issue response"],
      inspections: ["Annual current"],
      violations: [],
      overview: {
        summary: "Okafor is the best relay candidate for the Ramirez HOS shortfall.",
        recommendations: ["Stage at MM 261", "Push relay plan before fuel delay compounds"],
        readyForOtrNow: true,
        readyExplanation: "Near the route, healthy HOS, no tomorrow conflict.",
      },
      futureCommitments: ["No locked next-day load"],
    },
  },
  {
    id: "drv-reed",
    firstName: "Marcus",
    lastName: "Reed",
    unit: "T-16",
    truckType: "Reefer 53",
    terminal: "Dallas",
    status: "available",
    currentCity: "Fort Worth, TX",
    currentLat: 32.7555,
    currentLng: -97.3308,
    currentRoute: "Empty near outbound reefer cluster",
    hosRemainingHours: 10.1,
    deadheadMiles: 33,
    readinessScore: 81,
    maintenanceScore: 91,
    csaScore: 16,
    profitabilityScore: 89,
    currentFuelPercent: 68,
    mpgLoaded: 6.1,
    mpgEmpty: 6.6,
    maintenanceRisk: "low",
    downstreamImpact: "Assigning Reed to the wrong load burns tomorrow's higher-margin reefer surge opportunity.",
    eldProvider: "Samsara",
    breakdownStatus: "none",
    readinessBreakdown: scoreParts({ deadhead: 84, hos: 92, trip: 84, equipment: 98, maintenance: 91, tomorrow: 34, stranded: 78, fuel: 72, parking: 74 }),
    profile: {
      bio: "Premium reefer asset with strong outbound Dallas lane economics.",
      phone: "817-555-0116",
      email: "marcus.reed@truckerpath.demo",
      historicalTrips: ["Dallas reefer surge outbound", "Houston grocery return", "San Antonio cold-chain"],
      incidents: [],
      hosTrend: "Excellent.",
      fuelEfficiency: "6.1 MPG loaded / 6.6 MPG empty",
      averageTripDuration: "8h 01m",
      averageMargin: "$812 avg margin",
      safetyStats: ["CSA 16", "High customer score"],
      inspections: ["DOT annual current"],
      violations: [],
      overview: {
        summary: "Reed looks available, but the optimizer should protect tomorrow's reefer surge plan.",
        recommendations: ["Keep for Dallas outbound reefer surge", "Avoid consuming reefer flexibility on low-priority work"],
        readyForOtrNow: true,
        readyExplanation: "Physically ready, but strategically better reserved for tomorrow.",
      },
      futureCommitments: ["Dallas reefer surge placeholder - 06:30 tomorrow"],
    },
  },
  {
    id: "drv-johnson",
    firstName: "Tara",
    lastName: "Johnson",
    unit: "T-18",
    truckType: "Power Only",
    terminal: "Houston",
    status: "available",
    currentCity: "Houston, TX",
    currentLat: 29.7604,
    currentLng: -95.3698,
    currentRoute: "Waiting at yard",
    hosRemainingHours: 9.4,
    deadheadMiles: 12,
    readinessScore: 76,
    maintenanceScore: 86,
    csaScore: 14,
    profitabilityScore: 73,
    currentFuelPercent: 63,
    mpgLoaded: 6,
    mpgEmpty: 6.7,
    maintenanceRisk: "low",
    downstreamImpact: "Strong for bobtail / trailer-recovery work.",
    eldProvider: "Motive",
    breakdownStatus: "none",
    readinessBreakdown: scoreParts({ deadhead: 88, hos: 86, trip: 76, equipment: 64, maintenance: 84, tomorrow: 78, stranded: 82, fuel: 69, parking: 70 }),
    profile: {
      bio: "Flexible power-only driver used for yard, relay, and rescue work.",
      phone: "713-555-0118",
      email: "tara.johnson@truckerpath.demo",
      historicalTrips: ["Houston bobtail recovery", "Yard transfer", "Relay rescue"],
      incidents: [],
      hosTrend: "Stable.",
      fuelEfficiency: "6.0 MPG loaded / 6.7 MPG empty",
      averageTripDuration: "5h 26m",
      averageMargin: "$411 avg margin",
      safetyStats: ["CSA 14"],
      inspections: ["Current"],
      violations: [],
      overview: {
        summary: "Johnson is a flexible rescue asset rather than the first choice for long structured loads.",
        recommendations: ["Use for recovery, swap, or rescue missions"],
        readyForOtrNow: true,
        readyExplanation: "Available now with healthy HOS, though equipment fit is narrower.",
      },
      futureCommitments: [],
    },
  },
  {
    id: "drv-davis",
    firstName: "Quinn",
    lastName: "Davis",
    unit: "T-11",
    truckType: "Dry Van 53",
    terminal: "Oklahoma City",
    status: "active",
    currentCity: "Oklahoma City, OK",
    currentLat: 35.4676,
    currentLng: -97.5164,
    currentRoute: "OKC -> Kansas City parcel",
    currentLoadId: "LD-4818",
    currentTripId: "TR-011",
    hosRemainingHours: 8.9,
    deadheadMiles: 0,
    readinessScore: 80,
    maintenanceScore: 95,
    csaScore: 9,
    profitabilityScore: 88,
    currentFuelPercent: 81,
    mpgLoaded: 6.7,
    mpgEmpty: 7.1,
    maintenanceRisk: "low",
    downstreamImpact: "Strong active trip, healthy economics.",
    eldProvider: "Motive",
    breakdownStatus: "none",
    readinessBreakdown: scoreParts({ deadhead: 82, hos: 90, trip: 80, equipment: 98, maintenance: 96, tomorrow: 80, stranded: 79, fuel: 84, parking: 76 }),
    profile: {
      bio: "Top-performing linehaul driver.",
      phone: "405-555-0111",
      email: "quinn.davis@truckerpath.demo",
      historicalTrips: ["OKC -> KC parcel", "Tulsa -> Chicago transfer"],
      incidents: [],
      hosTrend: "Excellent.",
      fuelEfficiency: "6.7 MPG loaded / 7.1 MPG empty",
      averageTripDuration: "8h 07m",
      averageMargin: "$804 avg margin",
      safetyStats: ["CSA 9"],
      inspections: ["Current"],
      violations: [],
      overview: {
        summary: "Davis is one of the healthiest active linehaul operators in the fleet.",
        recommendations: ["Keep on premium on-time freight"],
        readyForOtrNow: false,
        readyExplanation: "Currently on an active trip.",
      },
      futureCommitments: ["Parcel relay tomorrow"],
    },
  },
  {
    id: "drv-brown",
    firstName: "Keisha",
    lastName: "Brown",
    unit: "T-25",
    truckType: "Flatbed",
    terminal: "Tulsa",
    status: "maintenance",
    currentCity: "Tulsa, OK",
    currentLat: 36.154,
    currentLng: -95.9928,
    currentRoute: "Waiting on PM",
    hosRemainingHours: 10.8,
    deadheadMiles: 0,
    readinessScore: 48,
    maintenanceScore: 58,
    csaScore: 17,
    profitabilityScore: 69,
    currentFuelPercent: 37,
    mpgLoaded: 5.5,
    mpgEmpty: 6.1,
    maintenanceRisk: "high",
    downstreamImpact: "Flatbed capacity constrained until PM clears.",
    eldProvider: "Geotab",
    breakdownStatus: "investigating",
    repairEtaHours: 2,
    readinessBreakdown: scoreParts({ deadhead: 72, hos: 96, trip: 66, equipment: 86, maintenance: 22, tomorrow: 68, stranded: 66, fuel: 30, parking: 72 }),
    profile: {
      bio: "Strong flatbed operator held by maintenance timing today.",
      phone: "918-555-0125",
      email: "keisha.brown@truckerpath.demo",
      historicalTrips: ["Tulsa steel", "Wichita machinery"],
      incidents: [],
      hosTrend: "Strong.",
      fuelEfficiency: "5.5 MPG loaded / 6.1 MPG empty",
      averageTripDuration: "8h 32m",
      averageMargin: "$640 avg margin",
      safetyStats: ["CSA 17"],
      inspections: ["PM overdue"],
      violations: [],
      overview: {
        summary: "Brown is waiting on maintenance clearance and should stay out of new assignments until PM is closed.",
        recommendations: ["Close PM", "Keep flatbed backup lined up"],
        readyForOtrNow: false,
        readyExplanation: "Maintenance hold is active.",
      },
      futureCommitments: [],
    },
  },
  {
    id: "drv-jackson",
    firstName: "Eli",
    lastName: "Jackson",
    unit: "T-17",
    truckType: "Dry Van 53",
    terminal: "San Antonio",
    status: "available",
    currentCity: "San Antonio, TX",
    currentLat: 29.4241,
    currentLng: -98.4936,
    currentRoute: "Reset complete",
    hosRemainingHours: 11,
    deadheadMiles: 21,
    readinessScore: 85,
    maintenanceScore: 90,
    csaScore: 13,
    profitabilityScore: 82,
    currentFuelPercent: 72,
    mpgLoaded: 6.8,
    mpgEmpty: 7.2,
    maintenanceRisk: "low",
    downstreamImpact: "Can cover south Texas spillover if Patel is consumed.",
    eldProvider: "Motive",
    breakdownStatus: "none",
    readinessBreakdown: scoreParts({ deadhead: 88, hos: 96, trip: 80, equipment: 96, maintenance: 90, tomorrow: 82, stranded: 84, fuel: 74, parking: 77 }),
    profile: {
      bio: "High-readiness swing driver for Texas intrastate work.",
      phone: "210-555-0117",
      email: "eli.jackson@truckerpath.demo",
      historicalTrips: ["San Antonio shuttle", "Austin grocery", "Laredo relay"],
      incidents: [],
      hosTrend: "Strong.",
      fuelEfficiency: "6.8 MPG loaded / 7.2 MPG empty",
      averageTripDuration: "6h 44m",
      averageMargin: "$588 avg margin",
      safetyStats: ["CSA 13"],
      inspections: ["Current"],
      violations: [],
      overview: {
        summary: "Jackson is a quality fallback if Dallas capacity gets consumed.",
        recommendations: ["Use for spillover, not first call on #4812"],
        readyForOtrNow: true,
        readyExplanation: "Healthy and reset, but not as perfectly positioned as Patel.",
      },
      futureCommitments: [],
    },
  },
];

export const demoLoads: LoadBoardRecord[] = [
  {
    id: "LD-4812",
    lane: "Dallas -> Houston",
    origin: "Dallas, TX",
    destination: "Houston, TX",
    pickupWindow: "1:00 PM - 4:00 PM",
    deliveryWindow: "8:30 PM - 10:00 PM",
    equipment: "Dry Van 53",
    miles: 243,
    rate: 2280,
    urgency: "critical",
    bestMatchDriverId: "drv-patel",
    bestMatchDriverName: "Sanjay Patel",
    marginProjection: 932,
    docsRequired: ["BOL", "POD", "Rate confirmation"],
    detentionTerms: "$75/hr after 2h",
    aiAssignmentRecommendation: "Patel closes the pickup cleanly with the highest readiness score and no tomorrow stranding.",
    customer: "Lone Star Retail",
    routeChoices: routeChoices({
      cheapest: [249, 275, 154, 19, 18, 5.6],
      fastest: [243, 258, 160, 27, 12, 5.2],
      shortest: [239, 269, 157, 25, 14, 5.1],
      recommended: [246, 264, 156, 21, 17, 5.8],
      warning: "TxDOT oversize and overweight route conditions should be checked day-of on official portals.",
    }),
  },
  {
    id: "LD-4799",
    lane: "Lubbock -> Abilene",
    origin: "Lubbock, TX",
    destination: "Abilene, TX",
    pickupWindow: "Delivered",
    deliveryWindow: "Delivered",
    equipment: "Flatbed",
    miles: 179,
    rate: 1320,
    assignedDriverId: "drv-williams",
    urgency: "high",
    bestMatchDriverId: "drv-williams",
    bestMatchDriverName: "Darius Williams",
    marginProjection: 414,
    docsRequired: ["BOL", "POD"],
    detentionTerms: "$65/hr after 2h",
    aiAssignmentRecommendation: "Complete document collection before billing release.",
    customer: "Basin Steel",
    routeChoices: routeChoices({
      cheapest: [181, 195, 118, 0, 11, 3.2],
      fastest: [179, 190, 120, 0, 9, 3.1],
      shortest: [178, 198, 119, 0, 10, 3.1],
      recommended: [180, 193, 118, 0, 11, 3.3],
    }),
  },
  {
    id: "LD-4807",
    lane: "Kansas City -> St. Louis",
    origin: "Kansas City, MO",
    destination: "St. Louis, MO",
    pickupWindow: "Picked up",
    deliveryWindow: "Today 7:10 PM - 8:30 PM",
    equipment: "Dry Van 53",
    miles: 248,
    rate: 1860,
    assignedDriverId: "drv-nguyen",
    urgency: "high",
    bestMatchDriverId: "drv-nguyen",
    bestMatchDriverName: "Thu Nguyen",
    marginProjection: 688,
    docsRequired: ["BOL", "POD"],
    detentionTerms: "$75/hr after 2h",
    aiAssignmentRecommendation: "Route stays viable, but send the customer-delay draft now.",
    customer: "Midwest Retail Co.",
    routeChoices: routeChoices({
      cheapest: [252, 281, 148, 8, 14, 4.7],
      fastest: [248, 262, 152, 11, 10, 4.1],
      shortest: [246, 275, 149, 10, 12, 4.0],
      recommended: [249, 266, 150, 9, 13, 4.8],
    }),
  },
  {
    id: "LD-4835",
    lane: "Joplin -> Memphis",
    origin: "Joplin, MO",
    destination: "Memphis, TN",
    pickupWindow: "Today 11:30 AM - 1:00 PM",
    deliveryWindow: "Tomorrow 2:00 AM - 4:00 AM",
    equipment: "Dry Van 53",
    miles: 326,
    rate: 2140,
    assignedDriverId: "drv-chen",
    urgency: "medium",
    bestMatchDriverId: "drv-chen",
    bestMatchDriverName: "Leo Chen",
    marginProjection: 704,
    docsRequired: ["BOL", "POD"],
    detentionTerms: "$70/hr after 2h",
    aiAssignmentRecommendation: "Resolve ELD sync gap before allowing departure.",
    customer: "Ozark Consumer",
    routeChoices: routeChoices({
      cheapest: [334, 383, 193, 12, 16, 3.9],
      fastest: [326, 356, 199, 21, 8, 3.5],
      shortest: [322, 372, 194, 17, 11, 3.2],
      recommended: [328, 362, 196, 16, 14, 4.1],
    }),
  },
  {
    id: "LD-4821",
    lane: "Amarillo -> Oklahoma City",
    origin: "Amarillo, TX",
    destination: "Oklahoma City, OK",
    pickupWindow: "Picked up",
    deliveryWindow: "Today 6:00 PM - 7:00 PM",
    equipment: "Dry Van 53",
    miles: 260,
    rate: 1710,
    assignedDriverId: "drv-martinez",
    urgency: "critical",
    bestMatchDriverId: "drv-johnson",
    bestMatchDriverName: "Tara Johnson",
    marginProjection: 521,
    docsRequired: ["BOL", "POD"],
    detentionTerms: "$60/hr after 2h",
    aiAssignmentRecommendation: "Swap or rescue mission required due to breakdown.",
    customer: "Panhandle Supply",
    routeChoices: routeChoices({
      cheapest: [264, 292, 156, 0, 12, 2.8],
      fastest: [260, 278, 160, 0, 10, 2.6],
      shortest: [258, 286, 158, 0, 11, 2.4],
      recommended: [261, 281, 157, 0, 12, 2.9],
    }),
  },
  {
    id: "LD-4818",
    lane: "Oklahoma City -> Kansas City",
    origin: "Oklahoma City, OK",
    destination: "Kansas City, MO",
    pickupWindow: "Picked up",
    deliveryWindow: "Today 8:00 PM - 9:00 PM",
    equipment: "Dry Van 53",
    miles: 353,
    rate: 2330,
    assignedDriverId: "drv-davis",
    urgency: "medium",
    bestMatchDriverId: "drv-davis",
    bestMatchDriverName: "Quinn Davis",
    marginProjection: 798,
    docsRequired: ["BOL", "POD"],
    detentionTerms: "$75/hr after 2h",
    aiAssignmentRecommendation: "Stay the course; current route remains healthiest.",
    customer: "Parcel South",
    routeChoices: routeChoices({
      cheapest: [361, 397, 208, 9, 15, 4.3],
      fastest: [353, 372, 214, 13, 10, 3.8],
      shortest: [350, 389, 210, 12, 11, 3.7],
      recommended: [355, 378, 211, 10, 14, 4.4],
    }),
  },
  {
    id: "LD-4844",
    lane: "Dallas -> Austin",
    origin: "Dallas, TX",
    destination: "Austin, TX",
    pickupWindow: "Today 2:00 PM - 5:00 PM",
    deliveryWindow: "Today 10:00 PM - 11:00 PM",
    equipment: "Dry Van 53",
    miles: 196,
    rate: 1640,
    urgency: "medium",
    bestMatchDriverId: "drv-jackson",
    bestMatchDriverName: "Eli Jackson",
    marginProjection: 612,
    docsRequired: ["BOL", "POD", "Seal record"],
    detentionTerms: "$75/hr after 2h",
    aiAssignmentRecommendation: "Use Jackson only if Patel is consumed by the urgent Houston run.",
    customer: "Capital Foods",
    routeChoices: routeChoices({
      cheapest: [201, 230, 128, 7, 12, 6.4],
      fastest: [196, 216, 133, 12, 8, 6.1],
      shortest: [194, 224, 129, 10, 10, 5.9],
      recommended: [198, 220, 130, 8, 11, 6.5],
    }),
  },
  {
    id: "LD-4850",
    lane: "Houston -> San Antonio",
    origin: "Houston, TX",
    destination: "San Antonio, TX",
    pickupWindow: "Today 3:30 PM - 6:00 PM",
    deliveryWindow: "Tonight 11:00 PM - 1:00 AM",
    equipment: "Power Only",
    miles: 197,
    rate: 1560,
    urgency: "medium",
    bestMatchDriverId: "drv-johnson",
    bestMatchDriverName: "Tara Johnson",
    marginProjection: 544,
    docsRequired: ["POD", "Trailer interchange"],
    detentionTerms: "$60/hr after 2h",
    aiAssignmentRecommendation: "Johnson is best on equipment fit and corridor proximity.",
    customer: "South Gulf Intermodal",
    routeChoices: routeChoices({
      cheapest: [205, 240, 130, 0, 13, 5.8],
      fastest: [197, 224, 134, 0, 10, 5.4],
      shortest: [195, 231, 132, 0, 11, 5.3],
      recommended: [199, 227, 131, 0, 13, 5.9],
    }),
  },
  { id: "LD-4851", lane: "Tulsa -> Little Rock", origin: "Tulsa, OK", destination: "Little Rock, AR", pickupWindow: "Today 1:00 PM - 4:00 PM", deliveryWindow: "Tonight 9:00 PM - 11:00 PM", equipment: "Flatbed", miles: 276, rate: 1880, urgency: "medium", bestMatchDriverId: "drv-brown", bestMatchDriverName: "Keisha Brown", marginProjection: 603, docsRequired: ["BOL", "POD"], detentionTerms: "$70/hr after 2h", aiAssignmentRecommendation: "Wait for Brown's PM closeout or move to backup flatbed.", customer: "Ark Valley Steel", routeChoices: routeChoices({ cheapest: [282, 319, 171, 0, 12, 4.9], fastest: [276, 301, 176, 0, 8, 4.4], shortest: [273, 312, 173, 0, 10, 4.2], recommended: [277, 305, 174, 0, 11, 5.0] }) },
  { id: "LD-4852", lane: "Wichita -> Denver", origin: "Wichita, KS", destination: "Denver, CO", pickupWindow: "Today 4:00 PM - 7:00 PM", deliveryWindow: "Tomorrow 7:00 AM - 9:00 AM", equipment: "Dry Van 53", miles: 525, rate: 2980, urgency: "medium", bestMatchDriverId: "drv-davis", bestMatchDriverName: "Quinn Davis", marginProjection: 975, docsRequired: ["BOL", "POD"], detentionTerms: "$75/hr after 2h", aiAssignmentRecommendation: "Protect state-overlay route review and the mountain weather watch before release.", customer: "Front Range Retail", routeChoices: routeChoices({ cheapest: [537, 580, 309, 22, 24, 2.8], fastest: [525, 548, 317, 35, 13, 2.4], shortest: [518, 571, 312, 29, 18, 2.3], recommended: [529, 553, 313, 24, 22, 3.1], warning: "Colorado permit and I-70 tunnel restrictions require screened review before release." }) },
  { id: "LD-4853", lane: "Kansas City -> Omaha", origin: "Kansas City, MO", destination: "Omaha, NE", pickupWindow: "Today 12:30 PM - 2:30 PM", deliveryWindow: "Today 7:30 PM - 9:00 PM", equipment: "Dry Van 53", miles: 186, rate: 1490, urgency: "low", bestMatchDriverId: "drv-nguyen", bestMatchDriverName: "Thu Nguyen", marginProjection: 551, docsRequired: ["BOL", "POD"], detentionTerms: "$65/hr after 2h", aiAssignmentRecommendation: "Filler regional load with healthy economics.", customer: "Heartland Distribution", routeChoices: routeChoices({ cheapest: [191, 212, 119, 0, 8, 6.3], fastest: [186, 201, 122, 0, 6, 6.0], shortest: [184, 208, 120, 0, 7, 6.0], recommended: [187, 204, 120, 0, 8, 6.5] }) },
  { id: "LD-4854", lane: "St. Louis -> Memphis", origin: "St. Louis, MO", destination: "Memphis, TN", pickupWindow: "Tonight 6:00 PM - 8:00 PM", deliveryWindow: "Tomorrow 2:00 AM - 4:00 AM", equipment: "Dry Van 53", miles: 284, rate: 1930, urgency: "medium", bestMatchDriverId: "drv-nguyen", bestMatchDriverName: "Thu Nguyen", marginProjection: 646, docsRequired: ["BOL", "POD"], detentionTerms: "$75/hr after 2h", aiAssignmentRecommendation: "Good downstream if Nguyen closes current trip cleanly.", customer: "River South Retail", routeChoices: routeChoices({ cheapest: [288, 321, 174, 6, 11, 4.7], fastest: [284, 307, 177, 9, 8, 4.4], shortest: [281, 315, 175, 7, 10, 4.3], recommended: [285, 311, 175, 6, 11, 4.8] }) },
  { id: "LD-4855", lane: "Houston -> New Orleans", origin: "Houston, TX", destination: "New Orleans, LA", pickupWindow: "Today 2:00 PM - 4:30 PM", deliveryWindow: "Tomorrow 12:00 AM - 3:00 AM", equipment: "Reefer 53", miles: 348, rate: 2480, urgency: "high", bestMatchDriverId: "drv-reed", bestMatchDriverName: "Marcus Reed", marginProjection: 812, docsRequired: ["BOL", "POD", "Temp trace"], detentionTerms: "$85/hr after 2h", aiAssignmentRecommendation: "Good reefer economics but can compromise tomorrow's Dallas surge plan.", customer: "Gulf Fresh", routeChoices: routeChoices({ cheapest: [355, 389, 219, 14, 17, 3.9], fastest: [348, 365, 224, 21, 10, 3.6], shortest: [345, 379, 220, 18, 13, 3.4], recommended: [350, 371, 221, 16, 16, 4.2] }) },
  { id: "LD-4856", lane: "Dallas -> Phoenix", origin: "Dallas, TX", destination: "Phoenix, AZ", pickupWindow: "Tonight 8:00 PM - 10:00 PM", deliveryWindow: "Tomorrow 8:00 PM - 11:00 PM", equipment: "Dry Van 53", miles: 1062, rate: 4720, urgency: "medium", bestMatchDriverId: "drv-jackson", bestMatchDriverName: "Eli Jackson", marginProjection: 1491, docsRequired: ["BOL", "POD"], detentionTerms: "$80/hr after 2h", aiAssignmentRecommendation: "Good economics, but tomorrow availability must be protected.", customer: "Desert Electronics", routeChoices: routeChoices({ cheapest: [1081, 1169, 619, 41, 33, 0.8], fastest: [1062, 1112, 637, 56, 19, 0.3], shortest: [1054, 1141, 625, 48, 26, 0.2], recommended: [1068, 1119, 626, 43, 31, 1.0], warning: "Arizona Table 4 and current route-condition checks are required before oversize or restricted moves." }) },
  { id: "LD-4857", lane: "San Antonio -> El Paso", origin: "San Antonio, TX", destination: "El Paso, TX", pickupWindow: "Tomorrow 5:00 AM - 7:00 AM", deliveryWindow: "Tomorrow 5:00 PM - 8:00 PM", equipment: "Dry Van 53", miles: 551, rate: 3110, urgency: "medium", bestMatchDriverId: "drv-jackson", bestMatchDriverName: "Eli Jackson", marginProjection: 990, docsRequired: ["BOL", "POD"], detentionTerms: "$75/hr after 2h", aiAssignmentRecommendation: "Fits Jackson cleanly if he stays clear of the Dallas urgent lane today.", customer: "Border Freight", routeChoices: routeChoices({ cheapest: [560, 612, 323, 11, 20, 2.1], fastest: [551, 588, 330, 18, 13, 1.8], shortest: [545, 604, 326, 15, 16, 1.7], recommended: [552, 591, 326, 12, 19, 2.3] }) },
  { id: "LD-4858", lane: "Omaha -> Kansas City", origin: "Omaha, NE", destination: "Kansas City, MO", pickupWindow: "Tomorrow 9:00 AM - 11:00 AM", deliveryWindow: "Tomorrow 3:00 PM - 5:00 PM", equipment: "Dry Van 53", miles: 186, rate: 1430, urgency: "low", bestMatchDriverId: "drv-davis", bestMatchDriverName: "Quinn Davis", marginProjection: 520, docsRequired: ["BOL", "POD"], detentionTerms: "$65/hr after 2h", aiAssignmentRecommendation: "Regional filler with good asset utilization.", customer: "Heartland Wholesale", routeChoices: routeChoices({ cheapest: [190, 215, 118, 0, 9, 6.0], fastest: [186, 204, 120, 0, 7, 5.7], shortest: [184, 209, 119, 0, 8, 5.7], recommended: [187, 206, 119, 0, 9, 6.2] }) },
  { id: "LD-4859", lane: "Dallas -> Shreveport", origin: "Dallas, TX", destination: "Shreveport, LA", pickupWindow: "Today 5:00 PM - 7:00 PM", deliveryWindow: "Tonight 11:00 PM - 1:00 AM", equipment: "Dry Van 53", miles: 189, rate: 1545, urgency: "medium", bestMatchDriverId: "drv-patel", bestMatchDriverName: "Sanjay Patel", marginProjection: 556, docsRequired: ["BOL", "POD"], detentionTerms: "$70/hr after 2h", aiAssignmentRecommendation: "Second-choice Dallas outbound if Patel is not consumed by #4812.", customer: "Eastline Goods", routeChoices: routeChoices({ cheapest: [193, 220, 123, 5, 9, 6.1], fastest: [189, 208, 126, 8, 6, 5.9], shortest: [188, 215, 124, 7, 7, 5.8], recommended: [190, 211, 124, 5, 9, 6.2] }) },
  { id: "LD-4860", lane: "Fort Worth -> Houston", origin: "Fort Worth, TX", destination: "Houston, TX", pickupWindow: "Today 2:30 PM - 4:30 PM", deliveryWindow: "Tonight 10:00 PM - 11:30 PM", equipment: "Reefer 53", miles: 271, rate: 2420, urgency: "high", bestMatchDriverId: "drv-reed", bestMatchDriverName: "Marcus Reed", marginProjection: 864, docsRequired: ["BOL", "POD", "Temp trace"], detentionTerms: "$85/hr after 2h", aiAssignmentRecommendation: "Operationally attractive now, but dashboard should surface the tomorrow-stranding tradeoff.", customer: "Metro Cold Chain", routeChoices: routeChoices({ cheapest: [278, 314, 171, 15, 14, 5.1], fastest: [271, 296, 177, 24, 8, 4.7], shortest: [268, 307, 173, 20, 10, 4.6], recommended: [272, 300, 173, 17, 13, 5.4] }) },
];

export const demoTrips: CurrentTrip[] = [
  {
    id: "TR-014",
    driverId: "drv-ramirez",
    driverName: "Ana Ramirez",
    truckUnit: "T-14",
    loadId: "LD-4799",
    origin: "Lubbock, TX",
    destination: "Abilene, TX",
    liveHosHours: 1.47,
    liveEta: "Today 1:06 PM",
    routeHealth: "risk",
    fuelStatus: "17% fuel, 80 mi to next TA partner stop",
    parkingStopPlan: "Abilene TA backup reserved",
    detentionState: "No detention, but relay likely",
    alertCount: 4,
    routeOptionsSummary: ["Fuel stop candidate near MM 261", "Relay swap with Okafor saves delivery window"],
    timeline: [
      { id: "1", label: "Loaded in Lubbock", timestamp: iso(-3), tone: "good" },
      { id: "2", label: "Fuel below threshold", timestamp: iso(-0.5), tone: "danger" },
      { id: "3", label: "HOS critical projected before delivery", timestamp: iso(0.2), tone: "warning" },
    ],
    weatherIncidents: [],
    detentionClockMinutes: 0,
    customerSlaRisk: "Medium if relay is not planned in next 20 min",
    downstreamImpact: "Late arrival eats tomorrow's Midland reload",
    nudgesSent: ["Fuel stop draft ready", "Relay note drafted"],
    lastMilePlan: "Standard dock approach",
    routeChoices: demoLoads[1].routeChoices,
  },
  {
    id: "TR-003",
    driverId: "drv-nguyen",
    driverName: "Thu Nguyen",
    truckUnit: "T-03",
    loadId: "LD-4807",
    origin: "Kansas City, MO",
    destination: "St. Louis, MO",
    liveHosHours: 7.8,
    liveEta: "Today 7:52 PM",
    routeHealth: "watch",
    fuelStatus: "61% fuel",
    parkingStopPlan: "Not required if current ETA holds",
    detentionState: "No detention",
    alertCount: 2,
    routeOptionsSummary: ["I-70 traffic event near Salina", "Weather delay adding 1h20m"],
    timeline: [
      { id: "1", label: "Departed KC", timestamp: iso(-2.5), tone: "good" },
      { id: "2", label: "Incident zone entered", timestamp: iso(-0.6), tone: "warning" },
      { id: "3", label: "Customer draft prepared", timestamp: iso(-0.1), tone: "default" },
    ],
    weatherIncidents: ["High wind advisory west of Topeka", "Traffic backup near Salina"],
    detentionClockMinutes: 0,
    customerSlaRisk: "SLA may slip if incident persists beyond 30 min",
    downstreamImpact: "Minimal if notice goes out now",
    nudgesSent: ["Review & send customer notice"],
    lastMilePlan: "North dock lane 2",
    routeChoices: demoLoads[2].routeChoices,
  },
  {
    id: "TR-012",
    driverId: "drv-chen",
    driverName: "Leo Chen",
    truckUnit: "T-12",
    loadId: "LD-4835",
    origin: "Joplin, MO",
    destination: "Memphis, TN",
    liveHosHours: 8.3,
    liveEta: "Tomorrow 3:02 AM",
    routeHealth: "watch",
    fuelStatus: "55% fuel",
    parkingStopPlan: "Joplin Petro and West Memphis backup modeled",
    detentionState: "No detention",
    alertCount: 3,
    routeOptionsSummary: ["ELD sync issue could block compliance confidence"],
    timeline: [
      { id: "1", label: "ELD sync gap detected", timestamp: iso(-0.8), tone: "danger" },
      { id: "2", label: "Manual-entry verification requested", timestamp: iso(-0.3), tone: "warning" },
    ],
    weatherIncidents: [],
    detentionClockMinutes: 0,
    customerSlaRisk: "Low",
    downstreamImpact: "Compliance risk bigger than ETA risk",
    nudgesSent: ["Call driver", "Offer nearby repair"],
    lastMilePlan: "South trailer gate",
    routeChoices: demoLoads[3].routeChoices,
  },
  {
    id: "TR-021",
    driverId: "drv-williams",
    driverName: "Darius Williams",
    truckUnit: "T-21",
    loadId: "LD-4799",
    origin: "Lubbock, TX",
    destination: "Abilene, TX",
    liveHosHours: 6.5,
    liveEta: "Delivered",
    routeHealth: "healthy",
    fuelStatus: "74% fuel",
    parkingStopPlan: "Complete",
    detentionState: "None",
    alertCount: 2,
    routeOptionsSummary: ["Billing blocked by missing BOL/POD"],
    timeline: [
      { id: "1", label: "Delivered", timestamp: iso(-2), tone: "good" },
      { id: "2", label: "BOL/POD missing", timestamp: iso(-1.5), tone: "danger" },
    ],
    weatherIncidents: [],
    detentionClockMinutes: 0,
    customerSlaRisk: "None",
    downstreamImpact: "Billing hold blocks invoice cashflow",
    nudgesSent: ["Upload missing document"],
    lastMilePlan: "Completed",
    routeChoices: demoLoads[1].routeChoices,
  },
  {
    id: "TR-008",
    driverId: "drv-martinez",
    driverName: "Jose Martinez",
    truckUnit: "T-08",
    loadId: "LD-4821",
    origin: "Amarillo, TX",
    destination: "Oklahoma City, OK",
    liveHosHours: 5.2,
    liveEta: "Unknown",
    routeHealth: "risk",
    fuelStatus: "44% fuel",
    parkingStopPlan: "Hold pending recovery",
    detentionState: "Breakdown event",
    alertCount: 5,
    routeOptionsSummary: ["Repair ETA 3.5h", "Closest dry-van capable shops ranked"],
    timeline: [
      { id: "1", label: "Fault code P2459", timestamp: iso(-1.5), tone: "danger" },
      { id: "2", label: "Breakdown confirmed", timestamp: iso(-1.4), tone: "danger" },
      { id: "3", label: "Repair shortlist generated", timestamp: iso(-0.6), tone: "warning" },
    ],
    weatherIncidents: [],
    detentionClockMinutes: 0,
    customerSlaRisk: "High",
    downstreamImpact: "Trailer rescue and customer notice likely required",
    nudgesSent: ["Call shop", "Alert customer"],
    lastMilePlan: "N/A",
    routeChoices: demoLoads[4].routeChoices,
  },
  {
    id: "TR-011",
    driverId: "drv-davis",
    driverName: "Quinn Davis",
    truckUnit: "T-11",
    loadId: "LD-4818",
    origin: "Oklahoma City, OK",
    destination: "Kansas City, MO",
    liveHosHours: 8.9,
    liveEta: "Today 8:21 PM",
    routeHealth: "healthy",
    fuelStatus: "81% fuel",
    parkingStopPlan: "No stop required",
    detentionState: "None",
    alertCount: 0,
    routeOptionsSummary: ["Clean active trip"],
    timeline: [{ id: "1", label: "Departed on time", timestamp: iso(-1.8), tone: "good" }],
    weatherIncidents: [],
    detentionClockMinutes: 0,
    customerSlaRisk: "Low",
    downstreamImpact: "Healthy",
    nudgesSent: [],
    lastMilePlan: "Standard receiving lane",
    routeChoices: demoLoads[5].routeChoices,
  },
  {
    id: "TR-031",
    driverId: "drv-jackson",
    driverName: "Eli Jackson",
    truckUnit: "T-17",
    loadId: "LD-4857",
    origin: "San Antonio, TX",
    destination: "El Paso, TX",
    liveHosHours: 11,
    liveEta: "Queued for tomorrow dispatch",
    routeHealth: "healthy",
    fuelStatus: "72% fuel",
    parkingStopPlan: "Kerrville / Fort Stockton options modeled",
    detentionState: "None",
    alertCount: 1,
    routeOptionsSummary: ["Candidate route plan ready"],
    timeline: [{ id: "1", label: "Reset completed", timestamp: iso(-1), tone: "good" }],
    weatherIncidents: [],
    detentionClockMinutes: 0,
    customerSlaRisk: "None",
    downstreamImpact: "Potential backup if Dallas urgent load changes",
    nudgesSent: [],
    lastMilePlan: "Southbound truck gate",
    routeChoices: demoLoads[14].routeChoices,
  },
  {
    id: "TR-044",
    driverId: "drv-patel",
    driverName: "Sanjay Patel",
    truckUnit: "T-05",
    loadId: "LD-4812",
    origin: "Dallas, TX",
    destination: "Houston, TX",
    liveHosHours: 11.2,
    liveEta: "Waiting for assignment",
    routeHealth: "healthy",
    fuelStatus: "82% fuel",
    parkingStopPlan: "No stop required",
    detentionState: "Not started",
    alertCount: 1,
    routeOptionsSummary: ["Urgent assignment pending"],
    timeline: [{ id: "1", label: "Ready near pickup", timestamp: iso(-0.2), tone: "good" }],
    weatherIncidents: [],
    detentionClockMinutes: 0,
    customerSlaRisk: "High if not assigned in next 30 min",
    downstreamImpact: "None if executed now",
    nudgesSent: [],
    lastMilePlan: "Use east truck entrance at Houston final",
    routeChoices: demoLoads[0].routeChoices,
  },
  {
    id: "TR-045",
    driverId: "drv-reed",
    driverName: "Marcus Reed",
    truckUnit: "T-16",
    loadId: "LD-4860",
    origin: "Fort Worth, TX",
    destination: "Houston, TX",
    liveHosHours: 10.1,
    liveEta: "Pending release",
    routeHealth: "watch",
    fuelStatus: "68% fuel",
    parkingStopPlan: "No stop required",
    detentionState: "None",
    alertCount: 1,
    routeOptionsSummary: ["Downstream reefer opportunity protected"],
    timeline: [{ id: "1", label: "Held for market surge decision", timestamp: iso(-0.3), tone: "warning" }],
    weatherIncidents: [],
    detentionClockMinutes: 0,
    customerSlaRisk: "Low",
    downstreamImpact: "Could cannibalize tomorrow reefer surge if dispatched now",
    nudgesSent: [],
    lastMilePlan: "Cold-chain entrance B",
    routeChoices: demoLoads[17].routeChoices,
  },
  {
    id: "TR-046",
    driverId: "drv-johnson",
    driverName: "Tara Johnson",
    truckUnit: "T-18",
    loadId: "LD-4850",
    origin: "Houston, TX",
    destination: "San Antonio, TX",
    liveHosHours: 9.4,
    liveEta: "Awaiting trailer hookup",
    routeHealth: "healthy",
    fuelStatus: "63% fuel",
    parkingStopPlan: "No stop required",
    detentionState: "None",
    alertCount: 0,
    routeOptionsSummary: ["Trailer interchange plan ready"],
    timeline: [{ id: "1", label: "Power-only asset staged", timestamp: iso(-0.4), tone: "good" }],
    weatherIncidents: [],
    detentionClockMinutes: 0,
    customerSlaRisk: "Low",
    downstreamImpact: "Good rescue coverage",
    nudgesSent: [],
    lastMilePlan: "Trailer yard entrance",
    routeChoices: demoLoads[8].routeChoices,
  },
];

export const demoUrgentBand: OperationalAlert[] = [
  { id: "ua-1", scope: "dispatcher", type: "delay", severity: "critical", title: "T-14 (Ramirez) 17% fuel - 80 mi to partner stop", description: "Fuel and HOS pressure are compounding on the active reefer run.", related: [{ type: "driver", id: "drv-ramirez", label: "Ana Ramirez" }, { type: "trip", id: "TR-014", label: "TR-014" }], actionLabel: "Send stop", status: "new" },
  { id: "ua-2", scope: "dispatcher", type: "reroute", severity: "critical", title: "Ramirez has 1h 28m drive time left - relay needed", description: "Okafor can intercept at MM 261 and preserve the customer promise.", related: [{ type: "driver", id: "drv-okafor", label: "Adaeze Okafor" }], actionLabel: "Plan relay", status: "new" },
  { id: "ua-3", scope: "dispatcher", type: "delay", severity: "critical", title: "Load #4812 Dallas -> Houston remains unassigned", description: "Pickup window is closing. Patel is the highest-confidence match.", related: [{ type: "load", id: "LD-4812", label: "Load #4812" }], actionLabel: "Assign now", status: "new" },
  { id: "ua-4", scope: "dispatcher", type: "breakdown", severity: "critical", title: "Martinez breakdown - repair ETA 3.5h", description: "Fault code P2459 mapped to likely aftertreatment issue. Rescue options are ranked.", related: [{ type: "driver", id: "drv-martinez", label: "Jose Martinez" }], actionLabel: "Open repair plan", status: "new" },
];

export const demoTasks: DispatcherTask[] = [
  { id: "task-1", category: "urgent", title: "Assign T-05 (Patel) to load #4812 Dallas -> Houston", whyItMatters: "Best-match driver is already in Dallas with the right trailer and the pickup window closes this afternoon.", severity: "urgent", effortMinutes: 2, confidence: 0.96, tags: ["Urgent", "Load #4812", "Score 96/100"], related: [{ type: "driver", id: "drv-patel", label: "Sanjay Patel" }, { type: "load", id: "LD-4812", label: "Load #4812" }], primaryCta: "Assign Patel", primaryAction: "assign", operationalReasons: ["14 mi deadhead", "11.2h HOS remaining", "No tomorrow stranding"], status: "open" },
  { id: "task-2", category: "urgent", title: "Send fuel-stop coordinates to T-14 (Ramirez)", whyItMatters: "Fuel is below threshold and HOS is already critical, so the trip risk compounds with every minute.", severity: "urgent", effortMinutes: 1, confidence: 0.91, tags: ["Fuel critical", "17% tank"], related: [{ type: "driver", id: "drv-ramirez", label: "Ana Ramirez" }, { type: "trip", id: "TR-014", label: "TR-014" }], primaryCta: "Send stop", primaryAction: "message", operationalReasons: ["17% fuel", "80 mi to TA", "Reefer load"], status: "open" },
  { id: "task-3", category: "alerts", title: "Plan relay: T-09 (Okafor) swaps with Ramirez at MM 261", whyItMatters: "Relay prevents an HOS miss without compromising tomorrow's plan.", severity: "attention", effortMinutes: 5, confidence: 0.89, tags: ["HOS critical", "Relay"], related: [{ type: "driver", id: "drv-okafor", label: "Adaeze Okafor" }, { type: "driver", id: "drv-ramirez", label: "Ana Ramirez" }], primaryCta: "Plan relay", primaryAction: "review", operationalReasons: ["18 mi from intercept", "9.7h HOS", "No tomorrow conflict"], status: "open" },
  { id: "task-4", category: "ai", title: "Review & send customer notice for Nguyen delay", whyItMatters: "The customer SLA is at risk and proactive communication lowers escalation probability.", severity: "attention", effortMinutes: 2, confidence: 0.84, tags: ["Delay", "Customer SLA"], related: [{ type: "trip", id: "TR-003", label: "TR-003" }, { type: "customer", id: "cust-midwest-retail", label: "Midwest Retail Co." }], primaryCta: "Review draft", primaryAction: "open_trip", operationalReasons: ["Weather + traffic delay", "Draft already prepared"], status: "open" },
  { id: "task-5", category: "alerts", title: "Resolve T-12 (Chen) ELD sync gap", whyItMatters: "47 minutes without sync introduces compliance risk and can invalidate route confidence.", severity: "attention", effortMinutes: 3, confidence: 0.88, tags: ["Compliance", "ELD"], related: [{ type: "driver", id: "drv-chen", label: "Leo Chen" }], primaryCta: "Call T-12", primaryAction: "open_driver", operationalReasons: ["ELD-SYNC-47", "Manual entry check"], status: "open" },
  { id: "task-6", category: "urgent", title: "Upload missing BOL/POD for Williams load #4799", whyItMatters: "Billing stays blocked until both delivery documents reconcile.", severity: "attention", effortMinutes: 1, confidence: 0.82, tags: ["Billing blocked"], related: [{ type: "driver", id: "drv-williams", label: "Darius Williams" }, { type: "load", id: "LD-4799", label: "Load #4799" }], primaryCta: "Nudge Williams", primaryAction: "open_docs", operationalReasons: ["Delivered 2h ago", "Invoice cannot auto-reconcile"], status: "open" },
  { id: "task-7", category: "ai", title: "Review Martinez breakdown repair shortlist", whyItMatters: "Repair ETA and rescue capacity determine whether the current load can still be salvaged.", severity: "urgent", effortMinutes: 4, confidence: 0.9, tags: ["Breakdown", "Repair ETA"], related: [{ type: "driver", id: "drv-martinez", label: "Jose Martinez" }], primaryCta: "Open repair plan", primaryAction: "open_driver", operationalReasons: ["P2459 code", "3.5h ETA", "Closest shops ranked"], status: "open" },
  { id: "task-8", category: "ai", title: "Protect Reed for tomorrow's Dallas reefer surge", whyItMatters: "Using Reed on the wrong Houston move burns a higher-margin opportunity already signaled by the market alert.", severity: "attention", effortMinutes: 2, confidence: 0.79, tags: ["Tomorrow impact", "Market surge"], related: [{ type: "driver", id: "drv-reed", label: "Marcus Reed" }], primaryCta: "Review capacity", primaryAction: "open_driver", operationalReasons: ["Higher-margin reefer tomorrow", "Current load is attractive but not optimal"], status: "open" },
];

export const demoAlerts: OperationalAlert[] = [
  ...demoUrgentBand,
  { id: "al-5", scope: "dispatcher", type: "weather", severity: "warning", title: "Nguyen delayed 1h 20m near Salina, KS", description: "Traffic and weather are affecting I-70. Draft customer notice is ready.", related: [{ type: "trip", id: "TR-003", label: "TR-003" }], actionLabel: "Notify customer", status: "new" },
  { id: "al-6", scope: "dispatcher", type: "eld_sync", severity: "warning", title: "T-12 ELD sync error", description: "Last HOS sync was 47 minutes ago. Manual-entry verification recommended.", related: [{ type: "driver", id: "drv-chen", label: "Leo Chen" }], actionLabel: "Call driver", status: "new" },
  { id: "al-7", scope: "dispatcher", type: "doc_missing", severity: "warning", title: "Williams billing blocked by missing BOL/POD", description: "Delivered load cannot invoice until both docs land and reconcile.", related: [{ type: "load", id: "LD-4799", label: "Load #4799" }], actionLabel: "Open docs", status: "new" },
  { id: "al-8", scope: "dispatcher", type: "detention", severity: "critical", title: "Detention exceeded 4h at Lone Star Grocery", description: "Invoice draft already exists. AI alternatives are ready for relay, reschedule, and customer notice.", related: [{ type: "load", id: "LD-4861", label: "Load #4861" }], actionLabel: "Review alternatives", status: "new" },
  { id: "al-9", scope: "dispatcher", type: "law_change", severity: "warning", title: "Hazmat route registry update affects screened lane", description: "FMCSA published NHMRR revisions covering reports through March 31, 2025; screened route review is required on affected hazardous lanes.", related: [{ type: "load", id: "LD-4852", label: "Load #4852" }], actionLabel: "Open impact", status: "new", effectiveDate: "2025-10-24", sourceUrl: "https://www.fmcsa.dot.gov/regulations/federal-register-documents/2025-22192" },
  { id: "al-10", scope: "dispatcher", type: "market_surge", severity: "info", title: "Dallas outbound reefer surge detected", description: "Rates are elevated on tomorrow morning outbound reefer loads; preserve premium reefer assets where possible.", related: [{ type: "driver", id: "drv-reed", label: "Marcus Reed" }], actionLabel: "Review market", status: "new" },
  { id: "al-11", scope: "driver", type: "idle_stop", severity: "warning", title: "Driver nudge queued for extended stop", description: "Idle-stop logic flagged Chen after 47 minutes without sync or movement.", related: [{ type: "driver", id: "drv-chen", label: "Leo Chen" }], actionLabel: "Send nudge", status: "new" },
  { id: "al-12", scope: "driver", type: "road_closure", severity: "warning", title: "Route advisory reminder on screened Arizona corridors", description: "ADOT Table 4 rules require day-of checks for closures and restrictions via official traveler systems.", related: [{ type: "load", id: "LD-4856", label: "Load #4856" }], actionLabel: "Review route", status: "new", effectiveDate: "2022-07-08", sourceUrl: "https://azdot.gov/sites/default/files/media/2022/07/OversizeandOverweightEnvelopeandSpecialPermitRulesEffective07082022.pdf" },
];

export const demoDetentions: DetentionCase[] = [
  { id: "det-01", loadId: "LD-4861", tripId: "TR-061", facility: "Lone Star Grocery", minutes: 262, clockState: "4h 22m at dock", invoiceDraftReady: true, aiAlternatives: ["Relay to Johnson after dock release", "Partial reschedule with customer notice", "Swap tomorrow load order for Reed"], tomorrowImpact: "Pushes one Dallas reefer opportunity to overflow board", marginImpact: "-$388 live margin hit" },
  { id: "det-02", loadId: "LD-4862", tripId: "TR-062", facility: "DFW Retail Crossdock", minutes: 146, clockState: "2h 26m at dock", invoiceDraftReady: true, aiAlternatives: ["Draft invoice now", "Keep current route", "Prepare customer exception note"], tomorrowImpact: "Minimal", marginImpact: "-$146 live margin hit" },
  { id: "det-03", loadId: "LD-4863", tripId: "TR-063", facility: "Memphis South DC", minutes: 88, clockState: "1h 28m", invoiceDraftReady: false, aiAlternatives: ["Monitor", "Prep invoice shell"], tomorrowImpact: "Low", marginImpact: "-$74 risk" },
];

export const demoDocumentCases: DocumentBillingCase[] = [
  { id: "doc-01", loadId: "LD-4799", driverName: "Darius Williams", customer: "Basin Steel", missingDocs: ["BOL", "POD"], reconciliationStatus: "blocked", invoiceMatchConfidence: 0.38, aiExplanation: "Delivered timestamp and lumper note exist, but required BOL/POD files are missing so invoice matching is blocked." },
  { id: "doc-02", loadId: "LD-4855", driverName: "Marcus Reed", customer: "Gulf Fresh", missingDocs: ["Temp trace"], reconciliationStatus: "review", invoiceMatchConfidence: 0.74, aiExplanation: "Invoice lines reconcile, but customer-specific cold-chain proof is still missing." },
  { id: "doc-03", loadId: "LD-4812", driverName: "Unassigned", customer: "Lone Star Retail", missingDocs: ["Rate confirmation"], reconciliationStatus: "review", invoiceMatchConfidence: 0.61, aiExplanation: "Commercial terms exist, but rate confirmation packet should be attached before dispatch release." },
  { id: "doc-04", loadId: "LD-4850", driverName: "Tara Johnson", customer: "South Gulf Intermodal", missingDocs: ["Trailer interchange"], reconciliationStatus: "review", invoiceMatchConfidence: 0.69, aiExplanation: "Power-only move needs trailer interchange proof for billing defense." },
  { id: "doc-05", loadId: "LD-4851", driverName: "Keisha Brown", customer: "Ark Valley Steel", missingDocs: ["POD"], reconciliationStatus: "review", invoiceMatchConfidence: 0.71, aiExplanation: "All but final delivery proof present." },
  { id: "doc-06", loadId: "LD-4852", driverName: "Quinn Davis", customer: "Front Range Retail", missingDocs: ["Permit note"], reconciliationStatus: "review", invoiceMatchConfidence: 0.68, aiExplanation: "Permit-sensitive route should carry reviewed route packet in the job file." },
  { id: "doc-07", loadId: "LD-4853", driverName: "Thu Nguyen", customer: "Heartland Distribution", missingDocs: [], reconciliationStatus: "approved", invoiceMatchConfidence: 0.93, aiExplanation: "Documents match cleanly." },
  { id: "doc-08", loadId: "LD-4854", driverName: "Thu Nguyen", customer: "River South Retail", missingDocs: ["Seal photo"], reconciliationStatus: "review", invoiceMatchConfidence: 0.77, aiExplanation: "Seal verification is referenced but not attached." },
  { id: "doc-09", loadId: "LD-4856", driverName: "Eli Jackson", customer: "Desert Electronics", missingDocs: ["Screened route packet"], reconciliationStatus: "review", invoiceMatchConfidence: 0.66, aiExplanation: "Route-sensitive load should archive the route review packet." },
  { id: "doc-10", loadId: "LD-4857", driverName: "Eli Jackson", customer: "Border Freight", missingDocs: [], reconciliationStatus: "approved", invoiceMatchConfidence: 0.92, aiExplanation: "Baseline docs already present." },
  { id: "doc-11", loadId: "LD-4858", driverName: "Quinn Davis", customer: "Heartland Wholesale", missingDocs: [], reconciliationStatus: "approved", invoiceMatchConfidence: 0.91, aiExplanation: "No blockers." },
  { id: "doc-12", loadId: "LD-4859", driverName: "Sanjay Patel", customer: "Eastline Goods", missingDocs: ["Fuel receipt"], reconciliationStatus: "review", invoiceMatchConfidence: 0.83, aiExplanation: "Fuel receipt missing for accessorial reimbursement." },
  { id: "doc-13", loadId: "LD-4860", driverName: "Marcus Reed", customer: "Metro Cold Chain", missingDocs: ["Temp trace", "POD"], reconciliationStatus: "blocked", invoiceMatchConfidence: 0.41, aiExplanation: "Cold-chain proof and POD are both missing, so auto-reconciliation is blocked." },
  { id: "doc-14", loadId: "LD-4861", driverName: "Pending", customer: "Lone Star Grocery", missingDocs: ["Detention backup"], reconciliationStatus: "review", invoiceMatchConfidence: 0.57, aiExplanation: "Invoice draft exists, but detention backup should be attached before send." },
  { id: "doc-15", loadId: "LD-4862", driverName: "Pending", customer: "DFW Retail Crossdock", missingDocs: ["Dock time proof"], reconciliationStatus: "review", invoiceMatchConfidence: 0.62, aiExplanation: "Dock-in/dock-out proof is referenced but not uploaded." },
];

export const demoLastMileInsights: LastMileInsight[] = [
  { facilityId: "fac-houston", facilityName: "Houston South DC", recommendedEntrance: "Use the east-side truck gate off Supply Row", parkingArea: "Stage in the striped south lot before backing", avoidNotes: ["Do not use the office entrance on Harbor Way", "Cars block the north apron at shift change"], confidence: 0.92, reasoning: "Truck entrance lanes and trailer staging markings are visible on the east approach. The office driveway is too tight for full-size trailers.", imageRefs: ["/facilities/houston-terminal.svg"] },
  { facilityId: "fac-dallas", facilityName: "Dallas Crossdock 9", recommendedEntrance: "Enter via Gate B on Industrial Ave", parkingArea: "Overflow staging on the west fence line", avoidNotes: ["Avoid Gate A during noon vendor traffic"], confidence: 0.88, reasoning: "Gate B aligns with the marked truck queue and widest turning radius.", imageRefs: ["/facilities/dallas-crossdock.svg"] },
  { facilityId: "fac-memphis", facilityName: "Memphis South Retail", recommendedEntrance: "Use the south truck apron on Shelby Industrial", parkingArea: "Hold on the painted dock-call line", avoidNotes: ["Avoid the customer office circle"], confidence: 0.86, reasoning: "Truck lane paint and dock-call signage align with the south apron.", imageRefs: ["/facilities/memphis-retail.svg"] },
  { facilityId: "fac-phoenix", facilityName: "Phoenix Tech Distribution", recommendedEntrance: "Enter from the 51st Ave freight gate", parkingArea: "Stage in lot C until dock assignment arrives", avoidNotes: ["Avoid visitor gate - height bar present"], confidence: 0.89, reasoning: "Freight gate geometry and lot C trailer markings support the truck move.", imageRefs: ["/facilities/phoenix-tech.svg"] },
  { facilityId: "fac-denver", facilityName: "Front Range Grocery", recommendedEntrance: "Take the truck-only ramp from Warehouse Loop", parkingArea: "Cold-chain staging pad 2", avoidNotes: ["Avoid south retail lot entrance"], confidence: 0.84, reasoning: "Trailer staging pads and reefer hookups are visible on the warehouse-loop side.", imageRefs: ["/facilities/denver-grocery.svg"] },
];

export const demoRepairShops: RepairShopOption[] = Array.from({ length: 25 }, (_, index) => ({
  id: `shop-${index + 1}`,
  name: ["Petro Service Center", "FleetPro Diesel", "RoadReady Truck Repair", "BlueLine Heavy Duty", "Interstate Fleet Service"][index % 5] + ` ${index + 1}`,
  city: ["Amarillo, TX", "Abilene, TX", "Joplin, MO", "Dallas, TX", "Houston, TX"][index % 5],
  distanceMiles: 6 + index * 3,
  capability: ["Aftertreatment", "ELD diagnostics", "PM + tires", "Trailer repair", "Reefer service"][index % 5],
}));

export const demoSafetyCases: SafetyCase[] = [
  { id: "safe-1", title: "Chen ELD sync gap follow-up", status: "Open", owner: "Jessica", dueText: "Due now" },
  { id: "safe-2", title: "Brown PM overdue", status: "Needs scheduling", owner: "Maintenance", dueText: "Today" },
  { id: "safe-3", title: "2 HOS warnings this week on Ramirez", status: "Coach", owner: "Safety", dueText: "Tomorrow" },
  { id: "safe-4", title: "Quarterly CSA review for Martinez", status: "Open", owner: "Safety", dueText: "This week" },
];

export const demoCostTrend: CostTrendPoint[] = [
  { label: "Mon", revenue: 39200, margin: 10820, costPerMile: 1.76 },
  { label: "Tue", revenue: 40450, margin: 11260, costPerMile: 1.79 },
  { label: "Wed", revenue: 41810, margin: 12030, costPerMile: 1.82 },
  { label: "Thu", revenue: 40190, margin: 10940, costPerMile: 1.8 },
  { label: "Fri", revenue: 43780, margin: 12810, costPerMile: 1.84 },
  { label: "Sat", revenue: 38220, margin: 10130, costPerMile: 1.78 },
  { label: "Sun", revenue: 41060, margin: 11820, costPerMile: 1.84 },
];

export const demoKpis: DashboardKpi[] = [
  { key: "trucks_on_road", label: "Trucks on road", value: "18", rawValue: 18, change: "of 24 total", tone: "neutral" },
  { key: "loads_today", label: "Loads today", value: "31", rawValue: 31, change: "+4 vs yesterday", tone: "positive" },
  { key: "on_time_rate", label: "On-time rate", value: "87%", rawValue: 87, change: "-3% this week", tone: "warning" },
  { key: "revenue_today", label: "Revenue today", value: "$41K", rawValue: 41060, change: "+$4K vs avg", tone: "positive" },
  { key: "cost_per_mile", label: "Cost per mile", value: "$1.84", rawValue: 1.84, change: "+$0.06", tone: "warning" },
  { key: "open_loads", label: "Open loads", value: "3", rawValue: 3, change: "1 urgent", tone: "critical" },
];

export function createDemoDispatcherSnapshot(): DispatcherSnapshot {
  return {
    mode: "demo",
    modeNotice: "Running seeded dispatcher OS data because the expanded InsForge operations schema has not been migrated yet. Assignment, task state, and drill-down flows still persist locally in demo mode.",
    greeting: "Good morning, Jessica",
    fleetHeadline: "18 trucks active • 5 loads en route • 2 customer risks • 1 billing blocker",
    lastRefresh: now.toISOString(),
    kpis: demoKpis,
    urgentBand: demoUrgentBand,
    tasks: demoTasks,
    drivers: demoDrivers,
    vehicles: demoVehicles,
    trips: demoTrips,
    loads: demoLoads,
    alerts: demoAlerts,
    detentions: demoDetentions,
    lastMileInsights: demoLastMileInsights,
    documentCases: demoDocumentCases,
    safetyCases: demoSafetyCases,
    repairShops: demoRepairShops,
    costTrend: demoCostTrend,
  };
}
