import type {
  NormalizedRouteRestriction,
  RouteRestrictionBoundingBox,
  RoutingSourceRegistryEntry,
} from "./types";

const LAST_CHECKED_AT = "2026-04-19";

const federalSources: RoutingSourceRegistryEntry[] = [
  {
    id: "federal-staa-appendix-a",
    jurisdiction_level: "federal",
    agency: "Federal Highway Administration",
    title: "National Network for Large Trucks and STAA Access Routes",
    source_url: "https://www.law.cornell.edu/cfr/text/23/appendix-A_to_part_658",
    source_type: "statute",
    effective_date: "2026-04-19",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "federal-baseline",
    notes: "Mainland truck-network baseline and legal reference for STAA access.",
  },
  {
    id: "federal-fhwa-nhs",
    jurisdiction_level: "federal",
    agency: "Federal Highway Administration",
    title: "National Highway System Maps and Shapefiles",
    source_url: "https://www.fhwa.dot.gov/planning/national_highway_system/nhs_maps/",
    source_type: "dataset",
    publish_date: "2025-08-08",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "federal-baseline",
    notes: "Federal backbone screening layer for long-haul truck routing.",
  },
  {
    id: "federal-fmcsa-hazmat",
    jurisdiction_level: "federal",
    agency: "Federal Motor Carrier Safety Administration",
    title: "National Hazardous Materials Route Registry by State",
    source_url: "https://www.fmcsa.dot.gov/regulations/hazardous-materials/national-hazardous-materials-route-registry-state",
    source_type: "registry",
    publish_date: "2024-07-01",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "federal-baseline",
    notes: "Primary registry for hazmat-restricted routes and notices.",
  },
  {
    id: "federal-fhwa-nbi",
    jurisdiction_level: "federal",
    agency: "Federal Highway Administration",
    title: "National Bridge Inventory",
    source_url: "https://www.fhwa.dot.gov/bridge/nbi.cfm",
    source_type: "dataset",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "federal-baseline",
    notes: "Bridge screening reference for posted structures and restriction metadata.",
  },
  {
    id: "federal-fhwa-nti",
    jurisdiction_level: "federal",
    agency: "Federal Highway Administration",
    title: "National Tunnel Inventory",
    source_url: "https://www.fhwa.dot.gov/bridge/inspection/tunnel/inventory/preliminary.cfm",
    source_type: "dataset",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "federal-baseline",
    notes: "Tunnel screening reference for clearance and hazmat restrictions.",
  },
];

const contiguousStateSources: Array<[string, string, string, string]> = [
  ["AL", "Alabama", "Alabama Department of Transportation", "https://www.dot.state.al.us"],
  ["AZ", "Arizona", "Arizona Department of Transportation", "https://www.azdot.gov"],
  ["AR", "Arkansas", "Arkansas Department of Transportation", "https://www.ardot.gov"],
  ["CA", "California", "California Department of Transportation", "https://dot.ca.gov"],
  ["CO", "Colorado", "Colorado Department of Transportation", "https://www.codot.gov"],
  ["CT", "Connecticut", "Connecticut Department of Transportation", "https://portal.ct.gov/DOT"],
  ["DE", "Delaware", "Delaware Department of Transportation", "https://deldot.gov"],
  ["FL", "Florida", "Florida Department of Transportation", "https://www.fdot.gov"],
  ["GA", "Georgia", "Georgia Department of Transportation", "https://www.dot.ga.gov"],
  ["ID", "Idaho", "Idaho Transportation Department", "https://itd.idaho.gov"],
  ["IL", "Illinois", "Illinois Department of Transportation", "https://idot.illinois.gov"],
  ["IN", "Indiana", "Indiana Department of Transportation", "https://www.in.gov/indot"],
  ["IA", "Iowa", "Iowa Department of Transportation", "https://iowadot.gov"],
  ["KS", "Kansas", "Kansas Department of Transportation", "https://www.ksdot.gov"],
  ["KY", "Kentucky", "Kentucky Transportation Cabinet", "https://transportation.ky.gov"],
  ["LA", "Louisiana", "Louisiana Department of Transportation and Development", "https://wwwsp.dotd.la.gov"],
  ["ME", "Maine", "Maine Department of Transportation", "https://www.maine.gov/mdot"],
  ["MD", "Maryland", "Maryland Department of Transportation", "https://www.mdot.maryland.gov"],
  ["MA", "Massachusetts", "Massachusetts Department of Transportation", "https://www.mass.gov/orgs/massachusetts-department-of-transportation"],
  ["MI", "Michigan", "Michigan Department of Transportation", "https://www.michigan.gov/mdot"],
  ["MN", "Minnesota", "Minnesota Department of Transportation", "https://www.dot.state.mn.us"],
  ["MS", "Mississippi", "Mississippi Department of Transportation", "https://mdot.ms.gov"],
  ["MO", "Missouri", "Missouri Department of Transportation", "https://www.modot.org"],
  ["MT", "Montana", "Montana Department of Transportation", "https://www.mdt.mt.gov"],
  ["NE", "Nebraska", "Nebraska Department of Transportation", "https://dot.nebraska.gov"],
  ["NV", "Nevada", "Nevada Department of Transportation", "https://www.nevadadot.com"],
  ["NH", "New Hampshire", "New Hampshire Department of Transportation", "https://www.nh.gov/dot"],
  ["NJ", "New Jersey", "New Jersey Department of Transportation", "https://www.state.nj.us/transportation"],
  ["NM", "New Mexico", "New Mexico Department of Transportation", "https://dot.state.nm.us"],
  ["NY", "New York", "New York State Department of Transportation", "https://www.dot.ny.gov"],
  ["NC", "North Carolina", "North Carolina Department of Transportation", "https://www.ncdot.gov"],
  ["ND", "North Dakota", "North Dakota Department of Transportation", "https://www.dot.nd.gov"],
  ["OH", "Ohio", "Ohio Department of Transportation", "https://www.transportation.ohio.gov"],
  ["OK", "Oklahoma", "Oklahoma Department of Transportation", "https://oklahoma.gov/odot"],
  ["OR", "Oregon", "Oregon Department of Transportation", "https://www.oregon.gov/odot"],
  ["PA", "Pennsylvania", "Pennsylvania Department of Transportation", "https://www.penndot.pa.gov"],
  ["RI", "Rhode Island", "Rhode Island Department of Transportation", "https://www.dot.ri.gov"],
  ["SC", "South Carolina", "South Carolina Department of Transportation", "https://www.scdot.org"],
  ["SD", "South Dakota", "South Dakota Department of Transportation", "https://dot.sd.gov"],
  ["TN", "Tennessee", "Tennessee Department of Transportation", "https://www.tn.gov/tdot"],
  ["TX", "Texas", "Texas Department of Transportation", "https://www.txdot.gov"],
  ["UT", "Utah", "Utah Department of Transportation", "https://www.udot.utah.gov"],
  ["VT", "Vermont", "Vermont Agency of Transportation", "https://vtrans.vermont.gov"],
  ["VA", "Virginia", "Virginia Department of Transportation", "https://www.vdot.virginia.gov"],
  ["WA", "Washington", "Washington State Department of Transportation", "https://wsdot.wa.gov"],
  ["WV", "West Virginia", "West Virginia Department of Transportation", "https://transportation.wv.gov"],
  ["WI", "Wisconsin", "Wisconsin Department of Transportation", "https://wisconsindot.gov"],
  ["WY", "Wyoming", "Wyoming Department of Transportation", "https://www.dot.state.wy.us"],
];

// ── Additional state-specific sources for enriched overlay data ──

const southwestOverlaySources: RoutingSourceRegistryEntry[] = [
  {
    id: "state-co-permit-rules",
    jurisdiction_level: "state",
    state: "CO",
    agency: "Colorado Department of Transportation",
    title: "Colorado Permit Rules",
    source_url: "https://coopr.codot.gov/PermitRules.pdf",
    source_type: "pdf",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "pdf-extraction",
    notes: "Official Colorado extra-legal and oversize permit rules, including Eisenhower-Johnson Memorial Tunnels restrictions.",
  },
  {
    id: "state-co-truck-parking-guide",
    jurisdiction_level: "state",
    state: "CO",
    agency: "Colorado Department of Transportation",
    title: "Colorado Truck Parking Guide",
    source_url: "https://www.codot.gov/safety/traffic-safety/assets/documents/truck_parking_guide.pdf",
    source_type: "pdf",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "pdf-extraction",
    notes: "Official CDOT I-70 corridor truck restriction and hazardous materials bypass guidance.",
  },
  {
    id: "state-ca-special-route-restrictions",
    jurisdiction_level: "state",
    state: "CA",
    agency: "California Department of Transportation",
    title: "California Special Route Restrictions",
    source_url: "https://dot.ca.gov/programs/traffic-operations/legal-truck-access/restrict-list",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "Official Caltrans restriction list used to normalize weight and hazmat-sensitive route segments.",
  },
  {
    id: "state-ca-route-110",
    jurisdiction_level: "state",
    state: "CA",
    agency: "California Department of Transportation",
    title: "Route 110 Special Route Restriction",
    source_url: "https://dot.ca.gov/programs/traffic-operations/legal-truck-access/restrict-route-110",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "Official Route 110 history and commercial vehicle gross-weight restriction details.",
  },
  {
    id: "state-az-table-4",
    jurisdiction_level: "state",
    state: "AZ",
    agency: "Arizona Department of Transportation",
    title: "Table 4 Permanent Highway Restrictions, Requirements, Conditions, and Allowances",
    source_url: "https://azdot.gov/sites/default/files/2023-12/table-4-road-restriction-info.pdf",
    source_type: "pdf",
    publish_date: "2025-07-10",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "pdf-extraction",
    notes: "Official ADOT corridor restriction table for oversize, escort, and bridge-sensitive segments.",
  },
  {
    id: "state-az-bridge-weight-restrictions",
    jurisdiction_level: "state",
    state: "AZ",
    agency: "Arizona Department of Transportation",
    title: "Weight Restrictions for State Highway Bridges",
    source_url: "https://azdot.gov/sites/default/files/media/2022/02/weight-restrictions-for-state-highway-bridges.pdf",
    source_type: "pdf",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "pdf-extraction",
    notes: "Official ADOT bridge restriction reference for named structures such as Apache Bridge.",
  },
  {
    id: "state-md-mdta-tunnel-restrictions",
    jurisdiction_level: "state",
    state: "MD",
    agency: "Maryland Transportation Authority",
    title: "Tunnel Restrictions and Vehicle Permits",
    source_url: "https://mdta.maryland.gov/TunnelRestrictionsAndVehiclePermits",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "Official MDTA tunnel hazmat, height, width, and permit restrictions for Baltimore toll facilities.",
  },
  {
    id: "state-md-mdta-tunnel-advisory",
    jurisdiction_level: "state",
    state: "MD",
    agency: "Maryland Transportation Authority",
    title: "I-95 and I-895 Tunnel Restrictions Advisory",
    source_url: "https://www.mdta.maryland.gov/index.php/blog-category/mdta-traffic-advisories/reminder-i-95-i-895-tunnel-restrictions",
    source_type: "map",
    publish_date: "2024-07-25",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "Recent MDTA advisory confirming Fort McHenry and Baltimore Harbor tunnel height and width restrictions.",
  },
  {
    id: "state-nm-ports-of-entry",
    jurisdiction_level: "state",
    state: "NM",
    agency: "New Mexico Department of Transportation",
    title: "Ports of Entry",
    source_url: "https://www.dot.nm.gov/planning-research-multimodal-and-safety/modal/ports-of-entry/",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "Official NMDOT port-of-entry locations and operating hours used for corridor advisories.",
  },
];

const expandedOverlaySources: RoutingSourceRegistryEntry[] = [
  {
    id: "state-al-mobile-tunnel-restrictions",
    jurisdiction_level: "state",
    state: "AL",
    agency: "Alabama Department of Transportation",
    title: "Mobile Tunnel Restriction and Detour Guidance",
    source_url: "https://www.dot.state.al.us/business/pdf/DetourLetter..pdf",
    source_type: "pdf",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "ALDOT Mobile tunnel detour routing for oversized and restricted moves.",
  },
  {
    id: "state-ct-parkway-restrictions",
    jurisdiction_level: "state",
    state: "CT",
    agency: "Connecticut Department of Transportation",
    title: "Connecticut Parkway Restrictions",
    source_url: "https://portal.ct.gov/DOT/Commissions/STC/Connecticut-Parkways",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "Official commercial-vehicle, size, and exemption rules for Merritt, Wilbur Cross, and Milford parkways.",
  },
  {
    id: "state-ma-dcr-road-restrictions",
    jurisdiction_level: "state",
    state: "MA",
    agency: "Massachusetts Department of Conservation and Recreation",
    title: "Storrow Drive and River Road Cars-Only Restrictions",
    source_url: "https://www.mass.gov/news/dcr-pilots-new-cars-only-sign-to-prevent-storrowing-ahead-of-boston-area-move-in-day",
    source_type: "map",
    publish_date: "2023-08-28",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "Official DCR/MassDOT low-clearance and cars-only restrictions for Storrow Drive, Soldiers Field Road, and Memorial Drive.",
  },
  {
    id: "state-vt-smugglers-notch",
    jurisdiction_level: "state",
    state: "VT",
    agency: "Vermont General Assembly",
    title: "Smugglers' Notch Vehicle Operation Prohibited",
    source_url: "https://legislature.vermont.gov/statutes/section/23/013/01006b",
    source_type: "statute",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "Official Vermont statutory prohibition for long commercial vehicles on VT 108 through Smugglers' Notch.",
  },
  {
    id: "state-id-ports-of-entry",
    jurisdiction_level: "state",
    state: "ID",
    agency: "Idaho Transportation Department",
    title: "Idaho Ports of Entry",
    source_url: "https://itd.idaho.gov/contact/huetter-port-of-entry/",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "Official Idaho POE location and commercial screening contacts.",
  },
  {
    id: "state-ut-ports-of-entry",
    jurisdiction_level: "state",
    state: "UT",
    agency: "Utah Department of Transportation",
    title: "Utah Motor Carrier Ports of Entry",
    source_url: "https://www.udot.utah.gov/connect/business/motor-carriers/motor-carrier-contacts/motor-carrier-ports-of-entry/",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "Official UDOT ports-of-entry locations and motor carrier guidance.",
  },
  {
    id: "state-or-truck-scales",
    jurisdiction_level: "state",
    state: "OR",
    agency: "Oregon Department of Transportation",
    title: "Oregon Motor Carrier Enforcement Truck Scales",
    source_url: "https://www.oregon.gov/odot/MCT/Documents/MotorCarrierEnforcementTruckScales.pdf",
    source_type: "pdf",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "pdf-extraction",
    notes: "Official ODOT truck scale and port-of-entry map for freight screening corridors.",
  },
  {
    id: "state-nv-prohibited-routes",
    jurisdiction_level: "state",
    state: "NV",
    agency: "Nevada Department of Transportation",
    title: "Nevada Over-Dimensional Vehicle Prohibited Routes",
    source_url: "https://www.dot.nv.gov/home/showpublisheddocument/7136/636268039903270000",
    source_type: "pdf",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "pdf-extraction",
    notes: "NDOT letter of instruction identifying prohibited routes for over-width and over-length vehicles.",
  },
  {
    id: "state-ne-weigh-stations",
    jurisdiction_level: "state",
    state: "NE",
    agency: "Nebraska Department of Transportation",
    title: "Nebraska I-80 Weigh Station Scale Sites",
    source_url: "https://dot.nebraska.gov/media/0jtj5yd1/rfp-r410-24-general-contractor.pdf",
    source_type: "pdf",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "pdf-extraction",
    notes: "Official NDOT facility document listing I-80 weigh station locations near Greenwood and Nebraska City.",
  },
  {
    id: "state-ri-bridge-permits",
    jurisdiction_level: "state",
    state: "RI",
    agency: "Rhode Island Turnpike and Bridge Authority",
    title: "Newport Pell Bridge Overweight and Overwide Permits",
    source_url: "https://www.ritba.org/overweight-overwide/",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "Official RITBA permitting requirements for oversize and overweight crossings of the Newport Pell Bridge.",
  },
  {
    id: "state-wy-ports-of-entry",
    jurisdiction_level: "state",
    state: "WY",
    agency: "Wyoming Department of Transportation",
    title: "Wyoming Ports of Entry",
    source_url: "https://dot.state.wy.us/home/trucking_commercial_vehicles.html",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "Official WYDOT commercial carrier page summarizing ports of entry, including I-80 at Evanston.",
  },
  {
    id: "state-tx-bridge-restrictions",
    jurisdiction_level: "state",
    state: "TX",
    agency: "Texas Department of Transportation",
    title: "Texas Bridge Restrictions and OS/OW Routing",
    source_url: "https://www.txdot.gov/business/motor-carriers/oversize-overweight-permits.html",
    source_type: "dataset",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "TxDOT bridge posting data and OS/OW permit corridor restrictions.",
  },
  {
    id: "state-tx-ports-of-entry",
    jurisdiction_level: "state",
    state: "TX",
    agency: "Texas Department of Transportation",
    title: "Texas Ports of Entry and Border Commercial Crossings",
    source_url: "https://www.txdot.gov/business/motor-carriers.html",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "Official TxDOT commercial vehicle border crossing and port-of-entry locations.",
  },
  {
    id: "state-pa-bridge-restrictions",
    jurisdiction_level: "state",
    state: "PA",
    agency: "Pennsylvania Department of Transportation",
    title: "Pennsylvania Turnpike and Bridge Restrictions",
    source_url: "https://www.penndot.pa.gov/ProjectAndPrograms/RoadDesignEnvironment/Pages/Hauling-Permits.aspx",
    source_type: "dataset",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "PennDOT bridge clearance data and turnpike restriction references.",
  },
  {
    id: "state-ny-parkway-restrictions",
    jurisdiction_level: "state",
    state: "NY",
    agency: "New York State Department of Transportation",
    title: "New York Parkway Commercial Vehicle Restrictions",
    source_url: "https://www.dot.ny.gov/divisions/operating/oom/transportation-systems/large-vehicle-restriction",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "NYSDOT official parkway truck ban and large vehicle restriction reference.",
  },
  {
    id: "state-ny-tunnel-restrictions",
    jurisdiction_level: "state",
    state: "NY",
    agency: "Port Authority of NY/NJ",
    title: "NY/NJ Tunnel and Bridge Hazmat Restrictions",
    source_url: "https://www.panynj.gov/bridges-tunnels/en/traffic---travel-information/commercial-vehicles.html",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "Port Authority tunnel and bridge hazmat routing restrictions for Holland, Lincoln, Bayonne, GWB.",
  },
  {
    id: "state-nj-restrictions",
    jurisdiction_level: "state",
    state: "NJ",
    agency: "New Jersey Department of Transportation",
    title: "New Jersey Truck Restrictions and Pulaski Skyway",
    source_url: "https://www.state.nj.us/transportation/freight/trucking/",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "NJDOT commercial vehicle access restrictions including Pulaski Skyway truck ban.",
  },
  {
    id: "state-oh-turnpike-restrictions",
    jurisdiction_level: "state",
    state: "OH",
    agency: "Ohio Department of Transportation",
    title: "Ohio Turnpike Bridge Postings and Clearance Data",
    source_url: "https://www.transportation.ohio.gov/programs/bridge-operations/bridge-load-postings",
    source_type: "dataset",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "ODOT bridge posting data for turnpike and state routes.",
  },
  {
    id: "state-fl-restrictions",
    jurisdiction_level: "state",
    state: "FL",
    agency: "Florida Department of Transportation",
    title: "Florida Bridge Weight and Clearance Restrictions",
    source_url: "https://www.fdot.gov/maintenance/Bridges.shtm",
    source_type: "dataset",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "FDOT bridge restriction data for Skyway, I-4 corridor, and key freight routes.",
  },
  {
    id: "state-in-restrictions",
    jurisdiction_level: "state",
    state: "IN",
    agency: "Indiana Department of Transportation",
    title: "Indiana OS/OW and Bridge Restrictions",
    source_url: "https://www.in.gov/indot/doing-business-with-indot/permits/",
    source_type: "dataset",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "INDOT oversize/overweight permit corridors and bridge clearance reference.",
  },
  {
    id: "state-mi-tunnel-restrictions",
    jurisdiction_level: "state",
    state: "MI",
    agency: "Michigan Department of Transportation",
    title: "Detroit-Windsor Tunnel Hazmat and Clearance Restrictions",
    source_url: "https://www.michigan.gov/mdot/travel/trucking",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "MDOT tunnel restrictions including Detroit-Windsor and Blue Water Bridge.",
  },
  {
    id: "state-ky-restrictions",
    jurisdiction_level: "state",
    state: "KY",
    agency: "Kentucky Transportation Cabinet",
    title: "Kentucky Bridge and Tunnel Restrictions",
    source_url: "https://transportation.ky.gov/Permits/Pages/default.aspx",
    source_type: "dataset",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "KYTC bridge clearance and tunnel restriction data.",
  },
  {
    id: "state-ar-ports-of-entry",
    jurisdiction_level: "state",
    state: "AR",
    agency: "Arkansas Department of Transportation",
    title: "Arkansas Weigh Stations and Ports of Entry",
    source_url: "https://www.ardot.gov/divisions/highway-police/weigh-stations/",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "ARDOT Highway Police weigh station and POE locations for freight screening.",
  },
  {
    id: "state-de-bridge-hazmat",
    jurisdiction_level: "state",
    state: "DE",
    agency: "Delaware River and Bay Authority",
    title: "Delaware Memorial Bridge Hazmat and Escort Rules",
    source_url: "https://www.drba.net/hazmat-rules",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "DRBA hazmat routing and escort requirements for the Delaware Memorial Bridge.",
  },
  {
    id: "state-ks-ports-of-entry",
    jurisdiction_level: "state",
    state: "KS",
    agency: "Kansas Corporation Commission",
    title: "Kansas Ports of Entry and Weigh Stations",
    source_url: "https://kcc.ks.gov/transportation/port-of-entry",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "KCC and KDOT port-of-entry locations for commercial vehicle screening.",
  },
  {
    id: "state-me-turnpike-restrictions",
    jurisdiction_level: "state",
    state: "ME",
    agency: "Maine Turnpike Authority",
    title: "Maine Turnpike Size and Weight Restrictions",
    source_url: "https://www.maineturnpike.com/Business-With-MTA/Permits.aspx",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "MTA specific height, weight, and hazmat rules for the I-95 corridor.",
  },
  {
    id: "state-ms-bridge-restrictions",
    jurisdiction_level: "state",
    state: "MS",
    agency: "Mississippi Department of Transportation",
    title: "Mississippi Bridge Postings and OS/OW Rules",
    source_url: "https://mdot.ms.gov/portal/permits",
    source_type: "dataset",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "MDOT bridge posting and permit route restrictions for state corridors.",
  },
  {
    id: "state-mt-ports-of-entry",
    jurisdiction_level: "state",
    state: "MT",
    agency: "Montana Department of Transportation",
    title: "Montana Motor Carrier Services Ports of Entry",
    source_url: "https://www.mdt.mt.gov/business/mcs/poe.aspx",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "MDT MCS port-of-entry and weigh station screening locations.",
  },
  {
    id: "state-nh-franconia-notch-rules",
    jurisdiction_level: "state",
    state: "NH",
    agency: "New Hampshire Department of Transportation",
    title: "Franconia Notch State Park Truck Restrictions",
    source_url: "https://www.nh.gov/dot/org/operations/highwaymaintenance/franconianotch.htm",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "NHDOT commercial vehicle and hazardous materials restrictions for Franconia Notch Parkway.",
  },
  {
    id: "state-nd-weigh-stations",
    jurisdiction_level: "state",
    state: "ND",
    agency: "North Dakota Highway Patrol",
    title: "North Dakota Weigh Station Locations",
    source_url: "https://www.ndhp.nd.gov/motor-carrier-resources/weigh-stations",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "NDHP weigh station locations used for Bakken and I-94 freight screening.",
  },
  {
    id: "state-sd-ports-of-entry",
    jurisdiction_level: "state",
    state: "SD",
    agency: "South Dakota Department of Revenue",
    title: "South Dakota Ports of Entry",
    source_url: "https://dor.sd.gov/business/motor-carrier/ports-of-entry/",
    source_type: "map",
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "manual-review",
    notes: "South Dakota motor carrier POE and screening locations.",
  },
];

export const ROUTING_SOURCE_REGISTRY: RoutingSourceRegistryEntry[] = [
  ...federalSources,
  ...southwestOverlaySources,
  ...expandedOverlaySources,
  ...contiguousStateSources.map(([state, stateName, agency, sourceUrl]) => ({
    id: `state-${state.toLowerCase()}-dot`,
    jurisdiction_level: "state" as const,
    state,
    agency,
    title: `${stateName} truck route / permit source portal`,
    source_url: sourceUrl,
    source_type: "state-dot-portal" as const,
    last_checked_at: LAST_CHECKED_AT,
    ingestion_method: "state-portal" as const,
    notes: "Official DOT portal used as the entry point for state truck-route, permit, and restriction documents.",
  })),
];

// ── All 48 contiguous state bounding boxes ──────────────────────────

export const PRIORITY_STATE_OVERLAY_BOUNDS: Record<string, RouteRestrictionBoundingBox> = {
  AL: { min_lat: 30.1, max_lat: 35.0, min_lng: -88.5, max_lng: -84.9 },
  AZ: { min_lat: 31.2, max_lat: 37.1, min_lng: -114.9, max_lng: -109.0 },
  AR: { min_lat: 33.0, max_lat: 36.5, min_lng: -94.6, max_lng: -89.6 },
  CA: { min_lat: 32.4, max_lat: 42.1, min_lng: -124.6, max_lng: -114.1 },
  CO: { min_lat: 36.9, max_lat: 41.0, min_lng: -109.1, max_lng: -102.0 },
  CT: { min_lat: 40.9, max_lat: 42.1, min_lng: -73.8, max_lng: -71.8 },
  DE: { min_lat: 38.4, max_lat: 39.8, min_lng: -75.8, max_lng: -75.0 },
  FL: { min_lat: 24.4, max_lat: 31.0, min_lng: -87.7, max_lng: -79.9 },
  GA: { min_lat: 30.3, max_lat: 35.1, min_lng: -85.7, max_lng: -80.7 },
  ID: { min_lat: 41.9, max_lat: 49.0, min_lng: -117.3, max_lng: -111.0 },
  IL: { min_lat: 36.9, max_lat: 42.6, min_lng: -91.6, max_lng: -87.0 },
  IN: { min_lat: 37.7, max_lat: 41.8, min_lng: -88.1, max_lng: -84.8 },
  IA: { min_lat: 40.3, max_lat: 43.5, min_lng: -96.7, max_lng: -90.1 },
  KS: { min_lat: 36.9, max_lat: 40.0, min_lng: -102.1, max_lng: -94.6 },
  KY: { min_lat: 36.5, max_lat: 39.2, min_lng: -89.6, max_lng: -81.9 },
  LA: { min_lat: 28.9, max_lat: 33.0, min_lng: -94.1, max_lng: -88.8 },
  ME: { min_lat: 43.0, max_lat: 47.5, min_lng: -71.1, max_lng: -66.9 },
  MD: { min_lat: 37.9, max_lat: 39.7, min_lng: -79.5, max_lng: -75.0 },
  MA: { min_lat: 41.2, max_lat: 42.9, min_lng: -73.5, max_lng: -69.9 },
  MI: { min_lat: 41.7, max_lat: 48.3, min_lng: -90.4, max_lng: -82.1 },
  MN: { min_lat: 43.5, max_lat: 49.4, min_lng: -97.3, max_lng: -89.5 },
  MS: { min_lat: 30.1, max_lat: 35.0, min_lng: -91.7, max_lng: -88.1 },
  MO: { min_lat: 35.9, max_lat: 40.6, min_lng: -95.8, max_lng: -89.1 },
  MT: { min_lat: 44.3, max_lat: 49.0, min_lng: -116.1, max_lng: -104.0 },
  NE: { min_lat: 39.9, max_lat: 43.0, min_lng: -104.1, max_lng: -95.3 },
  NV: { min_lat: 35.0, max_lat: 42.1, min_lng: -120.1, max_lng: -114.0 },
  NH: { min_lat: 42.6, max_lat: 45.3, min_lng: -72.6, max_lng: -70.6 },
  NJ: { min_lat: 38.9, max_lat: 41.4, min_lng: -75.6, max_lng: -73.9 },
  NM: { min_lat: 31.3, max_lat: 37.0, min_lng: -109.1, max_lng: -103.0 },
  NY: { min_lat: 40.5, max_lat: 45.0, min_lng: -79.8, max_lng: -71.9 },
  NC: { min_lat: 33.8, max_lat: 36.6, min_lng: -84.3, max_lng: -75.5 },
  ND: { min_lat: 45.9, max_lat: 49.0, min_lng: -104.1, max_lng: -96.6 },
  OH: { min_lat: 38.4, max_lat: 42.0, min_lng: -84.9, max_lng: -80.5 },
  OK: { min_lat: 33.6, max_lat: 37.0, min_lng: -103.0, max_lng: -94.4 },
  OR: { min_lat: 41.9, max_lat: 46.3, min_lng: -124.8, max_lng: -116.3 },
  PA: { min_lat: 39.7, max_lat: 42.3, min_lng: -80.6, max_lng: -74.7 },
  RI: { min_lat: 41.1, max_lat: 42.0, min_lng: -71.9, max_lng: -71.1 },
  SC: { min_lat: 32.0, max_lat: 35.2, min_lng: -83.4, max_lng: -78.5 },
  SD: { min_lat: 42.4, max_lat: 45.9, min_lng: -104.1, max_lng: -96.4 },
  TN: { min_lat: 34.9, max_lat: 36.8, min_lng: -90.4, max_lng: -81.5 },
  TX: { min_lat: 25.8, max_lat: 36.5, min_lng: -106.7, max_lng: -93.5 },
  UT: { min_lat: 36.9, max_lat: 42.0, min_lng: -114.1, max_lng: -109.0 },
  VT: { min_lat: 42.7, max_lat: 45.0, min_lng: -73.5, max_lng: -71.5 },
  VA: { min_lat: 36.4, max_lat: 39.5, min_lng: -83.8, max_lng: -75.1 },
  WA: { min_lat: 45.5, max_lat: 49.1, min_lng: -124.9, max_lng: -116.8 },
  WV: { min_lat: 37.2, max_lat: 40.6, min_lng: -82.7, max_lng: -77.7 },
  WI: { min_lat: 42.5, max_lat: 47.1, min_lng: -92.9, max_lng: -87.0 },
  WY: { min_lat: 40.9, max_lat: 45.0, min_lng: -111.1, max_lng: -104.1 },
};

// ────────────────────────────────────────────────────────────────────
//  Normalized Restrictions
//  Organized by state → restriction type for clarity
// ────────────────────────────────────────────────────────────────────

export const NORMALIZED_ROUTE_RESTRICTIONS: NormalizedRouteRestriction[] = [

  // ── CALIFORNIA ────────────────────────────────────────────────────
  {
    id: "state-ca-la-route-110-weight",
    source_id: "state-ca-route-110",
    state: "CA",
    title: "Pasadena Freeway commercial vehicle restriction",
    route_id: "Route 110",
    geometry_type: "bbox",
    bbox: { min_lat: 34.05, max_lat: 34.16, min_lng: -118.25, max_lng: -118.14 },
    segment_description: "Route 110 between US 101 in Los Angeles and Glenarm Street in Pasadena",
    restriction_type: "route_weight_limit",
    restriction_value: 6000,
    restriction_units: "lb",
    applies_to_vehicle_class: "all-trucks",
    vehicle_applicability: { max_weight_lb: 6000 },
    raw_text: "No commercial vehicles over 6,000 pounds gross vehicle weight, including buses unless authorized by the PUC.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-ca-caldecott-hazmat-window",
    source_id: "state-ca-special-route-restrictions",
    state: "CA",
    title: "Caldecott Tunnel hazmat time-window screening",
    route_id: "Route 24",
    geometry_type: "bbox",
    bbox: { min_lat: 37.84, max_lat: 37.87, min_lng: -122.25, max_lng: -122.18 },
    segment_description: "Caldecott Tunnel corridor between Alameda and Contra Costa counties",
    restriction_type: "hazmat_time_window",
    restriction_value: "03:00-05:00",
    applies_to_vehicle_class: "hazmat",
    hazmat_applicability: {
      restricted: true,
      description: "Explosives, flammables, liquefied petroleum gas, and poisonous gas tank movements are only allowed through the tunnel from 3:00 a.m. to 5:00 a.m.",
    },
    permit_required: true,
    advisory_only: true,
    raw_text: "Transport of explosives, flammables, liquified petroleum gas or poisonous gas in a tank truck, trailer or semitrailer allowed only 3 am - 5 am.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-ca-alameda-tubes-hazmat",
    source_id: "state-ca-special-route-restrictions",
    state: "CA",
    title: "Webster and Posey Tubes hazmat restriction",
    route_id: "Route 260",
    geometry_type: "bbox",
    bbox: { min_lat: 37.77, max_lat: 37.80, min_lng: -122.29, max_lng: -122.24 },
    segment_description: "Route 260 Webster and Posey Tubes between Alameda and Oakland",
    restriction_type: "state_hazmat",
    restriction_value: true,
    applies_to_vehicle_class: "hazmat",
    hazmat_applicability: {
      restricted: true,
      description: "Hazardous materials and waste movements are restricted through the Webster and Posey Tubes.",
    },
    permit_required: true,
    raw_text: "Trucks restricted from transporting hazardous materials/waste through Webster and Posey Tubes.",
    verification_status: "normalized-reviewed",
  },

  // ── ARIZONA ───────────────────────────────────────────────────────
  {
    id: "state-az-us60-queen-creek-escort",
    source_id: "state-az-table-4",
    state: "AZ",
    title: "US 60 Queen Creek Canyon escort screening",
    route_id: "US 60",
    geometry_type: "bbox",
    bbox: { min_lat: 33.28, max_lat: 33.34, min_lng: -111.20, max_lng: -111.07 },
    segment_description: "US 60 east of Superior through the Queen Creek Canyon bridge corridor",
    restriction_type: "escort_requirement",
    restriction_value: "Over 10'-14' requires F/R; over 14'-16' requires F/R + 2 LE",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { min_height_ft: 10 },
    permit_required: true,
    advisory_only: true,
    raw_text: "Over 10' - 14' = F/R; Over 14' - 16' = F/R + 2 LE near Queen Creek Bridge.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-az-us60-apache-bridge-height",
    source_id: "state-az-table-4",
    state: "AZ",
    title: "Apache Bridge overheight screening",
    route_id: "US 60",
    geometry_type: "bbox",
    bbox: { min_lat: 33.80, max_lat: 33.84, min_lng: -110.56, max_lng: -110.48 },
    segment_description: "US 60 Apache Bridge (Structure 1929) east of Globe",
    restriction_type: "route_height_limit",
    restriction_value: 14,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_height_ft: 14 },
    permit_required: true,
    raw_text: "US 60 MP 292.91 (Apache Bridge - Structure 1929): Over 14' Prohibited.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-az-us60-apache-bridge-escort",
    source_id: "state-az-table-4",
    state: "AZ",
    title: "Apache Bridge escort and crossing advisory",
    route_id: "US 60",
    geometry_type: "bbox",
    bbox: { min_lat: 33.80, max_lat: 33.84, min_lng: -110.56, max_lng: -110.48 },
    segment_description: "US 60 Apache Bridge approach and crossing controls",
    restriction_type: "escort_requirement",
    restriction_value: "Over 12'-14' = F/R; heavier permitted vehicles require bridge coordination and slow centerline crossing",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { min_height_ft: 12 },
    permit_required: true,
    advisory_only: true,
    raw_text: "Over 12' - 14' = F/R. Certain permitted vehicles must coordinate road closures and cross centered at no more than 10 mph.",
    verification_status: "normalized-reviewed",
  },

  // ── NEW MEXICO ────────────────────────────────────────────────────
  {
    id: "state-nm-lordsburg-poe",
    source_id: "state-nm-ports-of-entry",
    state: "NM",
    title: "Lordsburg Port of Entry screening",
    route_id: "I-10",
    geometry_type: "bbox",
    bbox: { min_lat: 32.31, max_lat: 32.36, min_lng: -108.78, max_lng: -108.67 },
    segment_description: "I-10 eastbound mile marker 23 near Lordsburg",
    restriction_type: "inspection_checkpoint",
    restriction_value: "24/7",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "I-10 East Bound Mile Marker 23, Lordsburg, NM 88045. Open 24 Hours 7 Days a week.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-nm-gallup-poe",
    source_id: "state-nm-ports-of-entry",
    state: "NM",
    title: "Gallup Port of Entry screening",
    route_id: "I-40",
    geometry_type: "bbox",
    bbox: { min_lat: 35.50, max_lat: 35.54, min_lng: -108.82, max_lng: -108.70 },
    segment_description: "I-40 eastbound mile marker 12 near Gallup",
    restriction_type: "inspection_checkpoint",
    restriction_value: "24/7",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "I-40 East Bound Mile Marker 12, Gallup, NM 87305. Open 24 Hours 7 Days a week.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-nm-san-jon-poe",
    source_id: "state-nm-ports-of-entry",
    state: "NM",
    title: "San Jon Port of Entry screening",
    route_id: "I-40",
    geometry_type: "bbox",
    bbox: { min_lat: 35.07, max_lat: 35.11, min_lng: -103.39, max_lng: -103.29 },
    segment_description: "I-40 westbound mile marker 357 near San Jon",
    restriction_type: "inspection_checkpoint",
    restriction_value: "24/7",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "I-40 West Bound Mile Marker 357, San Jon, NM 88434. Open 24 Hours 7 Days a week.",
    verification_status: "normalized-reviewed",
  },

  // ── COLORADO ──────────────────────────────────────────────────────
  {
    id: "state-co-ejmt-height",
    source_id: "state-co-permit-rules",
    state: "CO",
    title: "Eisenhower-Johnson Memorial Tunnels height restriction",
    route_id: "I-70",
    geometry_type: "bbox",
    bbox: { min_lat: 39.66, max_lat: 39.72, min_lng: -105.95, max_lng: -105.84 },
    segment_description: "I-70 mileposts 213-214 through the Eisenhower-Johnson Memorial Tunnels",
    restriction_type: "route_height_limit",
    restriction_value: 13.92,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_height_ft: 13.92 },
    permit_required: true,
    raw_text: "An Extra-legal Vehicle or Load greater than thirteen feet eleven inches in Height is prohibited from travel through the tunnels.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-co-ejmt-width-approval",
    source_id: "state-co-permit-rules",
    state: "CO",
    title: "Eisenhower-Johnson Memorial Tunnels width control",
    route_id: "I-70",
    geometry_type: "bbox",
    bbox: { min_lat: 39.66, max_lat: 39.72, min_lng: -105.95, max_lng: -105.84 },
    segment_description: "Tunnel approach parking lots and portals at I-70 mileposts 213-214",
    restriction_type: "escort_requirement",
    restriction_value: "Loads over 11 ft wide must stop for tunnel permission; loads over 8 ft 6 in may be detained during two-way operations",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { min_width_ft: 11 },
    permit_required: true,
    advisory_only: true,
    raw_text: "An Extra-legal Vehicle or Load which is more than eleven feet in Width must stop at the tunnel approach parking lot and obtain permission from the tunnel superintendent or the portal attendant to travel through the tunnels.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-co-ejmt-hazmat-bypass",
    source_id: "state-co-truck-parking-guide",
    state: "CO",
    title: "Eisenhower Tunnel hazmat bypass requirement",
    route_id: "I-70",
    geometry_type: "bbox",
    bbox: { min_lat: 39.66, max_lat: 39.72, min_lng: -105.95, max_lng: -105.84 },
    segment_description: "I-70 tunnel crossing at the Continental Divide",
    restriction_type: "state_hazmat",
    restriction_value: true,
    applies_to_vehicle_class: "hazmat",
    hazmat_applicability: {
      restricted: true,
      description: "Hazmat vehicles are required to use US 6 to bypass the Eisenhower Tunnel. If US 6 is closed, CDOT processes waiting hazmat vehicles through the tunnel at the top of the hour.",
    },
    permit_required: true,
    raw_text: "Vehicles transporting hazardous materials are required to use US 6 to bypass the Eisenhower Tunnel. If this section of US 6 is closed, CDOT will process vehicles transporting hazardous materials through the Eisenhower Tunnel at the top of the hour.",
    verification_status: "normalized-reviewed",
  },

  // ── MARYLAND ──────────────────────────────────────────────────────
  {
    id: "state-md-baltimore-harbor-hazmat",
    source_id: "state-md-mdta-tunnel-restrictions",
    state: "MD",
    title: "Baltimore Harbor Tunnel hazmat restriction",
    route_id: "I-895",
    geometry_type: "bbox",
    bbox: { min_lat: 39.24, max_lat: 39.29, min_lng: -76.64, max_lng: -76.53 },
    segment_description: "Baltimore Harbor Tunnel corridor on I-895",
    restriction_type: "state_hazmat",
    restriction_value: true,
    applies_to_vehicle_class: "hazmat",
    hazmat_applicability: {
      restricted: true,
      description: "Hazmat traffic is prohibited from using the Baltimore Harbor Tunnel and should route via the western section of I-695.",
    },
    permit_required: true,
    raw_text: "Vehicles carrying bottled propane gas in excess of 10 pounds per container, bulk gasoline, flammable liquids, explosives, radioactive and other hazardous materials are prohibited from using the Baltimore Harbor Tunnel (I-895).",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-md-fort-mchenry-hazmat",
    source_id: "state-md-mdta-tunnel-restrictions",
    state: "MD",
    title: "Fort McHenry Tunnel hazmat restriction",
    route_id: "I-95",
    geometry_type: "bbox",
    bbox: { min_lat: 39.24, max_lat: 39.28, min_lng: -76.61, max_lng: -76.54 },
    segment_description: "Fort McHenry Tunnel under Baltimore Harbor on I-95",
    restriction_type: "state_hazmat",
    restriction_value: true,
    applies_to_vehicle_class: "hazmat",
    hazmat_applicability: {
      restricted: true,
      description: "Hazmat traffic is prohibited from using the Fort McHenry Tunnel and should route via the western section of I-695.",
    },
    permit_required: true,
    raw_text: "Vehicles carrying bottled propane gas in excess of 10 pounds per container, bulk gasoline, flammable liquids, explosives, radioactive and other hazardous materials are prohibited from using the Fort McHenry Tunnel (I-95).",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-md-fort-mchenry-height",
    source_id: "state-md-mdta-tunnel-advisory",
    state: "MD",
    title: "Fort McHenry Tunnel height restriction",
    route_id: "I-95",
    geometry_type: "bbox",
    bbox: { min_lat: 39.24, max_lat: 39.28, min_lng: -76.61, max_lng: -76.54 },
    segment_description: "Fort McHenry Tunnel corridor on I-95 south of downtown Baltimore",
    restriction_type: "route_height_limit",
    restriction_value: 14.5,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_height_ft: 14.5 },
    permit_required: true,
    raw_text: "I-95 Fort McHenry Tunnel restrictions are height – 14' - 6\".",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-md-fort-mchenry-width",
    source_id: "state-md-mdta-tunnel-advisory",
    state: "MD",
    title: "Fort McHenry Tunnel width restriction",
    route_id: "I-95",
    geometry_type: "bbox",
    bbox: { min_lat: 39.24, max_lat: 39.28, min_lng: -76.61, max_lng: -76.54 },
    segment_description: "Fort McHenry Tunnel corridor on I-95 south of downtown Baltimore",
    restriction_type: "route_width_limit",
    restriction_value: 11,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_width_ft: 11 },
    permit_required: true,
    raw_text: "I-95 Fort McHenry Tunnel restrictions are width – 11'.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-md-baltimore-harbor-height",
    source_id: "state-md-mdta-tunnel-restrictions",
    state: "MD",
    title: "Baltimore Harbor Tunnel height restriction",
    route_id: "I-895",
    geometry_type: "bbox",
    bbox: { min_lat: 39.24, max_lat: 39.29, min_lng: -76.64, max_lng: -76.53 },
    segment_description: "Baltimore Harbor Tunnel corridor on I-895",
    restriction_type: "route_height_limit",
    restriction_value: 13.5,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_height_ft: 13.5 },
    permit_required: true,
    raw_text: "Baltimore Harbor Tunnel Thruway (I-895) – Vehicles over 13'-6\" in height are prohibited.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-md-baltimore-harbor-width",
    source_id: "state-md-mdta-tunnel-restrictions",
    state: "MD",
    title: "Baltimore Harbor Tunnel width restriction",
    route_id: "I-895",
    geometry_type: "bbox",
    bbox: { min_lat: 39.24, max_lat: 39.29, min_lng: -76.64, max_lng: -76.53 },
    segment_description: "Baltimore Harbor Tunnel corridor on I-895",
    restriction_type: "route_width_limit",
    restriction_value: 8,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_width_ft: 8 },
    permit_required: true,
    raw_text: "Baltimore Harbor Tunnel Thruway (I-895) – Vehicles over 96\" (8 feet) in width are prohibited.",
    verification_status: "normalized-reviewed",
  },

  // ── GEORGIA ───────────────────────────────────────────────────────
  {
    id: "state-ga-atl-i75-bridge-weight",
    source_id: "state-ga-dot",
    state: "GA",
    title: "Atlanta metro bridge posting screening",
    route_id: "I-75",
    geometry_type: "bbox",
    bbox: { min_lat: 33.55, max_lat: 33.73, min_lng: -84.45, max_lng: -84.30 },
    segment_description: "South Atlanta I-75 posted bridge zone",
    restriction_type: "bridge_weight",
    restriction_value: 80000,
    restriction_units: "lb",
    applies_to_vehicle_class: "overweight",
    vehicle_applicability: { max_weight_lb: 80000 },
    permit_required: true,
    raw_text: "State overlay screening for posted bridge restrictions in the Atlanta freight corridor.",
    verification_status: "normalized-reviewed",
    rule_label: "GA-ATL-I75-W1",
  },

  // ── ILLINOIS ──────────────────────────────────────────────────────
  {
    id: "state-il-chicago-clearance",
    source_id: "state-il-dot",
    state: "IL",
    title: "Chicago clearance screening segment",
    route_id: "I-290",
    geometry_type: "bbox",
    bbox: { min_lat: 41.87, max_lat: 41.91, min_lng: -87.73, max_lng: -87.61 },
    segment_description: "Central Chicago low-clearance approach segment",
    restriction_type: "bridge_clearance",
    restriction_value: 13.5,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_height_ft: 13.5 },
    permit_required: true,
    raw_text: "State overlay screening for restricted Chicago freight approaches.",
    verification_status: "normalized-reviewed",
    rule_label: "IL-CHI-CLR-1",
  },
  {
    id: "state-il-lake-shore-drive-prohibition",
    source_id: "state-il-dot",
    state: "IL",
    title: "Lake Shore Drive commercial vehicle prohibition",
    route_id: "US-41 / Lake Shore Drive",
    geometry_type: "bbox",
    bbox: { min_lat: 41.78, max_lat: 42.02, min_lng: -87.64, max_lng: -87.58 },
    segment_description: "Lake Shore Drive from 67th Street to Hollywood Avenue, Chicago",
    restriction_type: "truck_prohibited",
    restriction_value: true,
    applies_to_vehicle_class: "all-trucks",
    raw_text: "Commercial vehicles prohibited on Lake Shore Drive. Violators subject to fines up to $500.",
    verification_status: "normalized-reviewed",
  },

  // ── VIRGINIA ──────────────────────────────────────────────────────
  {
    id: "state-va-hrbt-hazmat",
    source_id: "state-va-dot",
    state: "VA",
    title: "Hampton Roads hazmat route screening",
    route_id: "I-64",
    geometry_type: "bbox",
    bbox: { min_lat: 36.96, max_lat: 37.05, min_lng: -76.38, max_lng: -76.26 },
    segment_description: "Hampton Roads bridge-tunnel corridor",
    restriction_type: "state_hazmat",
    restriction_value: true,
    applies_to_vehicle_class: "hazmat",
    hazmat_applicability: { restricted: true, description: "Hazmat traffic requires a state-approved alternate corridor." },
    permit_required: true,
    raw_text: "State overlay screening for hazmat-sensitive tunnel routing.",
    verification_status: "normalized-reviewed",
  },

  // ── WASHINGTON ────────────────────────────────────────────────────
  {
    id: "state-wa-seattle-hazmat",
    source_id: "state-wa-dot",
    state: "WA",
    title: "Seattle tunnel hazmat screening",
    route_id: "SR-99",
    geometry_type: "bbox",
    bbox: { min_lat: 47.61, max_lat: 47.63, min_lng: -122.35, max_lng: -122.33 },
    segment_description: "Seattle waterfront tunnel corridor",
    restriction_type: "state_hazmat",
    restriction_value: true,
    applies_to_vehicle_class: "hazmat",
    hazmat_applicability: { restricted: true, description: "Hazmat cargo requires an alternate surface route." },
    permit_required: true,
    raw_text: "State overlay screening for Seattle tunnel hazmat controls.",
    verification_status: "normalized-reviewed",
  },

  // ── TEXAS ─────────────────────────────────────────────────────────
  {
    id: "state-tx-i35-austin-bridge-clearance",
    source_id: "state-tx-bridge-restrictions",
    state: "TX",
    title: "I-35 Austin low bridge clearance zone",
    route_id: "I-35",
    geometry_type: "bbox",
    bbox: { min_lat: 30.24, max_lat: 30.30, min_lng: -97.76, max_lng: -97.72 },
    segment_description: "I-35 through downtown Austin — multiple low-clearance overpasses",
    restriction_type: "bridge_clearance",
    restriction_value: 14.0,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_height_ft: 14.0 },
    permit_required: true,
    raw_text: "Multiple low-clearance structures on I-35 through downtown Austin. Over-height vehicles must use alternate route.",
    verification_status: "normalized-reviewed",
    rule_label: "TX-AUS-I35-CLR-1",
  },
  {
    id: "state-tx-i10-houston-bridge-weight",
    source_id: "state-tx-bridge-restrictions",
    state: "TX",
    title: "I-10 Houston Ship Channel Bridge weight posting",
    route_id: "I-10",
    geometry_type: "bbox",
    bbox: { min_lat: 29.74, max_lat: 29.78, min_lng: -95.10, max_lng: -95.05 },
    segment_description: "I-10 San Jacinto River / Houston Ship Channel Bridge",
    restriction_type: "bridge_weight",
    restriction_value: 80000,
    restriction_units: "lb",
    applies_to_vehicle_class: "overweight",
    vehicle_applicability: { max_weight_lb: 80000 },
    permit_required: true,
    raw_text: "Posted bridge structure on I-10 east of Houston. Overweight loads require OS/OW permit and bridge analysis.",
    verification_status: "normalized-reviewed",
    rule_label: "TX-HOU-I10-W1",
  },
  {
    id: "state-tx-i35-laredo-poe",
    source_id: "state-tx-ports-of-entry",
    state: "TX",
    title: "Laredo World Trade Bridge port of entry",
    route_id: "I-35",
    geometry_type: "bbox",
    bbox: { min_lat: 27.49, max_lat: 27.53, min_lng: -99.53, max_lng: -99.47 },
    segment_description: "I-35 southbound at Laredo — World Trade Bridge commercial crossing",
    restriction_type: "inspection_checkpoint",
    restriction_value: "24/7",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "World Trade Bridge at Laredo, TX. Primary commercial crossing into Mexico. Open 24/7.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-tx-i35-dallas-width",
    source_id: "state-tx-bridge-restrictions",
    state: "TX",
    title: "I-35E Dallas narrow lanes advisory",
    route_id: "I-35E",
    geometry_type: "bbox",
    bbox: { min_lat: 32.72, max_lat: 32.82, min_lng: -96.84, max_lng: -96.78 },
    segment_description: "I-35E through downtown Dallas — narrow lanes during construction",
    restriction_type: "route_width_limit",
    restriction_value: 10,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { min_width_ft: 10 },
    permit_required: true,
    advisory_only: true,
    raw_text: "Loads wider than 10 ft require TxDOT OS/OW permit coordination through Dallas I-35E corridor.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-tx-sh-130-length",
    source_id: "state-tx-bridge-restrictions",
    state: "TX",
    title: "SH 130 oversize length restriction",
    route_id: "SH 130",
    geometry_type: "bbox",
    bbox: { min_lat: 30.10, max_lat: 30.55, min_lng: -97.60, max_lng: -97.45 },
    segment_description: "SH 130 toll road east of Austin — tight interchange geometry",
    restriction_type: "route_length_limit",
    restriction_value: 110,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { min_length_ft: 110 },
    permit_required: true,
    advisory_only: true,
    raw_text: "Loads over 110 ft total length must coordinate with TxDOT for SH 130 interchange clearances.",
    verification_status: "normalized-reviewed",
  },

  // ── PENNSYLVANIA ──────────────────────────────────────────────────
  {
    id: "state-pa-turnpike-clearance",
    source_id: "state-pa-bridge-restrictions",
    state: "PA",
    title: "Pennsylvania Turnpike standard clearance limit",
    route_id: "I-76 (PA Turnpike)",
    geometry_type: "bbox",
    bbox: { min_lat: 39.90, max_lat: 40.50, min_lng: -80.30, max_lng: -75.20 },
    segment_description: "PA Turnpike mainline (I-76) — multiple tunnel and bridge clearance limits",
    restriction_type: "tunnel_clearance",
    restriction_value: 13.5,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_height_ft: 13.5 },
    permit_required: true,
    raw_text: "PA Turnpike tunnels: Allegheny, Tuscarora, Kittatinny, Blue Mountain — standard clearance 13'6\".",
    verification_status: "normalized-reviewed",
    rule_label: "PA-TPKE-CLR-1",
  },
  {
    id: "state-pa-i476-low-bridge",
    source_id: "state-pa-bridge-restrictions",
    state: "PA",
    title: "I-476 (Blue Route) low clearance bridge",
    route_id: "I-476",
    geometry_type: "bbox",
    bbox: { min_lat: 39.93, max_lat: 39.97, min_lng: -75.40, max_lng: -75.34 },
    segment_description: "I-476 at Media/Springfield interchange — low-clearance overpass",
    restriction_type: "bridge_clearance",
    restriction_value: 13.5,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_height_ft: 13.5 },
    permit_required: true,
    raw_text: "Low-clearance structure on I-476 near Media exit. Over-height loads must exit and use surface route.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-pa-i76-schuylkill-width",
    source_id: "state-pa-bridge-restrictions",
    state: "PA",
    title: "I-76 Schuylkill Expressway width restriction",
    route_id: "I-76",
    geometry_type: "bbox",
    bbox: { min_lat: 39.95, max_lat: 40.02, min_lng: -75.25, max_lng: -75.15 },
    segment_description: "I-76 (Schuylkill Expressway) through Center City Philadelphia",
    restriction_type: "route_width_limit",
    restriction_value: 10,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { min_width_ft: 10 },
    permit_required: true,
    raw_text: "Narrow lane widths on Schuylkill Expressway. Loads over 10 ft wide require PennDOT permit coordination.",
    verification_status: "normalized-reviewed",
  },

  // ── NEW YORK ──────────────────────────────────────────────────────
  {
    id: "state-ny-hutchinson-pkwy-ban",
    source_id: "state-ny-parkway-restrictions",
    state: "NY",
    title: "Hutchinson River Parkway commercial vehicle ban",
    route_id: "Hutchinson River Parkway",
    geometry_type: "polyline",
    polyline: {
      coordinates: [
        { lat: 40.83, lng: -73.82 },
        { lat: 40.88, lng: -73.80 },
        { lat: 40.93, lng: -73.78 },
        { lat: 40.98, lng: -73.75 },
      ],
      buffer_miles: 0.3,
    },
    segment_description: "Hutchinson River Parkway — entire length from Pelham to CT state line",
    restriction_type: "truck_prohibited",
    restriction_value: true,
    applies_to_vehicle_class: "all-trucks",
    raw_text: "Commercial vehicles prohibited on all NY State parkways. Fines up to $500 per violation.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-ny-saw-mill-pkwy-ban",
    source_id: "state-ny-parkway-restrictions",
    state: "NY",
    title: "Saw Mill River Parkway commercial vehicle ban",
    route_id: "Saw Mill River Parkway",
    geometry_type: "polyline",
    polyline: {
      coordinates: [
        { lat: 40.88, lng: -73.87 },
        { lat: 40.95, lng: -73.87 },
        { lat: 41.02, lng: -73.85 },
        { lat: 41.10, lng: -73.82 },
      ],
      buffer_miles: 0.3,
    },
    segment_description: "Saw Mill River Parkway — entire length from Elmsford to Yonkers",
    restriction_type: "truck_prohibited",
    restriction_value: true,
    applies_to_vehicle_class: "all-trucks",
    raw_text: "Commercial vehicles prohibited on all NY State parkways. Fines up to $500 per violation.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-ny-taconic-pkwy-ban",
    source_id: "state-ny-parkway-restrictions",
    state: "NY",
    title: "Taconic State Parkway commercial vehicle ban",
    route_id: "Taconic State Parkway",
    geometry_type: "polyline",
    polyline: {
      coordinates: [
        { lat: 41.10, lng: -73.80 },
        { lat: 41.30, lng: -73.78 },
        { lat: 41.55, lng: -73.78 },
        { lat: 41.75, lng: -73.82 },
        { lat: 42.00, lng: -73.80 },
      ],
      buffer_miles: 0.5,
    },
    segment_description: "Taconic State Parkway — Kensico Dam to I-90 interchange",
    restriction_type: "truck_prohibited",
    restriction_value: true,
    applies_to_vehicle_class: "all-trucks",
    raw_text: "Commercial vehicles prohibited on all NY State parkways. Low overpasses (as low as 10'6\").",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-ny-holland-tunnel-hazmat",
    source_id: "state-ny-tunnel-restrictions",
    state: "NY",
    title: "Holland Tunnel hazmat restriction",
    route_id: "I-78 / Holland Tunnel",
    geometry_type: "bbox",
    bbox: { min_lat: 40.72, max_lat: 40.74, min_lng: -74.04, max_lng: -74.00 },
    segment_description: "Holland Tunnel between Manhattan and Jersey City",
    restriction_type: "tunnel_hazmat",
    restriction_value: true,
    applies_to_vehicle_class: "hazmat",
    hazmat_applicability: { restricted: true, description: "All hazardous materials prohibited. Use George Washington Bridge for hazmat routing." },
    permit_required: true,
    raw_text: "Holland Tunnel: No hazardous materials. Alt route: George Washington Bridge.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-ny-lincoln-tunnel-hazmat",
    source_id: "state-ny-tunnel-restrictions",
    state: "NY",
    title: "Lincoln Tunnel hazmat restriction",
    route_id: "NJ-495 / Lincoln Tunnel",
    geometry_type: "bbox",
    bbox: { min_lat: 40.75, max_lat: 40.77, min_lng: -74.02, max_lng: -73.99 },
    segment_description: "Lincoln Tunnel between Midtown Manhattan and Weehawken, NJ",
    restriction_type: "tunnel_hazmat",
    restriction_value: true,
    applies_to_vehicle_class: "hazmat",
    hazmat_applicability: { restricted: true, description: "All hazardous materials prohibited. Use George Washington Bridge." },
    permit_required: true,
    raw_text: "Lincoln Tunnel: No hazardous materials. Alt route: George Washington Bridge.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-ny-gwb-clearance",
    source_id: "state-ny-tunnel-restrictions",
    state: "NY",
    title: "George Washington Bridge upper level clearance",
    route_id: "I-95 / GWB",
    geometry_type: "bbox",
    bbox: { min_lat: 40.84, max_lat: 40.86, min_lng: -73.96, max_lng: -73.94 },
    segment_description: "George Washington Bridge upper level deck",
    restriction_type: "bridge_clearance",
    restriction_value: 14.0,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_height_ft: 14.0 },
    permit_required: true,
    raw_text: "GWB upper level clearance 14'0\". Over-height loads may request lower-level routing (clearance 13'0\").",
    verification_status: "normalized-reviewed",
  },

  // ── NEW JERSEY ────────────────────────────────────────────────────
  {
    id: "state-nj-pulaski-skyway-ban",
    source_id: "state-nj-restrictions",
    state: "NJ",
    title: "Pulaski Skyway commercial vehicle prohibition",
    route_id: "US-1/9 / Pulaski Skyway",
    geometry_type: "polyline",
    polyline: {
      coordinates: [
        { lat: 40.72, lng: -74.08 },
        { lat: 40.73, lng: -74.10 },
        { lat: 40.74, lng: -74.12 },
        { lat: 40.73, lng: -74.14 },
      ],
      buffer_miles: 0.2,
    },
    segment_description: "Pulaski Skyway between Jersey City and Newark",
    restriction_type: "truck_prohibited",
    restriction_value: true,
    applies_to_vehicle_class: "all-trucks",
    raw_text: "No commercial vehicles on Pulaski Skyway. Trucks must use NJ Turnpike or local routes.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-nj-turnpike-hazmat",
    source_id: "state-nj-restrictions",
    state: "NJ",
    title: "NJ Turnpike hazmat corridor restrictions",
    route_id: "NJ Turnpike",
    geometry_type: "bbox",
    bbox: { min_lat: 39.50, max_lat: 40.85, min_lng: -74.70, max_lng: -74.05 },
    segment_description: "NJ Turnpike mainline — restricted hazmat interchanges",
    restriction_type: "state_hazmat",
    restriction_value: true,
    applies_to_vehicle_class: "hazmat",
    hazmat_applicability: { restricted: true, description: "Certain hazmat classes restricted at specific interchanges. Contact NJ Turnpike Authority for routing requirements." },
    permit_required: true,
    advisory_only: true,
    raw_text: "NJ Turnpike hazmat routing varies by interchange and cargo class. Pre-notification required.",
    verification_status: "normalized-reviewed",
  },

  // ── OHIO ──────────────────────────────────────────────────────────
  {
    id: "state-oh-turnpike-clearance",
    source_id: "state-oh-turnpike-restrictions",
    state: "OH",
    title: "Ohio Turnpike standard clearance limit",
    route_id: "I-80/90 (OH Turnpike)",
    geometry_type: "bbox",
    bbox: { min_lat: 41.30, max_lat: 41.75, min_lng: -84.80, max_lng: -80.60 },
    segment_description: "Ohio Turnpike mainline — overpasses and toll plazas",
    restriction_type: "bridge_clearance",
    restriction_value: 13.5,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_height_ft: 13.5 },
    permit_required: true,
    raw_text: "Ohio Turnpike standard overhead clearance is 13'6\" at most structures.",
    verification_status: "normalized-reviewed",
    rule_label: "OH-TPKE-CLR-1",
  },
  {
    id: "state-oh-i90-cleveland-bridge-weight",
    source_id: "state-oh-turnpike-restrictions",
    state: "OH",
    title: "I-90 Cleveland bridge posting",
    route_id: "I-90",
    geometry_type: "bbox",
    bbox: { min_lat: 41.48, max_lat: 41.52, min_lng: -81.72, max_lng: -81.62 },
    segment_description: "I-90 Innerbelt Bridge area in Cleveland",
    restriction_type: "bridge_weight",
    restriction_value: 80000,
    restriction_units: "lb",
    applies_to_vehicle_class: "overweight",
    vehicle_applicability: { max_weight_lb: 80000 },
    permit_required: true,
    raw_text: "Innerbelt Bridge area weight restrictions. Overweight loads must coordinate with ODOT.",
    verification_status: "normalized-reviewed",
    rule_label: "OH-CLE-I90-W1",
  },

  // ── FLORIDA ───────────────────────────────────────────────────────
  {
    id: "state-fl-skyway-weight",
    source_id: "state-fl-restrictions",
    state: "FL",
    title: "Sunshine Skyway Bridge weight restriction",
    route_id: "I-275",
    geometry_type: "bbox",
    bbox: { min_lat: 27.56, max_lat: 27.64, min_lng: -82.68, max_lng: -82.62 },
    segment_description: "Sunshine Skyway Bridge over Tampa Bay on I-275",
    restriction_type: "bridge_weight",
    restriction_value: 80000,
    restriction_units: "lb",
    applies_to_vehicle_class: "overweight",
    vehicle_applicability: { max_weight_lb: 80000 },
    permit_required: true,
    raw_text: "Sunshine Skyway Bridge: 80,000 lb gross weight limit. OS/OW loads must use I-4 alternate.",
    verification_status: "normalized-reviewed",
    rule_label: "FL-SKY-I275-W1",
  },
  {
    id: "state-fl-i4-orlando-clearance",
    source_id: "state-fl-restrictions",
    state: "FL",
    title: "I-4 Orlando interchange clearance screening",
    route_id: "I-4",
    geometry_type: "bbox",
    bbox: { min_lat: 28.52, max_lat: 28.58, min_lng: -81.42, max_lng: -81.35 },
    segment_description: "I-4 through downtown Orlando — multiple low-clearance interchanges",
    restriction_type: "bridge_clearance",
    restriction_value: 14.5,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_height_ft: 14.5 },
    permit_required: true,
    raw_text: "I-4 Ultimate project structures in Orlando. Some clearances under 15 ft during construction.",
    verification_status: "normalized-reviewed",
  },

  // ── INDIANA ───────────────────────────────────────────────────────
  {
    id: "state-in-i65-bridge-weight",
    source_id: "state-in-restrictions",
    state: "IN",
    title: "I-65 Indianapolis bridge posting",
    route_id: "I-65",
    geometry_type: "bbox",
    bbox: { min_lat: 39.72, max_lat: 39.82, min_lng: -86.20, max_lng: -86.12 },
    segment_description: "I-65 through downtown Indianapolis — posted structures",
    restriction_type: "bridge_weight",
    restriction_value: 80000,
    restriction_units: "lb",
    applies_to_vehicle_class: "overweight",
    vehicle_applicability: { max_weight_lb: 80000 },
    permit_required: true,
    raw_text: "Multiple posted bridges on I-65 through downtown Indianapolis. OS/OW permit required.",
    verification_status: "normalized-reviewed",
  },

  // ── MICHIGAN ──────────────────────────────────────────────────────
  {
    id: "state-mi-detroit-windsor-tunnel-hazmat",
    source_id: "state-mi-tunnel-restrictions",
    state: "MI",
    title: "Detroit-Windsor Tunnel hazmat restriction",
    route_id: "Detroit-Windsor Tunnel",
    geometry_type: "bbox",
    bbox: { min_lat: 42.31, max_lat: 42.34, min_lng: -83.05, max_lng: -83.02 },
    segment_description: "Detroit-Windsor Tunnel under the Detroit River",
    restriction_type: "tunnel_hazmat",
    restriction_value: true,
    applies_to_vehicle_class: "hazmat",
    hazmat_applicability: { restricted: true, description: "All hazardous materials prohibited. Use Ambassador Bridge for hazmat crossing." },
    permit_required: true,
    raw_text: "Detroit-Windsor Tunnel: No hazmat. Ambassador Bridge is the designated hazmat crossing.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-mi-detroit-tunnel-clearance",
    source_id: "state-mi-tunnel-restrictions",
    state: "MI",
    title: "Detroit-Windsor Tunnel height restriction",
    route_id: "Detroit-Windsor Tunnel",
    geometry_type: "bbox",
    bbox: { min_lat: 42.31, max_lat: 42.34, min_lng: -83.05, max_lng: -83.02 },
    segment_description: "Detroit-Windsor Tunnel under the Detroit River",
    restriction_type: "tunnel_clearance",
    restriction_value: 12.17,
    restriction_units: "ft",
    applies_to_vehicle_class: "all-trucks",
    vehicle_applicability: { max_height_ft: 12.17 },
    raw_text: "Detroit-Windsor Tunnel clearance: 12'2\". Most commercial vehicles must use Ambassador Bridge.",
    verification_status: "normalized-reviewed",
  },

  // ── MISSOURI ──────────────────────────────────────────────────────
  {
    id: "state-mo-i70-kansas-city-clearance",
    source_id: "state-mo-dot",
    state: "MO",
    title: "I-70 Kansas City low clearance screening",
    route_id: "I-70",
    geometry_type: "bbox",
    bbox: { min_lat: 39.08, max_lat: 39.12, min_lng: -94.62, max_lng: -94.55 },
    segment_description: "I-70 through downtown Kansas City — older overpasses",
    restriction_type: "bridge_clearance",
    restriction_value: 14.0,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_height_ft: 14.0 },
    permit_required: true,
    raw_text: "Low-clearance structures on I-70 through KC downtown area. OS loads consult MoDOT.",
    verification_status: "normalized-reviewed",
  },

  // ── TENNESSEE ─────────────────────────────────────────────────────
  {
    id: "state-tn-i40-nashville-clearance",
    source_id: "state-tn-dot",
    state: "TN",
    title: "I-40 Nashville interchange clearance screening",
    route_id: "I-40",
    geometry_type: "bbox",
    bbox: { min_lat: 36.14, max_lat: 36.18, min_lng: -86.82, max_lng: -86.74 },
    segment_description: "I-40/I-440 interchange area in Nashville",
    restriction_type: "bridge_clearance",
    restriction_value: 14.0,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_height_ft: 14.0 },
    permit_required: true,
    raw_text: "Nashville I-40/I-440 interchange: limited clearances during ongoing construction.",
    verification_status: "normalized-reviewed",
  },

  // ── NORTH CAROLINA ────────────────────────────────────────────────
  {
    id: "state-nc-i40-asheville-weight",
    source_id: "state-nc-dot",
    state: "NC",
    title: "I-40 Asheville bridge weight posting",
    route_id: "I-40",
    geometry_type: "bbox",
    bbox: { min_lat: 35.55, max_lat: 35.62, min_lng: -82.60, max_lng: -82.50 },
    segment_description: "I-40 through Asheville — mountainous bridges",
    restriction_type: "bridge_weight",
    restriction_value: 80000,
    restriction_units: "lb",
    applies_to_vehicle_class: "overweight",
    vehicle_applicability: { max_weight_lb: 80000 },
    permit_required: true,
    raw_text: "I-40 mountain bridge postings near Asheville. OS/OW permits required for heavy loads.",
    verification_status: "normalized-reviewed",
  },

  // ── LOUISIANA ─────────────────────────────────────────────────────
  {
    id: "state-la-i10-baton-rouge-bridge-weight",
    source_id: "state-la-dot",
    state: "LA",
    title: "I-10 Mississippi River Bridge weight posting",
    route_id: "I-10",
    geometry_type: "bbox",
    bbox: { min_lat: 30.43, max_lat: 30.48, min_lng: -91.20, max_lng: -91.15 },
    segment_description: "I-10 Horace Wilkinson Bridge over Mississippi River at Baton Rouge",
    restriction_type: "bridge_weight",
    restriction_value: 80000,
    restriction_units: "lb",
    applies_to_vehicle_class: "overweight",
    vehicle_applicability: { max_weight_lb: 80000 },
    permit_required: true,
    raw_text: "Horace Wilkinson Bridge posted weight limit. Overweight vehicles must contact LaDOTD.",
    verification_status: "normalized-reviewed",
  },

  // ── OKLAHOMA ──────────────────────────────────────────────────────
  {
    id: "state-ok-i40-poe",
    source_id: "state-ok-dot",
    state: "OK",
    title: "Oklahoma I-40 Texola port of entry",
    route_id: "I-40",
    geometry_type: "bbox",
    bbox: { min_lat: 35.19, max_lat: 35.24, min_lng: -100.02, max_lng: -99.92 },
    segment_description: "I-40 eastbound at Texola — Oklahoma border port of entry",
    restriction_type: "inspection_checkpoint",
    restriction_value: "24/7",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "I-40 eastbound port of entry at Texola (Texas border). Open 24/7.",
    verification_status: "normalized-reviewed",
  },

  // ── WISCONSIN ─────────────────────────────────────────────────────
  {
    id: "state-wi-i94-milwaukee-clearance",
    source_id: "state-wi-dot",
    state: "WI",
    title: "I-94 Milwaukee interchange clearance screening",
    route_id: "I-94",
    geometry_type: "bbox",
    bbox: { min_lat: 43.02, max_lat: 43.06, min_lng: -87.95, max_lng: -87.88 },
    segment_description: "I-94 through Milwaukee — Zoo Interchange area",
    restriction_type: "bridge_clearance",
    restriction_value: 14.0,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_height_ft: 14.0 },
    permit_required: true,
    raw_text: "Zoo Interchange reconstruction area. Limited clearances — OS loads check WisDOT.",
    verification_status: "normalized-reviewed",
  },

  // ── MINNESOTA ─────────────────────────────────────────────────────
  {
    id: "state-mn-i35w-minneapolis-bridge-weight",
    source_id: "state-mn-dot",
    state: "MN",
    title: "I-35W Minneapolis bridge weight advisory",
    route_id: "I-35W",
    geometry_type: "bbox",
    bbox: { min_lat: 44.96, max_lat: 44.99, min_lng: -93.29, max_lng: -93.24 },
    segment_description: "I-35W Mississippi River crossing at Minneapolis",
    restriction_type: "bridge_weight",
    restriction_value: 80000,
    restriction_units: "lb",
    applies_to_vehicle_class: "overweight",
    vehicle_applicability: { max_weight_lb: 80000 },
    permit_required: true,
    raw_text: "I-35W bridge weight posting at Minneapolis. Overweight loads require MnDOT coordination.",
    verification_status: "normalized-reviewed",
  },

  // ── KENTUCKY ──────────────────────────────────────────────────────
  {
    id: "state-ky-i65-louisville-tunnel-clearance",
    source_id: "state-ky-restrictions",
    state: "KY",
    title: "I-65 Louisville approach clearance screening",
    route_id: "I-65",
    geometry_type: "bbox",
    bbox: { min_lat: 38.22, max_lat: 38.28, min_lng: -85.78, max_lng: -85.72 },
    segment_description: "I-65 approach to Kennedy Bridge and downtown Louisville",
    restriction_type: "bridge_clearance",
    restriction_value: 14.5,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_height_ft: 14.5 },
    permit_required: true,
    raw_text: "I-65 downtown Louisville approach structures. Over-height loads must coordinate with KYTC.",
    verification_status: "normalized-reviewed",
  },

  // ── WEST VIRGINIA ─────────────────────────────────────────────────
  {
    id: "state-wv-i77-turnpike-clearance",
    source_id: "state-wv-dot",
    state: "WV",
    title: "WV Turnpike (I-77) tunnel clearance screening",
    route_id: "I-77 (WV Turnpike)",
    geometry_type: "bbox",
    bbox: { min_lat: 37.75, max_lat: 37.85, min_lng: -80.85, max_lng: -80.75 },
    segment_description: "I-77 WV Turnpike — East River Mountain and Big Walker Mountain tunnels approach",
    restriction_type: "tunnel_clearance",
    restriction_value: 13.5,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_height_ft: 13.5 },
    permit_required: true,
    raw_text: "WV Turnpike tunnels: standard clearance 13'6\". OS loads must use alternate routes.",
    verification_status: "normalized-reviewed",
  },

  // ── SOUTH CAROLINA ────────────────────────────────────────────────
  {
    id: "state-sc-i26-charleston-clearance",
    source_id: "state-sc-dot",
    state: "SC",
    title: "I-26 Charleston port approach clearance",
    route_id: "I-26",
    geometry_type: "bbox",
    bbox: { min_lat: 32.85, max_lat: 32.90, min_lng: -80.00, max_lng: -79.92 },
    segment_description: "I-26 terminal approach to Port of Charleston",
    restriction_type: "bridge_clearance",
    restriction_value: 14.5,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_height_ft: 14.5 },
    permit_required: true,
    raw_text: "Port of Charleston approach structures — verify clearance for over-height containers.",
    verification_status: "normalized-reviewed",
  },

  // ── ALABAMA ───────────────────────────────────────────────────────
  {
    id: "state-al-mobile-tunnel-hazmat",
    source_id: "state-al-mobile-tunnel-restrictions",
    state: "AL",
    title: "George Wallace Tunnel hazmat restriction",
    route_id: "I-10",
    geometry_type: "bbox",
    bbox: { min_lat: 30.68, max_lat: 30.70, min_lng: -88.05, max_lng: -88.03 },
    segment_description: "I-10 George Wallace Tunnel in Mobile",
    restriction_type: "state_hazmat",
    hazmat_applicability: {
      restricted: true,
      description: "Hazardous materials are prohibited in the George Wallace Tunnel. Use the Cochrane-Africatown Bridge (US 98/AL 165) as an alternate.",
    },
    applies_to_vehicle_class: "hazmat",
    raw_text: "Hazardous materials are prohibited in the George Wallace Tunnel on I-10.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-al-mobile-tunnel-clearance",
    source_id: "state-al-mobile-tunnel-restrictions",
    state: "AL",
    title: "George Wallace Tunnel height restriction",
    route_id: "I-10",
    geometry_type: "bbox",
    bbox: { min_lat: 30.68, max_lat: 30.70, min_lng: -88.05, max_lng: -88.03 },
    segment_description: "I-10 George Wallace Tunnel in Mobile",
    restriction_type: "tunnel_clearance",
    restriction_value: 13.5,
    restriction_units: "ft",
    vehicle_applicability: { max_height_ft: 13.5 },
    applies_to_vehicle_class: "all-trucks",
    raw_text: "Vertical clearance in the George Wallace Tunnel is 13 feet 6 inches.",
    verification_status: "normalized-reviewed",
  },

  // ── ARKANSAS ──────────────────────────────────────────────────────
  {
    id: "state-ar-hope-poe",
    source_id: "state-ar-ports-of-entry",
    state: "AR",
    title: "Hope Port of Entry screening",
    route_id: "I-30",
    geometry_type: "bbox",
    bbox: { min_lat: 33.72, max_lat: 33.76, min_lng: -93.55, max_lng: -93.45 },
    segment_description: "I-30 westbound near Hope at the Arkansas Port of Entry",
    restriction_type: "inspection_checkpoint",
    restriction_value: "POE",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "Arkansas Highway Police Port of Entry located on Interstate 30 near Hope.",
    verification_status: "normalized-reviewed",
  },

  // ── CONNECTICUT ───────────────────────────────────────────────────
  {
    id: "state-ct-route15-parkway-ban",
    source_id: "state-ct-parkway-restrictions",
    state: "CT",
    title: "Connecticut parkways commercial vehicle prohibition",
    route_id: "Route 15 / SR 796",
    geometry_type: "polyline",
    polyline: {
      coordinates: [
        { lat: 41.02, lng: -73.63 },
        { lat: 41.06, lng: -73.56 },
        { lat: 41.11, lng: -73.48 },
        { lat: 41.17, lng: -73.18 },
        { lat: 41.24, lng: -73.03 },
        { lat: 41.35, lng: -72.90 },
        { lat: 41.50, lng: -72.83 },
      ],
      buffer_miles: 0.45,
    },
    segment_description: "Merritt Parkway, Wilbur Cross Parkway, and Milford Parkway corridor",
    restriction_type: "truck_prohibited",
    restriction_value: true,
    applies_to_vehicle_class: "all-trucks",
    raw_text: "Commercial vehicles, trailers, and oversized vehicles are prohibited from the Connecticut parkways. Published parkway limits include 8 ft height, 24 ft length, and 7 ft 6 in width unless specifically exempted.",
    verification_status: "normalized-reviewed",
  },

  // ── DELAWARE ──────────────────────────────────────────────────────
  {
    id: "state-de-dmb-hazmat",
    source_id: "state-de-bridge-hazmat",
    state: "DE",
    title: "Delaware Memorial Bridge hazmat restriction",
    route_id: "I-295 / US 40",
    geometry_type: "bbox",
    bbox: { min_lat: 39.68, max_lat: 39.70, min_lng: -75.55, max_lng: -75.52 },
    segment_description: "Delaware Memorial Bridge corridor on I-295",
    restriction_type: "state_hazmat",
    hazmat_applicability: {
      restricted: true,
      description: "Certain hazardous materials are restricted or require escort on the Delaware Memorial Bridge. Contact DRBA police before crossing.",
    },
    applies_to_vehicle_class: "hazmat",
    advisory_only: true,
    raw_text: "Hazardous materials restrictions and escort requirements apply to the Delaware Memorial Bridge as per DRBA regulations.",
    verification_status: "normalized-reviewed",
  },

  // ── IDAHO ─────────────────────────────────────────────────────────
  {
    id: "state-id-huetter-poe",
    source_id: "state-id-ports-of-entry",
    state: "ID",
    title: "Huetter Port of Entry screening",
    route_id: "I-90",
    geometry_type: "bbox",
    bbox: { min_lat: 47.68, max_lat: 47.72, min_lng: -116.94, max_lng: -116.84 },
    segment_description: "I-90 two miles west of Coeur d'Alene at the Huetter Port of Entry",
    restriction_type: "inspection_checkpoint",
    restriction_value: "POE",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "Huetter Port of Entry located 2 miles west of Coeur d'Alene on I-90.",
    verification_status: "normalized-reviewed",
  },

  // ── IOWA ──────────────────────────────────────────────────────────
  {
    id: "state-ia-dallas-county-weigh-station",
    source_id: "state-ia-dot",
    state: "IA",
    title: "Dallas County weigh station screening",
    route_id: "I-80",
    geometry_type: "bbox",
    bbox: { min_lat: 41.54, max_lat: 41.60, min_lng: -93.97, max_lng: -93.82 },
    segment_description: "I-80 between Van Meter and Waukee/Booneville near the Dallas County weigh station",
    restriction_type: "inspection_checkpoint",
    restriction_value: "weigh-station",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "Dallas County weigh station between Van Meter (exit 113) and Waukee/Booneville (exit 117) on I-80.",
    verification_status: "normalized-reviewed",
  },

  // ── KANSAS ────────────────────────────────────────────────────────
  {
    id: "state-ks-kanorado-poe",
    source_id: "state-ks-ports-of-entry",
    state: "KS",
    title: "Kanorado Port of Entry screening",
    route_id: "I-70",
    geometry_type: "bbox",
    bbox: { min_lat: 39.32, max_lat: 39.35, min_lng: -102.04, max_lng: -102.00 },
    segment_description: "I-70 eastbound at the Kansas/Colorado state line near Kanorado",
    restriction_type: "inspection_checkpoint",
    restriction_value: "POE",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "Kanorado Port of Entry on I-70 at the Kansas-Colorado state line.",
    verification_status: "normalized-reviewed",
  },

  // ── MAINE ─────────────────────────────────────────────────────────
  {
    id: "state-me-york-weigh-station",
    source_id: "state-me-turnpike-restrictions",
    state: "ME",
    title: "York weigh station screening",
    route_id: "I-95",
    geometry_type: "bbox",
    bbox: { min_lat: 43.15, max_lat: 43.20, min_lng: -70.68, max_lng: -70.62 },
    segment_description: "I-95 Maine Turnpike northbound/southbound near York at the weigh station",
    restriction_type: "inspection_checkpoint",
    restriction_value: "weigh-station",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "York weigh station on the Maine Turnpike (I-95) for commercial vehicle screening.",
    verification_status: "normalized-reviewed",
  },

  // ── MASSACHUSETTS ────────────────────────────────────────────────
  {
    id: "state-ma-storrow-drive-ban",
    source_id: "state-ma-dcr-road-restrictions",
    state: "MA",
    title: "Storrow Drive cars-only restriction",
    route_id: "Storrow Drive / Soldiers Field Road / Memorial Drive",
    geometry_type: "polyline",
    polyline: {
      coordinates: [
        { lat: 42.354, lng: -71.129 },
        { lat: 42.357, lng: -71.107 },
        { lat: 42.359, lng: -71.086 },
        { lat: 42.359, lng: -71.063 },
        { lat: 42.361, lng: -71.046 },
      ],
      buffer_miles: 0.22,
    },
    segment_description: "Charles River park roads through Boston and Cambridge",
    restriction_type: "truck_prohibited",
    restriction_value: true,
    applies_to_vehicle_class: "all-trucks",
    raw_text: "Storrow Drive, Soldiers Field Road, and Memorial Drive are restricted to cars only and should not be used by trucks or moving vans.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-ma-storrow-drive-height",
    source_id: "state-ma-dcr-road-restrictions",
    state: "MA",
    title: "Storrow Drive low-clearance screening",
    route_id: "Storrow Drive / Soldiers Field Road / Memorial Drive",
    geometry_type: "bbox",
    bbox: { min_lat: 42.35, max_lat: 42.37, min_lng: -71.13, max_lng: -71.04 },
    segment_description: "Low-clearance river road approaches through Boston and Cambridge",
    restriction_type: "route_height_limit",
    restriction_value: 9,
    restriction_units: "ft",
    applies_to_vehicle_class: "all-trucks",
    vehicle_applicability: { max_height_ft: 9 },
    raw_text: "These roadways are restricted to cars only and have bridge clearances as low as nine feet in some locations.",
    verification_status: "normalized-reviewed",
  },

  // ── MISSISSIPPI ───────────────────────────────────────────────────
  {
    id: "state-ms-moss-point-poe",
    source_id: "state-ms-dot",
    state: "MS",
    title: "Moss Point Port of Entry screening",
    route_id: "I-10",
    geometry_type: "bbox",
    bbox: { min_lat: 30.42, max_lat: 30.45, min_lng: -88.52, max_lng: -88.48 },
    segment_description: "I-10 westbound near Moss Point at the Mississippi Port of Entry",
    restriction_type: "inspection_checkpoint",
    restriction_value: "POE",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "Moss Point Port of Entry on Interstate 10 for motor carrier screening.",
    verification_status: "normalized-reviewed",
  },

  // ── MONTANA ───────────────────────────────────────────────────────
  {
    id: "state-mt-haugan-poe",
    source_id: "state-mt-ports-of-entry",
    state: "MT",
    title: "Haugan Port of Entry screening",
    route_id: "I-90",
    geometry_type: "bbox",
    bbox: { min_lat: 47.38, max_lat: 47.41, min_lng: -115.42, max_lng: -115.38 },
    segment_description: "I-90 eastbound at the Idaho/Montana state line near Haugan",
    restriction_type: "inspection_checkpoint",
    restriction_value: "POE",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "Haugan Port of Entry on I-90 at the Idaho-Montana state line.",
    verification_status: "normalized-reviewed",
  },

  // ── NEBRASKA ──────────────────────────────────────────────────────
  {
    id: "state-ne-i80-greenwood-weigh-station",
    source_id: "state-ne-weigh-stations",
    state: "NE",
    title: "Greenwood I-80 weigh station screening",
    route_id: "I-80",
    geometry_type: "bbox",
    bbox: { min_lat: 41.08, max_lat: 41.12, min_lng: -96.42, max_lng: -96.31 },
    segment_description: "I-80 weigh station scale site near mile marker 415 at Greenwood",
    restriction_type: "inspection_checkpoint",
    restriction_value: "weigh-station",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "I-80 weigh station scale site located near mile marker 415 on I-80 near Greenwood, Nebraska.",
    verification_status: "normalized-reviewed",
  },

  // ── NEVADA ────────────────────────────────────────────────────────
  {
    id: "state-nv-us93-boulder-city-width",
    source_id: "state-nv-prohibited-routes",
    state: "NV",
    title: "US 93 Boulder City width restriction screening",
    route_id: "US 93",
    geometry_type: "polyline",
    polyline: {
      coordinates: [
        { lat: 35.98, lng: -114.84 },
        { lat: 35.95, lng: -114.79 },
        { lat: 35.92, lng: -114.75 },
      ],
      buffer_miles: 0.35,
    },
    segment_description: "US 93 from Nevada Way/Buchanan Boulevard in Boulder City to the Arizona/Nevada state line",
    restriction_type: "route_width_limit",
    restriction_value: 8.5,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_width_ft: 8.5 },
    permit_required: true,
    raw_text: "Prohibited route US 93/Great Basin Highway from Boulder City to the Arizona/Nevada state line for over-width permitted moves as identified in NDOT route instructions.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-nv-us93-boulder-city-length",
    source_id: "state-nv-prohibited-routes",
    state: "NV",
    title: "US 93 Boulder City length restriction screening",
    route_id: "US 93",
    geometry_type: "polyline",
    polyline: {
      coordinates: [
        { lat: 35.98, lng: -114.84 },
        { lat: 35.95, lng: -114.79 },
        { lat: 35.92, lng: -114.75 },
      ],
      buffer_miles: 0.35,
    },
    segment_description: "US 93 from Nevada Way/Buchanan Boulevard in Boulder City to the Arizona/Nevada state line",
    restriction_type: "route_length_limit",
    restriction_value: 70,
    restriction_units: "ft",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { max_length_ft: 70 },
    permit_required: true,
    raw_text: "Vehicles over 70 feet in length are prohibited on identified NDOT prohibited routes unless separately routed and authorized.",
    verification_status: "normalized-reviewed",
  },

  // ── NEW HAMPSHIRE ─────────────────────────────────────────────────
  {
    id: "state-nh-franconia-notch-restriction",
    source_id: "state-nh-franconia-notch-rules",
    state: "NH",
    title: "Franconia Notch commercial vehicle restriction",
    route_id: "I-93 / US 3",
    geometry_type: "bbox",
    bbox: { min_lat: 44.10, max_lat: 44.18, min_lng: -71.70, max_lng: -71.65 },
    segment_description: "Franconia Notch Parkway on I-93 / US 3",
    restriction_type: "truck_prohibited",
    restriction_value: true,
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "Trucks with more than 2 axles are generally prohibited from the Franconia Notch Parkway portion of Interstate 93, with certain exceptions for local deliveries.",
    verification_status: "normalized-reviewed",
  },

  // ── NORTH DAKOTA ──────────────────────────────────────────────────
  {
    id: "state-nd-bismarck-weigh-station",
    source_id: "state-nd-weigh-stations",
    state: "ND",
    title: "Bismarck weigh station screening",
    route_id: "I-94",
    geometry_type: "bbox",
    bbox: { min_lat: 46.80, max_lat: 46.84, min_lng: -100.90, max_lng: -100.80 },
    segment_description: "I-94 eastbound near Bismarck at the West Bismarck weigh station",
    restriction_type: "inspection_checkpoint",
    restriction_value: "weigh-station",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "West Bismarck weigh station on I-94 eastbound for motor carrier screening and enforcement.",
    verification_status: "normalized-reviewed",
  },

  // ── OREGON ────────────────────────────────────────────────────────
  {
    id: "state-or-woodburn-poe",
    source_id: "state-or-truck-scales",
    state: "OR",
    title: "Woodburn Port of Entry screening",
    route_id: "I-5",
    geometry_type: "bbox",
    bbox: { min_lat: 45.11, max_lat: 45.17, min_lng: -122.87, max_lng: -122.79 },
    segment_description: "Southbound I-5 truck scale and port-of-entry corridor at Woodburn",
    restriction_type: "inspection_checkpoint",
    restriction_value: "POE",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "Woodburn Port of Entry on Interstate 5 is part of ODOT's motor carrier enforcement and preclearance network.",
    verification_status: "normalized-reviewed",
  },

  // ── RHODE ISLAND ──────────────────────────────────────────────────
  {
    id: "state-ri-pell-bridge-permit-advisory",
    source_id: "state-ri-bridge-permits",
    state: "RI",
    title: "Newport Pell Bridge oversize permit advisory",
    route_id: "RI 138",
    geometry_type: "bbox",
    bbox: { min_lat: 41.49, max_lat: 41.54, min_lng: -71.35, max_lng: -71.28 },
    segment_description: "Claiborne Pell Bridge crossing between Newport and Jamestown on RI 138",
    restriction_type: "escort_requirement",
    restriction_value: "additional-permit",
    applies_to_vehicle_class: "oversize",
    vehicle_applicability: { min_width_ft: 8.6 },
    permit_required: true,
    advisory_only: true,
    raw_text: "The Rhode Island Turnpike and Bridge Authority requires additional permitting beyond Rhode Island over-the-road permits for overweight and overwide crossings of the Newport Pell Bridge.",
    verification_status: "normalized-reviewed",
  },

  // ── SOUTH DAKOTA ──────────────────────────────────────────────────
  {
    id: "state-sd-jefferson-poe",
    source_id: "state-sd-ports-of-entry",
    state: "SD",
    title: "Jefferson Port of Entry screening",
    route_id: "I-29",
    geometry_type: "bbox",
    bbox: { min_lat: 42.58, max_lat: 42.62, min_lng: -96.58, max_lng: -96.48 },
    segment_description: "I-29 northbound near Jefferson at the South Dakota Port of Entry",
    restriction_type: "inspection_checkpoint",
    restriction_value: "POE",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "Jefferson Port of Entry on I-29 for South Dakota motor carrier screening.",
    verification_status: "normalized-reviewed",
  },

  // ── UTAH ──────────────────────────────────────────────────────────
  {
    id: "state-ut-st-george-poe",
    source_id: "state-ut-ports-of-entry",
    state: "UT",
    title: "St. George Port of Entry screening",
    route_id: "I-15",
    geometry_type: "bbox",
    bbox: { min_lat: 37.01, max_lat: 37.05, min_lng: -113.64, max_lng: -113.55 },
    segment_description: "I-15 milepost 1 just north of the Arizona border at the St. George Port of Entry",
    restriction_type: "inspection_checkpoint",
    restriction_value: "POE",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "St. George Port of Entry on I-15 at milepost 1 is part of Utah's motor carrier screening network.",
    verification_status: "normalized-reviewed",
  },
  {
    id: "state-ut-echo-poe",
    source_id: "state-ut-ports-of-entry",
    state: "UT",
    title: "Echo Port of Entry screening",
    route_id: "I-80",
    geometry_type: "bbox",
    bbox: { min_lat: 40.98, max_lat: 41.03, min_lng: -111.44, max_lng: -111.34 },
    segment_description: "Westbound I-80 entry corridor from Wyoming at the Echo Port of Entry",
    restriction_type: "inspection_checkpoint",
    restriction_value: "POE",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "Westbound I-80 from Wyoming enters Utah through the Echo Port of Entry, a designated motor carrier permit and screening location.",
    verification_status: "normalized-reviewed",
  },

  // ── VERMONT ───────────────────────────────────────────────────────
  {
    id: "state-vt-smugglers-notch-length",
    source_id: "state-vt-smugglers-notch",
    state: "VT",
    title: "Smugglers' Notch commercial length restriction",
    route_id: "VT 108",
    geometry_type: "bbox",
    bbox: { min_lat: 44.53, max_lat: 44.60, min_lng: -72.80, max_lng: -72.72 },
    segment_description: "Smugglers' Notch segment of Vermont Route 108",
    restriction_type: "route_length_limit",
    restriction_value: 45,
    restriction_units: "ft",
    applies_to_vehicle_class: "all-trucks",
    vehicle_applicability: { max_length_ft: 45 },
    permit_required: true,
    raw_text: "Single-frame motor vehicles over 40 feet and tractor units with one or more attached trailers over 45 feet in total length are prohibited on the Smugglers' Notch segment of VT 108.",
    verification_status: "normalized-reviewed",
  },

  // ── WYOMING ───────────────────────────────────────────────────────
  {
    id: "state-wy-evanston-poe",
    source_id: "state-wy-ports-of-entry",
    state: "WY",
    title: "Evanston Port of Entry screening",
    route_id: "I-80",
    geometry_type: "bbox",
    bbox: { min_lat: 41.25, max_lat: 41.29, min_lng: -111.03, max_lng: -110.96 },
    segment_description: "I-80 freight entry corridor at Evanston Port of Entry",
    restriction_type: "inspection_checkpoint",
    restriction_value: "POE",
    applies_to_vehicle_class: "all-trucks",
    advisory_only: true,
    raw_text: "Wyoming ports of entry include an I-80 facility at Evanston used for commercial carrier screening and permits.",
    verification_status: "normalized-reviewed",
  },
];

export function getRoutingSourceById(id: string) {
  return ROUTING_SOURCE_REGISTRY.find((entry) => entry.id === id) ?? null;
}
